### ISSUE TITLE
indicating case weight support in `show_model_info()`

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/parsnip#1000]
From #996:

``` r
library(tidymodels)

# custom model info:
set_new_model("discrim_mixture")
set_model_mode(model = "discrim_mixture", mode = "classification")
set_model_engine(
  "discrim_mixture", 
  mode = "classification", 
  eng = "mda"
)
set_dependency("discrim_mixture", eng = "mda", pkg = "mda")

show_model_info("discrim_mixture")
#> Information for `discrim_mixture`
#>  modes: unknown, classification 
#> 
#>  engines: 
#>    classification: mdaNA
#> 
#> ¹The model can use case weights.
#> 
#>  no registered arguments.
#> 
#>  no registered fit modules.
#> 
#>  no registered prediction modules.

show_model_info("linear_reg")
#> Information for `linear_reg`
#>  modes: unknown, regression 
#> 
#>  engines: 
#>    regression: brulee, glm¹, glmnet¹, keras, lm¹, spark¹, stan¹
#> 
#> ¹The model can use case weights.
#> 
#>  [truncated output for clarity]
```

<sup>Created on 2023-09-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

_"¹The model can use case weights."_ means that only engines with the superscripted 1 can use case weights. In cases where some engines _can_ support case weights, the notation is clear, but when there's no case weight support for any engine (and thus no superscripted 1 previouslt), that footnote seems like it's saying that every engine used with the model can use case weights. We ought to fix that—I'll open up a separate issue.

_Originally posted by @simonpcouch in https://github.com/tidymodels/parsnip/issues/996#issuecomment-1719792452_

**Comment by hfrick** [comment]
offtopic: issue #1000 !!
