### ISSUE TITLE
brms support

### ISSUE THREAD

**Issue by joscani** [tidymodels/parsnip#1002]
Hi. I know there is [bayesian](https://github.com/hsbadr/bayesian) package . But the problem is Bayesian library doesn't support weights from brms formula like that target1 | resp_weights(n) ~ (1 | edad_cat) + (1 | valor_cliente) + (1 | tipo). 

I wrote an [issue](https://github.com/hsbadr/bayesian/issues/14) a year ago.. 

Is there any way to use brms in tidymodels . My goal is using brms and vetiver to version my models. 
Thanks

**Comment by simonpcouch** [comment]
Thanks for the issue! Given that this is an issue with a community-contributed extension package, there's little we can do from parsnip's perspective. I will go ahead and close this in favor of discussions on that package's repo.
