### ISSUE TITLE
Add oPLS model

### ISSUE THREAD

**Issue by AlbanOtt2** [tidymodels/parsnip#1006]
Hi parsnip dev,

Thank you for your efforts, we are moving from our many models implementation to tidymodels.

## Implement oPLS as an option of PLS

NB: here oPLS means [orthogonal PLS](https://en.wikipedia.org/wiki/Partial_least_squares_regression#Extensions)
In chemometry and other fields like omics analysis, one may prefer to use oPLS rather than standard PLS.
> This leads to improved diagnostics, as well as more easily interpreted visualization. However, these changes only improve the interpretability, not the predictivity, of the PLS models[^1]

[^1]: Trygg, J. and Wold, S. (2002), Orthogonal projections to latent structures (O-PLS). J. Chemometrics, 16: 119-128. https://doi.org/10.1002/cem.695

**Comment by simonpcouch** [comment]
Thanks for the issue, @AlbanOtt2!

This sounds like a great idea for a community-contributed parsnip extension package that adds an additional engine for the [pls model](https://parsnip.tidymodels.org/reference/pls.html). We've written docs on how to do so [here](https://www.tidymodels.org/learn/develop/models/), and the [plsmod package](https://github.com/tidymodels/plsmod) shows an example of how to do that for another engine.
