### ISSUE TITLE
Add "Least square support vector machine"?

### ISSUE THREAD

**Issue by Freestyleyang** [tidymodels/parsnip#1008]
Hi There,

Thank you for your efforts.

Can I ask if it is possible to include "Least square support vector machine" in tidymodels? The "Least square support vector machine" is currently available in the R package `kernlab` as the function `lssvm`. Thank you.

**Comment by simonpcouch** [comment]
Thanks for the issue!

This sounds like a great idea for a parsnip extension package, implementing a new "lssvm" engine for each of the kernels supported in parsnip. parsnip's infrastructure allows for anyone to create their own package that integrates with parsnip (and thus the rest of the tidymodels ecosystem)! We have some documentation on how to create custom model specifications [on the tidymodels website](https://www.tidymodels.org/learn/develop/models/). We'd recommend creating a new package of your own—poissonreg would indeed be a great place to see how those specifications are situated in a package.

Feel free to holler if you run into any issues while building the package or have a finished product you'd like us to feature [on the tidymodels website](https://www.tidymodels.org/find/parsnip/).

**Comment by simonpcouch** [comment]
Going to go ahead and close. If anyone ends up taking this on and running into issues, feel free to holler.
