### ISSUE TITLE
Naive Bayes slow prediction

### ISSUE THREAD

**Issue by jxu** [tidymodels/parsnip#1010]
I'm not sure if this is a problem with klaR or parsnip per se, but naive bayes prediction takes a long time on a large dataset, much longer than training. It might be because of the large number of warnings generated? 

```
> warnings()
Warning messages:
1: In FUN(X[[i]], ...) :
  Numerical 0 probability for all classes with observation 1
2: In FUN(X[[i]], ...) :
  Numerical 0 probability for all classes with observation 2
3: In FUN(X[[i]], ...) :
  Numerical 0 probability for all classes with observation 3
```
etc.

**Comment by EmilHvitfeldt** [comment]
Hello @jxu 👋 

This is an known issue, and not much we can do on our end. We do have another engine [naivebayes](https://parsnip.tidymodels.org/reference/details_naive_Bayes_naivebayes.html) that has a significantly faster prediction time

``` r
library(parsnip)
library(modeldata)
library(discrim)

nb_klaR <- naive_Bayes() |>
  set_engine("klaR") |>
  fit(Street ~ ., data = ames)

tictoc::tic()
predict(nb_klaR, ames)
#> observation 2930
#> # A tibble: 2,930 × 1
#>    .pred_class
#>    <fct>      
#>  1 Pave       
#>  2 Pave       
#>  3 Pave       
#>  4 Pave       
#>  5 Pave       
#>  6 Pave       
#>  7 Pave       
#>  8 Pave       
#>  9 Pave       
#> 10 Pave       
#> # ℹ 2,920 more rows
tictoc::toc()
#> 4.247 sec elapsed

nb_naivebayes <- naive_Bayes() |>
  set_engine("naivebayes") |>
  fit(Street ~ ., data = ames)

tictoc::tic()
predict(nb_naivebayes, ames)
#> # A tibble: 2,930 × 1
#>    .pred_class
#>    <fct>      
#>  1 Pave       
#>  2 Pave       
#>  3 Pave       
#>  4 Pave       
#>  5 Pave       
#>  6 Pave       
#>  7 Pave       
#>  8 Pave       
#>  9 Pave       
#> 10 Pave       
#> # ℹ 2,920 more rows
tictoc::toc()
#> 0.025 sec elapsed
```

**Comment by jxu** [comment]
Thanks for getting back to me. Is there a reason why naivebayes is not the default? The Ames dataset, 2930 x 74, is not even that big, and naive bayes is supposed to be extremely fast.

**Comment by jxu** [comment]
Related #1007

**Comment by EmilHvitfeldt** [comment]
{klaR} was the original engine for `naive_Bayes()` and when then {naivebayes} engine as added, {klaR} was kept the default to keep the old behavior. E.I. it was likely that some some people relied on the fact that a {klaR} model came through and it would break things if that changed.

https://github.com/tidymodels/discrim/commit/b27a1c51df1ce61e8e23d34e750e8f85529cd24e

**Comment by simonpcouch** [comment]
Will go ahead and close. Glad we've documented this here!
