### ISSUE TITLE
Use `brulee::brulee_activations()` to check for available activation functions in `parsnip::check_args.mlp()`

### ISSUE THREAD

**Issue by christophscheuch** [tidymodels/parsnip#1019]
A recent change in `brulee` introduced new activation functions and `brulee_activations()`, which provides available functions (see [PR #74](https://github.com/tidymodels/brulee/pull/74)). However, `parsnip` does not support these new activation functions yet, because `parsnip::check_args.mlp()` has hard coded values (see function [definition here](https://github.com/tidymodels/parsnip/blob/b462f76f9593bb29f8c93b022cef92ed0ec3a9c4/R/mlp.R#L145)).

Would be great to have support for the new activation functions in parsnip.

**Comment by hfrick** [comment]
Thanks for flagging this @christophscheuch ! We'll get this opened up once the dust of the current work on {brulee} by @topepo has settled a bit.

**Comment by topepo** [comment]
I am working on this now that I just sent brulee to CRAN (with those features).
