### ISSUE TITLE
Documentation issue: rand_forest function help falsely lists h2o as an engine option

### ISSUE THREAD

**Issue by birbritto** [tidymodels/parsnip#1077]
when calling the help on rand_forest:

`?rand_forest`

It lists h2o in the engine-specific pages for the model, implying that that's an option for an engine. However, using:

`show_engines('rand_forest') `gives:

```
# A tibble: 6 × 2
  engine       mode          
  <chr>        <chr>         
1 ranger       classification
2 ranger       regression    
3 randomForest classification
4 randomForest regression    
5 spark        classification
6 spark        regression 
```

and trying to use h2o gives this error:

```
rf_fit <- rand_forest(trees = 100, mode = "unknown") %>%
+   set_engine("h2o")  %>% fit ( something ~ var1 + var2 etc, data = training_data)
```

```
Error in `set_engine()`:
! Engine 'h2o' is not supported for `rand_forest()`. See `show_engines('rand_forest')`.
```

Requesting an update to the documentation if that makes sense. Thank you

**Comment by simonpcouch** [comment]
Thanks for the issue!

The `rand_forest` docs note that h2o requires a parsnip extension package with the "2" superscript. From `?rand_forest`

<img width="836" alt="Screenshot 2024-02-28 at 10 15 55 AM" src="https://github.com/tidymodels/parsnip/assets/35748691/76ec8d15-2b05-4839-8267-a57fa2887490">

Clicking the h2o hyperlink from the docs will show that you need to load the [agua](https://agua.tidymodels.org/) extension package with `library(agua)` to use this engine. :)

I will keep this issue open in case we think we might be able to provide better errors or docs to make this visible to folks.
