### ISSUE TITLE
Models documentation header mismatch

### ISSUE THREAD

**Issue by marcelglueck** [tidymodels/parsnip#1080]
## The problem
It seems that the header for quite some neural network models does not fit their content:

Example:
- https://parsnip.tidymodels.org//reference/details_mlp_keras.html: Header says "Multilayer perceptron", but the document says otherwise ("keras_mlp() fits a single layer...")

The same applies to https://parsnip.tidymodels.org//reference/details_mlp_nnet.html. Please correct me if I am wrong.

**Comment by topepo** [comment]
This isn't necessary. Historically, the input layer is counted. An MLP is a neural network with at least one layer of hidden units. For example, long ago, logistic regression was considered a single-layer perceptron.

We could amend the documentation to say a "single layer of hidden units" if that makes it less confusing.

**Comment by marcelglueck** [comment]
Thanks for clarifying. Not sure whether the amendment makes it less confusing. Might be just me not being a ML guy. 😅
