### ISSUE TITLE
Use {cli} for error messages

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/parsnip#1081]
Most or all errors thrown in this package are made via `rlang::abort()`. We are transitioning to `cli::cli_abort()` to make use of the richer styling options for errors via cli (which calls rlang under the hood). 

It is often sufficient to search for and replace the rlang version with the cli version together with adding a little bit of styling.

Some examples of the styling possibilities are in the [general introduction](https://cli.r-lib.org/articles/semantic-cli.html) under the section of [Inline text formatting](https://cli.r-lib.org/articles/semantic-cli.html#inline-text-formatting). More details on [inline formatting](https://cli.r-lib.org/reference/inline-markup.html) and [pluralization](https://cli.r-lib.org/articles/pluralization.html). 

One aspect to watch out for when transitioning from `rlang::abort()` to `cli::cli_abort()` are messages pre-assembled from user input as described [here](https://rlang.r-lib.org/dev/reference/topic-condition-formatting.html#transitioning-from-abort-to-cli-abort-).

#499 can serve as an example.

We are splitting this up into several batches:
- [x] #1091
- [x] #1093
- [x] #1136
- [x] #1137
- [x] #1138
- [x] #1139 
- [x] #1140 
- [x] #1141 
- [x] #1142

**Comment by simonpcouch** [comment]
9/9 done! Huzzah!

**Comment by simonpcouch** [comment]
I was a bit too eager in closing this—will reopen and later close with one last PR for the stray remaining ones.
