### ISSUE TITLE
add utility to list needed engine packages

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/parsnip#1113]
For installation/setup purposes, it'd be great to have some kind of utility to find all of the engine package installs needed to plausibly fit any model in the parsnip model env. In other words, if parsnip listed all engines it supports in `Suggests`, what would they be?

I used this while setting up a new machine the other day to do so with a version of the model env that includes all engines supported by parsnip extensions:

``` r
library(tidyverse)
library(tidymodels)
lapply(parsnip:::extensions(), require, character.only = TRUE)
env <- parsnip::get_model_env()
pkgs_list <- as.list(env)[grepl("_pkgs", names(env), fixed= TRUE)]

all_possible_dependencies <-
  pkgs_list %>% 
  bind_rows() %>% 
  pull(pkg) %>% 
  list_flatten() %>% 
  unlist() %>% 
  unique()
```

**Comment by EmilHvitfeldt** [comment]
Is this different than `parsnip:::install_engine_packages()`? https://github.com/tidymodels/parsnip/blob/main/R/install_packages.R

**Comment by simonpcouch** [comment]
Not different enough to warrant this issue--thanks. :)
