### ISSUE TITLE
Register aorsf models for classification and regression

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#1126]
Extending #1120 to include these new engine/mode combinations to the parsnip "database"

**Comment by hfrick** [comment]
They are in bonsai already! 🎉  https://github.com/tidymodels/bonsai/pull/78

**Comment by simonpcouch** [comment]
I believe the changes this issue might refer to—including aorsf in parsnip's "model info file"—were included with #1120 via the changes to `models.tsv`.
