### ISSUE TITLE
Minor documentation update necessary for serialization of LightGBM models?

### ISSUE THREAD

**Issue by joranE** [tidymodels/parsnip#1131]
Given the changes in `bundle` about removing LightGBM bundlers (discussed [here](https://github.com/rstudio/bundle/issues/24)), is this bit in the documentation for the LightGBM engine for `boost_tree()` still relevant, or should it be removed?

> Models fitted with this engine may require native serialization methods to be properly saved and/or passed between R sessions.  To learn more about preparing fitted models for serialization, see the bundle package.

**Comment by simonpcouch** [comment]
Thanks for pointing this out!
