### ISSUE TITLE
mode as a required argument

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/parsnip#130]
The Scratch vignette articles says the following

> First, is the object that describes the model's mode(s). The modes are the type of model and the two main values are "classification" and "regression". __A third mode, "unknown", is used for initializing objects but models will fail if it is used further.__

Which suggest that unknown is used to create a specification, but I won't allow further. Which as far as I can see not what is happening right now.

``` r
library(parsnip)

model <- svm_poly(mode = "unknown") %>%
  set_engine("kernlab") %>%
  fit(cyl ~ ., data = mtcars)
#>  Setting default kernel parameters

model$spec$mode
#> [1] "regression"

model <- svm_poly(mode = "classification") %>%
  set_engine("kernlab") %>%
  fit(cyl ~ ., data = mtcars)
#>  Setting default kernel parameters

model$spec$mode
#> [1] "classification"
```

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

If there isn't a strong reason why it can't be, I would suggest that the `mode` argument should be explicitly set by the user before using `fit`. In other words, I would argue that have mode being inferred from data is a non-ideal choice.

**Comment by alexpghayes** [comment]
`cyl` is numeric so this is a data issue more than a parsnip issue? I agree that `mode` is weird though, see #85 for more thoughts.

**Comment by EmilHvitfeldt** [comment]
> cyl is numeric so this is a data issue more than a parsnip issue? 

Oh didn't notice that. The code was just an example that parsnip will assign/guess the mode if left unspecified.

**Comment by topepo** [comment]
The next version will require users to assign the mode for models that can do multiple types (e.g. classification or regression). 

The package now allows for different fit functions for different modes (to reduce the need for wrappers) and it needs to know the mode before `fit()` is executed.
