### ISSUE TITLE
Don't double import rlang functions

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/parsnip#141]
Ideally I think we would not import all of rlang, and only import what we use. These throw mainly harmless warnings on R 3.1

rlang::eval_tidy
https://github.com/tidymodels/parsnip/blob/1f96393b8a3caef2510bbf12a0ab8cca8981fa7b/NAMESPACE#L160

all of rlang
https://github.com/tidymodels/parsnip/blob/master/NAMESPACE#L126

location of importFrom
https://github.com/tidymodels/parsnip/blob/fc366b68b3c11c20f8c2f1a4f5ab7475c8b57c59/R/arguments.R#L128

**Comment by topepo** [comment]
There are times that I do that so that people (including myself) can recognize where the function is coming from.

**Comment by DavisVaughan** [comment]
i think if we have multiple `@importFrom` calls floating around all over the place (for clarity), that would be fine and roxygen knows what to do with that. the minor problem is that we have both `@import rlang` and `@importFrom rlang eval_tidy` which both get added to the NAMESPACE. If we remove the `@import rlang` and just `@importFrom` the things we use, it should go away.
