### ISSUE TITLE
model_spec as a part of set_engine()

### ISSUE THREAD

**Issue by grayskripko** [tidymodels/parsnip#142]
I've skimmed https://github.com/tidymodels/parsnip/issues/99 and still can't understand why ```model_spec``` object is a part of the ```engine``` object.
As for me, it's a pain to work with any ML library like ```mlr``` or ```caret``` because you need to keep in mind all the details of the function call. Eventually, for each my project I wrote wrappers to orient in a project faster. That's why I like parsnip, it's very similar to my point of view. I understand the need for```fit```  function and the ```spec``` as a flexible part of it. 
Why the ```engine``` entity can't be a part of ```spec``` or ```fit```?

**Comment by topepo** [comment]
I'm not sure what you are asking. The engine is a component of the model specification (not the other way around):

```r
> logistic_reg() %>% set_engine("glm") %>% str()
List of 5
 $ args    :List of 2
  ..$ penalty: language ~NULL
  .. ..- attr(*, ".Environment")=<environment: R_EmptyEnv> 
  ..$ mixture: language ~NULL
  .. ..- attr(*, ".Environment")=<environment: R_EmptyEnv> 
 $ eng_args: Named list()
  ..- attr(*, "class")= chr "quosures"
 $ mode    : chr "classification"
 $ method  : NULL
 $ engine  : chr "glm"
 - attr(*, "class")= chr [1:2] "logistic_reg" "model_spec"
```

**Comment by grayskripko** [comment]
I'm talking about the order they appear. In your example, you use ```logistic_reg()``` as an argument of ```set_engine```. I think, but maybe I'm wrong, that  ```set_engine``` should be an argument of ```logistic_reg()```

**Comment by EmilHvitfeldt** [comment]
In the way I see it, one of the central parts of `parsnip` is the separation between the **model specification** and the **computational engine**.

In the current framework (`logistic_reg()` as an argument of `set_engine()`) you are able to write what you want the model to do, this case a random forrest with some pre-set parameters.

``` r
my_model <- rand_forest(mode = "regression", mtry = 3, trees = 1000)
```

After you have decided what you want your model to do, then you decide how the calculations are done (which package backend should be used). You could start with the randomForest package.

``` r
my_fit <- my_model %>%
  set_engine("randomForest") %>%
  fit(output ~ var1 + var2 + var3, data = my_data)
```

however if you find that randomForest wasn't the right fit for you, you can easily change the engine

``` r
my_fit <- my_model %>%
  set_engine("ranger") %>%
  fit(output ~ var1 + var2 + var3, data = my_data)
```

Notice how we are not changing our model specifications as we still have the same modeling goals.

In the end I would say that the purpose (model specification) is more important than its implementation (computational engine) and is thus represented by the order in which they appear.

**Comment by topepo** [comment]
> I'm talking about the order they appear. In your example, you use ```logistic_reg()``` as an argument of ```set_engine```. I think, but maybe I'm wrong, that  ```set_engine``` should be an argument of ```logistic_reg()```

We do that so that the model object is [pipe-able](https://principles.tidyverse.org/unifying-principles.html#composable). We decided to exclude the engine an argument from the model specification functions because we want people to have to think about choosing the engine separately.

**Comment by alexpghayes** [comment]
Personally, I think of `model_spec` as defining a class of models and `engine` as specifying an estimator. These are definitely different things and being explicit about the estimator is good practice. For prediction problems this doesn't matter as much, but if you are sloppy about estimators when doing inference, everything falls apart pretty quick.

**Comment by grayskripko** [comment]
thank you, guys, I've figured out.
Another one point of view: ```model_spec``` is a placeholder for "harmonized" or "generalized" arguments. ```set_engine``` allows specifying engine-specific arguments in turn. 
Perhaps a summary of this thread could be added to the README file
