### ISSUE TITLE
Error in fitting probabilistic model for SVM in kernlab

### ISSUE THREAD

**Issue by reisner** [tidymodels/parsnip#144]
For some datasets, fitting a probabilistic model for SVM fails, giving:

```
line search fails
```

More information here: https://stackoverflow.com/questions/15895897/line-search-fails-in-training-ksvm-prob-model

Perhaps another SVM library would deal with this more gracefully? Or maybe a wrapper that could try other values for fitting the model?

**Comment by topepo** [comment]
That's a (long-standing) issue with `kernlab` which is otherwise great. 

We will eventually have our own (more robust) function for Platt scaling in the `probably` package. With that, we could do our own. 

This can also be a sign that the model is problematic, perhaps due to a class imbalance.

**Comment by reisner** [comment]
OK Sounds good, thanks. Feel free to close this issue if you'd like.
