### ISSUE TITLE
Feature Request: Failed model class and NA_model_?

### ISSUE THREAD

**Issue by billdenney** [tidymodels/parsnip#145]
Quick summary: Should a "failed_model" class exist (which may apply to any type of model), and should an NA_model_ constant exist?

For a myriad of reasons, models can fail to fit.  For summarization purposes and others, it can be useful to track the models that didn't work (i.e. in my case:  Yes, I did try, no it didn't work needs to be said in some reports).  For those cases, I think that a "failed_model" class or something similar to that could help.  I'd imagine that it would record as much as possible about the model that was attempted, and it would record the error message from the model in an easily accessible way (or error attribute, as applicable).

Related to this, if warnings are displayed from the model, but it still converges, it would be helpful to capture those (maybe that class could be "model_warnings" or maybe that's just an attribute of all fit models).

And, finally, there are some cases where having an `NA` value is useful for a model fit (I didn't want to fit that model, but the model fitting may be almost factorial in design, so I want to show something in an entry).  As discussed in a broom issue (tidymodels/broom#565), logical `NA` is not likely the best fit, so could some form of `NA_model_` constant make sense (maybe as a specific instance of the "failed_model" class suggested above)?

This is related to #123 and tidymodels/broom#600.

P.S.  Hi Max!

**Comment by topepo** [comment]
> Should a "failed_model" class exist (which may apply to any type of model), 

No. Probably not. 

Right now `parsnip` can catch those and the underlying `fit` element is a `try-error` object. I don't think that we need a new class there but we will need logic in the `predict` method (and others) to deal with this to avoid throwing more errors. 

> and should an NA_model_ constant exist?

As a return value for `predict`? If you mean as the results in `fit` then no; the current class (`try-error`) captures the failure and contains some diagnostic info about the failure. Using a more atomic data type wouldn't allow us to do that.

**Comment by billdenney** [comment]
Thanks for the pointer here.  I hadn't fully tested my question within `parsnip`, and now that I see how it is handled, I agree that the class of `c("_try-error", "model_fit")` covers what I was requesting.

In case others have a similar question in the future, an example of it is here:
https://github.com/tidymodels/parsnip/blob/5bc61d8c8f635c715555cb79d63533842adbc650/tests/testthat/test_linear_reg.R#L235-L241
