### ISSUE TITLE
predict "raw" type for SVM in kernlab outputs classes, not raw SVM output.

### ISSUE THREAD

**Issue by reisner** [tidymodels/parsnip#146]
I expected raw SVM output from this, but got predicted classes instead:

```
> predict(model, new_data = prepped_testing_data, type = "raw")
   [1] FALSE FALSE TRUE  FALSE TRUE  TRUE  TRUE  TRUE
Levels: FALSE TRUE
>
...
```

**Comment by topepo** [comment]
It's hard to tell what the underlying issue is without a small reproducible example. 

Looking at `?predict.model_fit`: 

> `type`: A single character value or NULL. Possible values are "numeric", "class", "prob", "conf_int", "pred_int", "quantile", or "raw". When NULL, predict will choose an appropriate value based on the model's mode.
> `opts`: A list of optional arguments to the underlying predict function that will be used when `type = "raw"`. The list should not include options for the model object or the new data being predicted.

So `type = "raw"` will rely on you to use `opts` to get what you want. I don't think that the associated PR is a good idea since it locks in decision values as the result of using `type = "raw"` (e.g. some people may want `type = "votes"`). 

I think that you can get to what you want though: 

``` r
library(tidymodels)
#> ── Attaching packages ───────────────────────────────────────────────────────────────── tidymodels 0.0.2 ──
#> ✔ broom     0.5.1          ✔ purrr     0.3.0     
#> ✔ dials     0.0.2          ✔ recipes   0.1.4     
#> ✔ dplyr     0.7.8          ✔ rsample   0.0.4     
#> ✔ ggplot2   3.1.0          ✔ tibble    2.0.1     
#> ✔ infer     0.4.0          ✔ yardstick 0.0.2     
#> ✔ parsnip   0.0.1.9000
#> ── Conflicts ──────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
#> ✖ purrr::discard() masks scales::discard()
#> ✖ dplyr::filter()  masks stats::filter()
#> ✖ dplyr::lag()     masks stats::lag()
#> ✖ recipes::step()  masks stats::step()

svm_fit <- 
  svm_rbf(mode = "classification", cost = 1) %>% 
  set_engine("kernlab") %>% 
  fit(Class ~ ., data = two_class_dat)

svm_fit
#> parsnip model object
#> 
#> Support Vector Machine object of class "ksvm" 
#> 
#> SV type: C-svc  (classification) 
#>  parameter : cost C = 1 
#> 
#> Gaussian Radial Basis kernel function. 
#>  Hyperparameter : sigma =  2.17302241830935 
#> 
#> Number of Support Vectors : 341 
#> 
#> Objective Function Value : -297.9647 
#> Training error : 0.171934 
#> Probability model included.

predict(
  svm_fit, 
  new_data = two_class_dat %>% slice(1:3), 
  type = "raw", 
  opts = list(type = "decision")
)
#>            [,1]
#> [1,]  0.8590466
#> [2,] -1.2299551
#> [3,] -0.1540822

# Generally, don't do this
library(kernlab)
#> 
#> Attaching package: 'kernlab'
#> The following object is masked from 'package:purrr':
#> 
#>     cross
#> The following object is masked from 'package:ggplot2':
#> 
#>     alpha
#> The following object is masked from 'package:scales':
#> 
#>     alpha
predict(
  svm_fit$fit, 
  two_class_dat %>% slice(1:3) %>% select(-Class) %>% as.matrix(),
  type = "decision"
)
#>            [,1]
#> [1,]  0.8590466
#> [2,] -1.2299551
#> [3,] -0.1540822
```

Created on 2019-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

Note that "raw" also means that the return value is whatever the underlying `predict` methods gives you (a 1-column matrix in this example).

**Comment by reisner** [comment]
@topepo OK Thanks, I guess I was misunderstanding the purpose of the `raw` type. I think that gets me what I want, thanks.

BTW I'm confused by your section marked `# Generally, don't do this`...

**Comment by topepo** [comment]
It's not a good idea to make predictions on the `object$fit` object since it is ignorant to any changes that `parsnip` made to the data (perhaps format). Right now, it is fairly low risk but may not be in the future. The has been the source of a lot of issues with `caret::predict.train`.
