### ISSUE TITLE
`predict()` function does not work with randomForest

### ISSUE THREAD

**Issue by zenggyu** [tidymodels/parsnip#149]
When I use `predict()` to make predictions with a random forest model, the following error occurs:

    Error in UseMethod("predict"): no applicable method for 'predict' applied to an object of class randomForest"

It seems in order for this function to work, the `randomForest` package should be loaded (that is how I work around this issue). Perhaps you have forgotten to include this step?

**Comment by DavisVaughan** [comment]
Can you provide a reproducible example of this? If your are calling predict() on the parsnip object then it's designed so that this should work

**Comment by zenggyu** [comment]
I have encountered this issue more than once, but I didn't pay attention to saving related files and scripts. I try to reproduce it, but everything works fine now (this is awkward). It could be that the issue was caused by some silly mistakes I made. It can be closed for now; I will report again with reproducible examples if I encounter such issue again.

**Comment by topepo** [comment]
I'll close this but please reopen if you see the issue again (and have some example code).
