### ISSUE TITLE
non-right censoring for survival models with recipes

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#15]
`Surv` objects of `type= "counting"`, `"interval1"` or `"interval2"` are not currently supported. 

This would mostly be for defining roles but in the case of **interval censoring** is is difficult. If we let two time variables be used with the `outcome` role, we don't know what their order should be (and the recipe might change the order). If we used roles like `tmin` and `tmax`, then `juice` and helpers won't recognize them as outcomes.

**Comment by juliasilge** [comment]
About two years later, we are talking survival methods again and have this on near-term priorities.
