### ISSUE TITLE
restructure  model information objects

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#167]
The objects in the [`data` files](https://tidymodels.github.io/parsnip/articles/articles/Scratch.html) could have a better format. Two examples:

 * The `fit$func` slot should be able to have different functions for different model modes. For example, if a package has two separate functions for regression and classification, we end up needing a wrapper to include it. 

 * The parameter key tibble should include a reference to where the recommended function for initializing the object should reside. For example, for a random forest model,  the parameter could be initialized by the corresponding `dials` object. 

Paging @DavisVaughan, @alexpghayes, and @stevenpawley for notes on where the pain points are and recommendations for better organization.

**Comment by topepo** [comment]
For the parameter key, I'd suggest having a list column that has a function reference. For example, 

```r
# linear_reg_arg_key
  tibble::tribble(
   ~parsnip, ~lm,  ~glmnet,              ~spark, ~stan,  ~keras,                             ~func,
  "penalty",  NA, "lambda",         "reg_param",    NA, "decay", c(pkg = "dials", fun = "penalty"),
  "mixture",  NA,  "alpha", "elastic_net_param",    NA,      NA, c(pkg = "dials", fun = "mixture")
  )
```

**Comment by topepo** [comment]
Previous thoughts from @DavisVaughan:

Extensibility:

* Think about how someone could extend parsnip to work with their model without having to make a PR to get that model integrated into the core of parsnip.
* Think about maintaining an extensible but internal list of types of objects that are needed to make parsnip work:
  - **parsnip_modes** - A list of data frames, 1 for each model, with the allowed modes of that model. Each data frame has a single column per engine and the rows are mappings to whether or not the engine allows class/reg/unknown. Accessible for external packages through `register_model_mode()` for new models, and `register_engine_mode()` for new engines. (this could replace both the modes vector and the engines vector since that info is redundant)
  - **parsnip_arg_key** - A list of data frames, one for each model. Each data frame has a single column per engine and the rows are the mapping to the core arguments. Accessible by `register_model_args()` for a new model (new data frame) and `register_engine_args()` for a new column of a data frame.
* **parsnip_data** - A list of lists, one for each model, and then per model there is 1 list per engine. This contains the actual data about each model+engine combo. There should be helpers that standardize the fact that each _data list needs `list(libs, fit = list(interface, protect, func, defaults), pred = list(pre, post, func, args), classes = list(pre, post, func, args), ...and so on)`. After using the helpers, you can add your engine to this object with `register_engine_data()` or `register_model_data()` for a new model (this would just create an element in the list for that model).
   - This would also be much easier in terms of standardizing naming because you could access engine data with`parsnip_data$model$engine`
* A helper for standard things to do when creating a new model would be good. Like create a template for what the internals of `nearest_neighbor()` look like since it is so lightweight and most models look similar here. Maybe a `make_model_spec()` object that accepts the model name and the named list of args.
Along the same lines, maybe helpers for printing and updating as well?

**Comment by topepo** [comment]
From @stevenpawley  in #164:

> Relating to the use of additional engines, one possible difficulty with the `parsnip` package is that although a user can add their own model specification+engine, adding an additional engine to an existing model specification appears to require changes to the translate function in the package? Perhaps this part of the package could be further modularized so that the translation of the engine's parameters can be defined outside of the parsnip package by a user-specified function?

**Comment by topepo** [comment]
The code above is a rough prototype. 

The information on the models, modes, and model-specific data are stored in an environment. Users can modify this environment using their code (although the changes are retained in the current R session). If someone had a package that enhances `parsnip` with their own models, they could list it under `Depends` and make the new model objects when their package starts up. 

Here's some example code:

``` r
library(parsnip)

register_new_model("naive_bayes")
register_model_mode("naive_bayes", "classification")
register_model_engine("naive_bayes", "classification", "klaR")
register_model_arg(
  mod = "naive_bayes",
  eng = "klaR",
  val = "Laplace",
  original = "fL",
  func = list(pkg = "dials", fun = "Laplace")
)

show_model_info("naive_bayes")
#> Information for `naive_bayes`
#>  modes: unknown, classification 
#>  engines: klaR (classification)
#>  arguments: 
#> # A tibble: 1 x 3
#>   engine parsnip original
#>   <chr>  <chr>   <chr>   
#> 1 klaR   Laplace fL
```

<sup>Created on 2019-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The methods (and constructors) for new code modules (e.g. model fitting and the various prediction methods) are not implemented yet. I wanted to see how this feels/smells first. 

There is the possibility for disconnects. The user might add an argument using the code above but might forget about it or misspell it in the actual model function etc.

**Comment by topepo** [comment]
One thing that we might consider is that, once model objects are assigned to the model environment, the code in the package isn't referenced. Perhaps we should, at build time, remove the files that contain these components.

**Comment by DavisVaughan** [comment]
I think we need to make sure that users can't override the pre-existing information that parsnip provides. Like, I don't think we would want them to be able to alter the kknn information that we would provide by doing `register_model_arg()`, but I'm not sure.

**Comment by topepo** [comment]
> I think we need to make sure that users can't override the pre-existing information that parsnip provides.

I agree. I'd leave it for someone to make a strong case for being able to modify items. 

Also, I asked Hadley to look at this thread and he was wondering if there is a way to use S3 for this.

**Comment by DavisVaughan** [comment]
I wonder if we can learn from dbplyr. They basically do that using S3 to specify the data base backend type. Then they can query the specific translations using a generic function that dispatches with s3.

We could maybe do a similar thing with a S3 model info object. I'll think about this some more.

**Comment by topepo** [comment]
There should also be a flag somewhere in the model data that denotes if a tuning parameter can be an argument to `multi_predict()`.

**Comment by topepo** [comment]
To do list

 - [ ] resolve all test errors
 - [ ] document new developer functions
 - [ ] decide whether to put new functions in different package
 - [ ] re-write vignette
 - [ ] re-write function to show calls in man files
 - [ ] re-factor code that is used for the [models page](https://tidymodels.github.io/parsnip/articles/articles/Models.html)
