### ISSUE TITLE
[Documentation]  linear_reg penalty parameter 

### ISSUE THREAD

**Issue by alexhallam** [tidymodels/parsnip#173]
The [parsnip documentation](https://tidymodels.github.io/parsnip/reference/linear_reg.html) states

```
penalty: The total amount of regularization in the model. Note that this must be zero for some engines.
```

It would be nice if there were additional documentation mapping this penalty term to the lambda term in glmnet. 

The code makes it look like penalty == lambda, but there could be confusion that penalty == log(lambda), because the authors of glmnet sometimes emphasis log(lambda) in their plots and [documentation](https://web.stanford.edu/~hastie/glmnet/glmnet_alpha.html#spa).

**Comment by juliasilge** [comment]
This is a great point. 🙌  This should be alleviated by [the new tables in the docs](https://github.com/tidymodels/parsnip/pull/272) that map engine specific params (`lambda` in this case) to the parsnip params (`penalty`).
