### ISSUE TITLE
Add causal inference models

### ISSUE THREAD

**Issue by ljanda** [tidymodels/parsnip#177]
It would be so great to have a tidy, syntax-consistent approach to doing things like propensity score matching, difference-in-differences, regression discontinuity, interrupted time series, and instrumental variables. 

Here are some examples of packages that exist on CRAN  for these methods (but vary greatly in syntax, adherence to tidyverse style guide, etc)

Propensity score matching/weighting: [Matching](https://cran.r-project.org/web/packages/Matching/Matching.pdf), [twang](https://cran.r-project.org/web/packages/twang/twang.pdf)

Difference-in-difference: [did](https://cran.rstudio.com/web/packages/did/did.pdf) 

Regression Discontinuity: [rdd](https://cran.r-project.org/web/packages/rdd/index.html)

Interrupted Time Series: many packages for working with time series data but mainly for making forecasts/predictions not much for making inferences using interrupted time series

Instrumental Variables: several packages in the CRAN task view linked below

There is a CRAN task view for [econometrics](https://cran.r-project.org/web/views/Econometrics.html), which includes some of these methods but not all and includes many other methods

**Comment by fkgruber** [comment]
I agree that this would be useful. 
It seems, though, that some of these methods like matching or propensity score matching should probably go to recipes package instead of parsnip?

**Comment by juliasilge** [comment]
We agree with you that this is an important topic but unfortunately it is not in scope for us in the near term (next 3-6 months). I'm going to close this issue for now, not because we don't think this would be valuable but because we are going to be focusing on other areas of work over the next few months.

Thank you for putting thought into this! 🙌
