### ISSUE TITLE
with failed model, return NA values in correct format

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#193]
So return a tibble with the right rows and columns and NA results

**Comment by patr1ckm** [comment]
Which behavior are you thinking of? If the model fails and you call `predict`, you get an empty data frame with the correct column names but filled with NAs? Or if the model fails, `NAs` are filled in the list of the model fit with the fields that should be expected from that model?

**Comment by topepo** [comment]
This is impossible to do. For some models, there is no way to know the dimensions of the output object. For example, with `glmnet`, there is no way to know the number of `lambda` values and this is required for the output object.
