### ISSUE TITLE
objects lose `model_fit` class after reading 

### ISSUE THREAD

**Issue by JosiahParry** [tidymodels/parsnip#212]
Perhaps this has been solved elsewhere but I cannot find the documentation. 

I have saved a model object as an rds file. Once I restart my session and read it in, the object effectively loses its class. It's there nominally, but its entirely lost the print method and the `predict.model_fit()` method doesn't work either.

I've tried this with and without `parsnip` loaded in the environment. Neither work. 

``` r
library(tidymodels)

iris_split <- initial_split(iris)

iris_train <- training(iris_split)
iris_test <- testing(iris_split)

iris_mod <- rand_forest(mode = "classification") %>%
  set_engine("ranger") %>%
  fit(Species ~ ., data = iris_train)

readr::write_rds(iris_mod, glue::glue("{here::here()}/iris_model.rds"))

# restart r-session
.rs.restartR()

# read model back in
iris_mod2 <- readr::read_rds(glue::glue("{here::here()}/iris_model.rds"))

# classes are shown
class(iris_mod2)

# print it and classes are effectively lost
iris_mod2

# try predicting on model_fit class
parsnip::predict.model_fit(iris_mod2, iris[1,])
#> #> Error in UseMethod("predict") : 
#>  no applicable method for 'predict' applied to an object of class "ranger"

```

<sup>Created on 2019-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by topepo** [comment]
```
# print it and classes are effectively lost
iris_mod2
```

You have to load `parsnip` (and `ranger`) to get the print method(s) to work right

```
# try predicting on model_fit class
parsnip::predict.model_fit(iris_mod2, iris[1,])
#> #> Error in UseMethod("predict") : 
#>  no applicable method for 'predict' applied to an object of class "ranger"
```

`parsnip` loads the namespace of the required packages when the model is fit. You'll need to load them to do prediction (e.g. `library(ranger)`). It's the same issue; `predict.model_fit` and `predict.ranger` are needed to make S3 dispatch work.

**Comment by JosiahParry** [comment]
Beautiful. Thanks, Max!
