### ISSUE TITLE
Custom Metrics in Parsnip

### ISSUE THREAD

**Issue by ngupta23** [tidymodels/parsnip#218]
Hello, Is it possible to provide custom metrics for model training and evaluation using parsnip as we can do in caret?

Thanks!

**Comment by topepo** [comment]
Yes but you would do that using the [`yardstick` package](https://tidymodels.github.io/yardstick/articles/custom-metrics.html). Is there something that should be in there or is your metric specific to your problem?

**Comment by ngupta23** [comment]
Thanks for the quick reply. It is a custom metric (not standard). I see what you are saying,.. I will try it out.
