### ISSUE TITLE
Error in UseMethod("predict") :    no applicable method for 'predict' applied to an object of class "c('elnet', 'glmnet')"

### ISSUE THREAD

**Issue by konradsemsch** [tidymodels/parsnip#249]
I'm attaching a zipped rds object that contains all the information to make this example reproducible. I'm essentially trying to make a prediction on a fitted workflow, but that gives me the following error. Could you please take a look?

```
library(recipes)
library(parsnip)

df_input <- diamonds[1, ]
pipeline <- readRDS("/pipeline.rds")

predict(pipeline$workflow, df_input)
```

Giving the following error:
```
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('elnet', 'glmnet')"
```

[pipeline.rds.zip](https://github.com/tidymodels/parsnip/files/3977896/pipeline.rds.zip)

**Comment by EmilHvitfeldt** [comment]
Since you have a **workflows** object with a fitted **glmnet** you need to load both **workflows** and **glmnet** to predict so it knows what methods to dispatch.

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(parsnip)
library(workflows)
library(glmnet)
#> Loading required package: Matrix
#> Loaded glmnet 3.0-2
library(zeallot)
library(ggplot2)

df_input <- diamonds[1, ]
pipeline <- readRDS("~/Downloads/pipeline")
#> Warning: namespace 'rmlpackage' is not available and has been replaced
#> by .GlobalEnv when processing object ''

predict(pipeline$workflow, df_input)
#> # A tibble: 1 x 1
#>   .pred
#>   <dbl>
#> 1  4.91
```

<sup>Created on 2019-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by konradsemsch** [comment]
Thanks, that helped!

**Comment by jg43b** [comment]
Why is it that it's not necessary to load `glmnet` to actually train the underlying model, but it _is_ necessary to load it to make predictions? For instance in [this model notebook](https://www.tidymodels.org/start/resampling/), `ranger` is never attached to the global namespace.

**Comment by topepo** [comment]
We do load `glmnet` to fit the model but you might not see that since it is not _attached_. [This SO link](https://stackoverflow.com/a/56538266/1078601) does a good job at explaining the difference. 

We don't attach so that there are not conflicts in function names. 

The _currrent_ reason that you need to load a package is because we are not doing the same thing for predictions (but #308 will fix that). 

In the future, it would be better to open a new issue rather than append to a closed one.

**Comment by jg43b** [comment]
Great, thanks for the explanation! I'll be sure to open a new issue or post in the RStudio community as appropriate in the future.
