### ISSUE TITLE
robust standard erros

### ISSUE THREAD

**Issue by economer** [tidymodels/parsnip#258]
Hi, 
It might be a naive question, however, I was wondering if there is an option to get the robust standard errors in parsnip.

**Comment by topepo** [comment]
Any ones in particular?  Some are done after the model fit (so that they would be independent of `parsnip`).

**Comment by economer** [comment]
Hi Max, 
Thanks for the response. I was mainly looking for the linear regression model. I know I can use the sandwich package. However, it would be perfect, if we can report the robust standard errors in the tidymodels environment. 


Seyed.

**Comment by topepo** [comment]
I think that it would be a good idea to write `bread()`, `meat()`, `vcov()`, and `estfun()` methods for `parsnip` objects that just call those functions for the fit object. This would allow the full functionality of `sandwich` for _+any_ applicable `parsnip` objects.
