### ISSUE TITLE
Documentation request: Adding which models support missing values and categoricals to the Model List page

### ISSUE THREAD

**Issue by kdpsingh** [tidymodels/parsnip#261]
The documentation page for the Model List (https://tidymodels.github.io/parsnip/articles/articles/Models.html) includes very helpful features about each model.

Two other useful things to to know would be whether:
- the model natively supports missing values
- the model supports categorical (factor) variables

For instance, xgboost supports missing values but not categoricals whereas ranger supports categoricals but not missing values. This impacts where you need to do a step_impute() in your recipe which is why would be great to include right up front in the docs if possible.

The mlr docs have this info so could even be borrowed from there: https://mlr.mlr-org.com/articles/tutorial/integrated_learners.html

Thanks for the consideration,

Karandeep

**Comment by EmilHvitfeldt** [comment]
As a general note: it is advisable to deal with missing and categorical values before turning the data over to the model. This way you have greater control over what happens and you can switch model/framework without having to change your preprocessing steps.

**Comment by kdpsingh** [comment]
I generally agree with this but there are a number of models (particularly tree-based models) which have very reasonable approaches to handling missing values. In these cases, it would be useful to users to know that certain engines having missing values support whereas others do not.

**Comment by juliasilge** [comment]
In our recently announced book [_Tidy Modeling with R_](https://www.tmwr.org/), we have a [table in the appendix on recommend preprocessing per model](https://www.tmwr.org/pre-proc-table.html). That's where we plan to gather and organize information of this type for models available in tidymodels. It's already in good shape and we can add to or edit any details there. 🚀
