### ISSUE TITLE
make engines tab-completable functions

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#278]
`set_engine(eng_lm())`, `set_engine(eng_stan_lm())` or similar

or maybe `eng_stan_lm()` or `eng_lm_stan()` or `eng_lm()`, `eng_lmer_stan_glmer()`

**Comment by simonpcouch** [comment]
A couple thoughts:

* The user would still need to type `eng` to get relevant suggestions to tab through, which is as much as we need to type already for some engines.
* Most of the the tab-completed suggestions would not be well-paired with the model type they're being matched to.
* This feels like it would be better served by improvements to tab-completion of arguments in the IDE generally.

As this hasn't come to the top of our to-do list in the last couple years, I'm going to go ahead and close.
