### ISSUE TITLE
Xgboost Sparse xgb.DMatrix

### ISSUE THREAD

**Issue by ThomasWolf0701** [tidymodels/parsnip#284]
Parsnip seems to transform a data frame into a xgb.DMatrix when calling xgboost.
Does this take sparseness into consideration. Like is the xgb.DMatrix  automatically constructed as sparse or is there any way to define this. Would be really helpful.

**Comment by topepo** [comment]
`parsnip::xgb_train()` uses

```r
x <- xgboost::xgb.DMatrix(x, label = y, missing = NA)
```

so `x` is a sparse representation.
