### ISSUE TITLE
R crash fitting the model

### ISSUE THREAD

**Issue by cgoo4** [tidymodels/parsnip#288]
Hi - The following code example causes my R session to abort in RStudio.  If I change to `rand_forest` and `ranger`, the code works fine.  In the R Gui, it also aborts producing the attached problem report.

[R Crash.pdf](https://github.com/tidymodels/parsnip/files/4532973/R.Crash.pdf)
[Session Info.pdf](https://github.com/tidymodels/parsnip/files/4532989/Session.Info.pdf)

```r
library(tidymodels)

mt_recipe <- 
  mtcars %>% 
  recipe() %>%
  update_role(mpg, new_role = "outcome") %>%
  update_role(-has_role("outcome"), new_role = "predictor")

mt_model <-
  boost_tree(
    mtry = 6,
    trees = 10,
    min_n = 3
  ) %>%
  set_mode("regression") %>%
  set_engine("xgboost")

mt_wflow <- workflow() %>% 
  add_recipe(mt_recipe) %>% 
  add_model(mt_model)

mt_fit <- mt_wflow %>% 
  fit(mtcars)
```

**Comment by stevenpawley** [comment]
I think this is an XGBoost issue on MacOS, and not parsnip. I also have problems with XGBoost crashing R on MacOS due to gcc and libomp, unless XGBoost is compiled without libomp but then its only single-threaded. It might relate to the issues here https://github.com/dmlc/xgboost/issues/4477

**Comment by cgoo4** [comment]
Thanks Steven.  It had been working for me up until March 20th.  Yesterday I tried reverting to `xgboost `1.0.0.1, but the fit still aborted.  I just now tried going further back to version 0.90.0.1, and this works.

**Comment by stevenpawley** [comment]
I fixed my XGBoost issues by installing gcc@7 via homebrew and then compiling from source with:

```
CC=gcc-7 CXX=g++-7 cmake .. -DR_LIB=ON
sudo make -j install
```
Using gcc-9 which is homebrew's default caused XGBoost to crash.

**Comment by hcho3** [comment]
The script ran successfully on my Macbook Pro (2019, Catalina). How did you install R? Did you use Homebrew or use *.dmg file from the R website?

**Comment by cgoo4** [comment]
I use [updateR](https://github.com/AndreaCirilloAC/updateR) to install the latest versions.

**Comment by hcho3** [comment]
@cgoo4 updateR requires an existing R installation. Do you recall how you installed R for the first time?

**Comment by cgoo4** [comment]
I do see some Homebrew files on my Mac drive, but also vaguely recall deciding against using it.  Is there a way to tell how it was originally installed?  Or worth anyway trying a fresh install from the R site?

**Comment by hcho3** [comment]
I'm trying to decide if there's significant difference between Homebrew R vs. the R pkg file provided by the R site.

**Comment by hcho3** [comment]
One theory: Maybe another OpenMP runtime (like libgomp) is already in use and clashing with libomp used by XGBoost.

If this is the case, we may want to keep XGBoost single-thread by default. Users who want multi-threading would be asked to [specify OpenMP flags in `~/.R/Makevars`](https://github.com/dmlc/xgboost/issues/1136#issuecomment-213654815). This is a shame, because I badly wanted to give multithreading out of the box to all Mac users.

**Comment by topepo** [comment]
I agree with the comments above (and was not able to reproduce). If it makes you feel any better, I struggle with these install issues on every new computer that I have. 

Note that with R 4.0, openmp is turned off by default. I think that this means that CRAN binaries would not have this feature for `xgboost` and you would have to compile it to get there.

**Comment by cgoo4** [comment]
After updating to R4, the code runs successfully with xgboost 1.0.0.2.

**Comment by hcho3** [comment]
> Note that with R 4.0, openmp is turned off by default. 

Is this true? I did not see this in the release note. Is there a link I can look at?
