### ISSUE TITLE
"&gt;" instead of ">" in manual pages

### ISSUE THREAD

**Issue by Deleetdk** [tidymodels/parsnip#309]
## The problem

Some or all of the manual pages have `&gt;` instead of `>`. Seems like a HTML bug somewhere.

![Screenshot from 2020-05-16 11-58-40](https://user-images.githubusercontent.com/6759913/82116814-9a58e280-976c-11ea-8128-f38917227e42.png)

## Reproducible example

- https://parsnip.tidymodels.org/reference/multinom_reg.html
- https://parsnip.tidymodels.org/reference/linear_reg.html
- https://parsnip.tidymodels.org/reference/rand_forest.html
(Many others)

I tested in Firefox and Chromium, same result.

**Comment by juliasilge** [comment]
Related to r-lib/pkgdown#1311 which has been closed/fixed.
