### ISSUE TITLE
Variable Importance Function/method

### ISSUE THREAD

**Issue by kylegilde** [tidymodels/parsnip#311]
Is there a variable importance function for the model_fit object?

**Comment by topepo** [comment]
We rely on the `vip` package for that. They have `vip:::vip.model_fit()` so it should work well. There are examples of usage [here](https://www.tidymodels.org/start/tuning/) and [here](https://www.tidymodels.org/start/case-study/).

**Comment by kylegilde** [comment]
good to know, thanks!

**Comment by vasileioubill95** [comment]
Hello,
Does the tidymodels support variable importance function for support vector machine (svm) from kernel (either radial basis function (svm_rbf) or polynomial (svm_poly).
Thank you!

**Comment by juliasilge** [comment]
We typically use the [vip](https://koalaverse.github.io/vip/) package to calculate variable importance. This package supports both model-based variable importance (check out [what is available here](https://koalaverse.github.io/vip/reference/vi_model.html)) and model-agnostic procedures for computing feature importance. [Check out their docs](https://koalaverse.github.io/vip/).
