### ISSUE TITLE
non-standard data arguments

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#315]
In some cases, a model function that `parsnip` is calling has non-standard argument names for the data-oriented components. 

For example, a function `foo()` that only has the x/y interface might have a signature like `foo(X, Y)` instead of the standard `foo(x, y)`. 

Some real examples: 

 * `sparklyr` models use `x` as the `data` slot (and put it in the first position)
 * `kernlab::ksvm(x, data)` where `x` is a formula. 
 * `MASS::lda(x, grouping)`

**Comment by juliasilge** [comment]
This change is implemented in #316. 🚀
