### ISSUE TITLE
linear svm models

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/parsnip#336]
This issues https://github.com/tidymodels/parsnip/issues/35 talks about linear SVM models but we only have `svm_poly()` and `svm_rbf()`.

I can see how `svm_linear()` would be a special case of `svm_poly()` but is there still room for `svm_linear()` for models that doesn't do polynomials?

**Comment by juliasilge** [comment]
Still TODO here is to add kernlab as an engine for `svm_linear()`
