### ISSUE TITLE
Trying to add maxnet to logistic model but run into problems (reprex included)

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [tidymodels/parsnip#348]
# The problem:

Hello everyone, I am extremely interested in learning how to work with the `parsnip` package, especially adding my own models. I am trying to work with the maxnet package, this is the model I am trying to emulate with Parsnip:

    # load the package
    library(maxnet)

    # get the example dataset
    data(bradypus)

    # Subset presences
    p <- bradypus$presence

    # Get climatic variables
    data <- bradypus[, -1]

    # model the data
    mod <- maxnet(p, data, regmult = 1, classes = "lq")

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

One of the challenges of this model is that it does not use a traditional formula approach but uses a vector for the response variable and a matrix as the predictors, the full reprex is at the end including the session info

# What I tried

## Setting the new mode and dependencies (should be fine)

I tried to reproduce this simple model using [this parsnip vignette](https://www.tidymodels.org/learn/develop/models/) on how to add a model. But since this is a logistic model I tried to add it to that method instead of creating a new one.

so I started by adding the new mode to the logistic_regression model and the dependencies, I think all of this is fine:

    library(tidymodels)
    #> ── Attaching packages ──────────────────── tidymodels 0.1.1 ──
    #> ✓ broom     0.7.0      ✓ recipes   0.1.13
    #> ✓ dials     0.0.8      ✓ rsample   0.0.7 
    #> ✓ dplyr     1.0.0      ✓ tibble    3.0.3 
    #> ✓ ggplot2   3.3.2      ✓ tidyr     1.1.0 
    #> ✓ infer     0.5.3      ✓ tune      0.1.1 
    #> ✓ modeldata 0.0.2      ✓ workflows 0.1.2 
    #> ✓ parsnip   0.1.2      ✓ yardstick 0.0.7 
    #> ✓ purrr     0.3.4
    #> ── Conflicts ─────────────────────── tidymodels_conflicts() ──
    #> x purrr::discard() masks scales::discard()
    #> x dplyr::filter()  masks stats::filter()
    #> x dplyr::lag()     masks stats::lag()
    #> x recipes::step()  masks stats::step()

    ## Set new mode
    set_model_mode(model = "logistic_reg", mode = "classification")

    # Establish de model engines
    set_model_engine(
      "logistic_reg",
      mode = "classification",
      eng = "maxnet"
    )
    # Set package dependencies
    set_dependency("logistic_reg", eng = "maxnet", pkg = "maxnet")

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Adding the arguments (might be wrong)

Here is where I start having doubts, especially how to add the p and data arguments:

```
# set arguments

set_model_arg(
  model = "logistic_reg",
  eng = "maxnet",
  parsnip = "formula",
  original = "f",
  func = list(pkg = "maxnet", fun = "maxnet"),
  has_submodel = FALSE
)

set_model_arg(
  model = "logistic_reg",
  eng = "maxnet",
  parsnip = "penalty",
  original = "regmult",
  func = list(pkg = "maxnet", fun = "maxnet"),
  has_submodel = FALSE
)

set_model_arg(
  model = "logistic_reg",
  eng = "maxnet",
  parsnip = "presences",
  original = "p",
  func = list(pkg = "maxnet", fun = "maxnet"),
  has_submodel = FALSE
)

set_model_arg(
  model = "logistic_reg",
  eng = "maxnet",
  parsnip = "classes",
  original = "classes",
  func = list(pkg = "maxnet", fun = "maxnet"),
  has_submodel = FALSE
)

set_model_arg(
  model = "logistic_reg",
  eng = "maxnet",
  parsnip = "data",
  original = "data",
  func = list(pkg = "maxnet", fun = "maxnet"),
  has_submodel = FALSE
)
```

## Setting the fit

Here I have more doubts of having made the best choice I wanted to put a default in formula, but the default is defined on other arguments, so I couldn't do it:

```

## Set the model fit

set_fit(
  model = "logistic_reg",
  eng = "maxnet",
  mode = "classification",
  value = list(
  interface = "data.frame",
  protect = c("data.frame", "data"),
  func = c(pkg = "maxnet", fun = "maxnet"),
  defaults = list()
  )
)

class_info <- 
  list(
    pre = NULL,
    post = NULL,
    func = c(fun = "predict"),
    args =
      list(
        object = quote(object$fit),
        newdata = quote(new_data),
        type = "cloglog"
      )
  )

```

## Set the model predictions (This should be fine I think)

```
set_pred(
  model = "logistic_reg",
  eng = "maxnet",
  mode = "classification",
  type = "raw",
  value = class_info
)
```

## And finally running the model

```

## Specify the model

sdm_spec <- logistic_reg(penalty = 1) %>% 
  set_engine("maxnet")

# get the example dataset
data(bradypus)

# Subset presences
p <- bradypus$presence

# Get climatic variables
data <- bradypus[,-1]

## Fit the model

sdm_fit <- sdm_spec %>%
  fit(p = p, data = bradypus, engine = "maxet", classes = "lq", formula = maxnet::maxnet.formula(p = p, data = data, classes = "lq))

```

The error I get is `Error: These argument(s) cannot be used to create the data: `p`, `engine`, `classes`. Possible arguments are: `subset`, `weights`, `contrasts`, `offset`` so I am guessing I set the data argument wrong.

Any help would be  appreciated

# here is the whole reprex (Including session info):

    library(tidymodels)
    #> ── Attaching packages ──────────────────── tidymodels 0.1.1 ──
    #> ✓ broom     0.7.0      ✓ recipes   0.1.13
    #> ✓ dials     0.0.8      ✓ rsample   0.0.7 
    #> ✓ dplyr     1.0.0      ✓ tibble    3.0.3 
    #> ✓ ggplot2   3.3.2      ✓ tidyr     1.1.0 
    #> ✓ infer     0.5.3      ✓ tune      0.1.1 
    #> ✓ modeldata 0.0.2      ✓ workflows 0.1.2 
    #> ✓ parsnip   0.1.2      ✓ yardstick 0.0.7 
    #> ✓ purrr     0.3.4
    #> ── Conflicts ─────────────────────── tidymodels_conflicts() ──
    #> x purrr::discard() masks scales::discard()
    #> x dplyr::filter()  masks stats::filter()
    #> x dplyr::lag()     masks stats::lag()
    #> x recipes::step()  masks stats::step()
    library(maxnet)

    ## Set new mode

    set_model_mode(model = "logistic_reg", mode = "classification")

    # Establish the model engines

    set_model_engine(
      "logistic_reg",
      mode = "classification",
      eng = "maxnet"
    )
    # Set package dependencies

    set_dependency("logistic_reg", eng = "maxnet", pkg = "maxnet")

    # set arguments

    set_model_arg(
      model = "logistic_reg",
      eng = "maxnet",
      parsnip = "formula",
      original = "f",
      func = list(pkg = "maxnet", fun = "maxnet"),
      has_submodel = FALSE
    )

    set_model_arg(
      model = "logistic_reg",
      eng = "maxnet",
      parsnip = "penalty",
      original = "regmult",
      func = list(pkg = "maxnet", fun = "maxnet"),
      has_submodel = FALSE
    )

    set_model_arg(
      model = "logistic_reg",
      eng = "maxnet",
      parsnip = "presences",
      original = "p",
      func = list(pkg = "maxnet", fun = "maxnet"),
      has_submodel = FALSE
    )

    set_model_arg(
      model = "logistic_reg",
      eng = "maxnet",
      parsnip = "classes",
      original = "classes",
      func = list(pkg = "maxnet", fun = "maxnet"),
      has_submodel = FALSE
    )

    set_model_arg(
      model = "logistic_reg",
      eng = "maxnet",
      parsnip = "data",
      original = "data",
      func = list(pkg = "maxnet", fun = "maxnet"),
      has_submodel = FALSE
    )

    ## Set the model fit

    set_fit(
      model = "logistic_reg",
      eng = "maxnet",
      mode = "classification",
      value = list(
        interface = "data.frame",
        protect = c("data.frame", "data"),
        func = c(pkg = "maxnet", fun = "maxnet"),
        defaults = list()
      )
    )

    class_info <-
      list(
        pre = NULL,
        post = NULL,
        func = c(fun = "predict"),
        args =
          list(
            object = quote(object$fit),
            newdata = quote(new_data),
            type = "cloglog"
          )
      )

    ## Set the model predictions

    set_pred(
      model = "logistic_reg",
      eng = "maxnet",
      mode = "classification",
      type = "raw",
      value = class_info
    )

    ## Specify the model

    sdm_spec <- logistic_reg(penalty = 1) %>%
      set_engine("maxnet")

    # get the example dataset
    data(bradypus)

    # Subset presences
    p <- bradypus$presence

    # Get climatic variables
    data <- bradypus[, -1]

    ## Fit the model

    sdm_fit <- sdm_spec %>%
      fit(p = p, data = bradypus, engine = "maxet", classes = "lq", formula = maxnet::maxnet.formula(p = p, data = data, classes = "lq"))
    #> Error: These argument(s) cannot be used to create the data: `p`, `engine`, `classes`. Possible arguments are: `subset`, `weights`, `contrasts`, `offset`

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 3.6.3 (2020-02-29)
    #>  os       Ubuntu 18.04.4 LTS          
    #>  system   x86_64, linux-gnu           
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/Santiago            
    #>  date     2020-07-23                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version    date       lib source                          
    #>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.2)                  
    #>  backports     1.1.8      2020-06-17 [1] CRAN (R 3.6.3)                  
    #>  broom       * 0.7.0      2020-07-09 [1] CRAN (R 3.6.3)                  
    #>  callr         3.4.3      2020-03-28 [1] CRAN (R 3.6.3)                  
    #>  class         7.3-17     2020-04-26 [4] CRAN (R 3.6.3)                  
    #>  cli           2.0.2      2020-02-28 [1] CRAN (R 3.6.3)                  
    #>  codetools     0.2-16     2018-12-24 [4] CRAN (R 3.6.3)                  
    #>  colorspace    1.4-1      2019-03-18 [1] CRAN (R 3.6.2)                  
    #>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.2)                  
    #>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.2)                  
    #>  devtools      2.3.1      2020-07-21 [1] CRAN (R 3.6.3)                  
    #>  dials       * 0.0.8      2020-07-08 [1] CRAN (R 3.6.3)                  
    #>  DiceDesign    1.8-1      2019-07-31 [1] CRAN (R 3.6.3)                  
    #>  digest        0.6.25     2020-02-23 [1] CRAN (R 3.6.3)                  
    #>  dplyr       * 1.0.0      2020-05-29 [1] CRAN (R 3.6.3)                  
    #>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 3.6.3)                  
    #>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.2)                  
    #>  fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.2)                  
    #>  foreach       1.5.0      2020-03-30 [1] CRAN (R 3.6.3)                  
    #>  fs            1.4.2      2020-06-30 [1] CRAN (R 3.6.3)                  
    #>  furrr         0.1.0      2018-05-16 [1] CRAN (R 3.6.3)                  
    #>  future        1.18.0     2020-07-09 [1] CRAN (R 3.6.3)                  
    #>  generics      0.0.2      2018-11-29 [1] CRAN (R 3.6.2)                  
    #>  ggplot2     * 3.3.2      2020-06-19 [1] CRAN (R 3.6.3)                  
    #>  globals       0.12.5     2019-12-07 [1] CRAN (R 3.6.3)                  
    #>  glue          1.4.1      2020-05-13 [1] CRAN (R 3.6.3)                  
    #>  gower         0.2.1      2019-05-14 [1] CRAN (R 3.6.2)                  
    #>  GPfit         1.0-8      2019-02-08 [1] CRAN (R 3.6.3)                  
    #>  gtable        0.3.0      2019-03-25 [1] CRAN (R 3.6.2)                  
    #>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.2)                  
    #>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 3.6.3)                  
    #>  infer       * 0.5.3      2020-07-14 [1] CRAN (R 3.6.3)                  
    #>  ipred         0.9-9      2019-04-28 [1] CRAN (R 3.6.2)                  
    #>  iterators     1.0.12     2019-07-26 [1] CRAN (R 3.6.2)                  
    #>  knitr         1.29       2020-06-23 [1] CRAN (R 3.6.3)                  
    #>  lattice       0.20-41    2020-04-02 [4] CRAN (R 3.6.3)                  
    #>  lava          1.6.7      2020-03-05 [1] CRAN (R 3.6.3)                  
    #>  lhs           1.0.2      2020-04-13 [1] CRAN (R 3.6.3)                  
    #>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 3.6.3)                  
    #>  listenv       0.8.0      2019-12-05 [1] CRAN (R 3.6.3)                  
    #>  lubridate     1.7.9      2020-06-08 [1] CRAN (R 3.6.3)                  
    #>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.2)                  
    #>  MASS          7.3-51.6   2020-04-26 [4] CRAN (R 3.6.3)                  
    #>  Matrix        1.2-18     2019-11-27 [4] CRAN (R 3.6.1)                  
    #>  maxnet      * 0.1.2      2020-06-03 [1] Github (mrmaxent/maxnet@08310a7)
    #>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.2)                  
    #>  modeldata   * 0.0.2      2020-06-22 [1] CRAN (R 3.6.3)                  
    #>  munsell       0.5.0      2018-06-12 [1] CRAN (R 3.6.2)                  
    #>  nnet          7.3-14     2020-04-26 [4] CRAN (R 3.6.3)                  
    #>  parsnip     * 0.1.2      2020-07-03 [1] CRAN (R 3.6.3)                  
    #>  pillar        1.4.6      2020-07-10 [1] CRAN (R 3.6.3)                  
    #>  pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 3.6.3)                  
    #>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.2)                  
    #>  pkgload       1.1.0      2020-05-29 [1] CRAN (R 3.6.3)                  
    #>  plyr          1.8.6      2020-03-03 [1] CRAN (R 3.6.3)                  
    #>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.2)                  
    #>  pROC          1.16.2     2020-03-19 [1] CRAN (R 3.6.3)                  
    #>  processx      3.4.3      2020-07-05 [1] CRAN (R 3.6.3)                  
    #>  prodlim       2019.11.13 2019-11-17 [1] CRAN (R 3.6.2)                  
    #>  ps            1.3.3      2020-05-08 [1] CRAN (R 3.6.3)                  
    #>  purrr       * 0.3.4      2020-04-17 [1] CRAN (R 3.6.3)                  
    #>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.2)                  
    #>  Rcpp          1.0.5      2020-07-06 [1] CRAN (R 3.6.3)                  
    #>  recipes     * 0.1.13     2020-06-23 [1] CRAN (R 3.6.3)                  
    #>  remotes       2.2.0      2020-07-21 [1] CRAN (R 3.6.3)                  
    #>  rlang         0.4.7      2020-07-09 [1] CRAN (R 3.6.3)                  
    #>  rmarkdown     2.3        2020-06-18 [1] CRAN (R 3.6.3)                  
    #>  rpart         4.1-15     2019-04-12 [4] CRAN (R 3.6.1)                  
    #>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.2)                  
    #>  rsample     * 0.0.7      2020-06-04 [1] CRAN (R 3.6.3)                  
    #>  rstudioapi    0.11       2020-02-07 [1] CRAN (R 3.6.3)                  
    #>  scales      * 1.1.1      2020-05-11 [1] CRAN (R 3.6.3)                  
    #>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.2)                  
    #>  stringi       1.4.6      2020-02-17 [1] CRAN (R 3.6.3)                  
    #>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.2)                  
    #>  survival      3.1-12     2020-04-10 [4] CRAN (R 3.6.3)                  
    #>  testthat      2.3.2      2020-03-02 [1] CRAN (R 3.6.3)                  
    #>  tibble      * 3.0.3      2020-07-10 [1] CRAN (R 3.6.3)                  
    #>  tidymodels  * 0.1.1      2020-07-14 [1] CRAN (R 3.6.3)                  
    #>  tidyr       * 1.1.0      2020-05-20 [1] CRAN (R 3.6.3)                  
    #>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 3.6.3)                  
    #>  timeDate      3043.102   2018-02-21 [1] CRAN (R 3.6.2)                  
    #>  tune        * 0.1.1      2020-07-08 [1] CRAN (R 3.6.3)                  
    #>  usethis       1.6.1      2020-04-29 [1] CRAN (R 3.6.3)                  
    #>  vctrs         0.3.2      2020-07-15 [1] CRAN (R 3.6.3)                  
    #>  withr         2.2.0      2020-04-20 [1] CRAN (R 3.6.3)                  
    #>  workflows   * 0.1.2      2020-07-07 [1] CRAN (R 3.6.3)                  
    #>  xfun          0.15       2020-06-21 [1] CRAN (R 3.6.3)                  
    #>  yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.2)                  
    #>  yardstick   * 0.0.7      2020-07-13 [1] CRAN (R 3.6.3)                  
    #> 
    #> [1] /home/derek/R/x86_64-pc-linux-gnu-library/3.6
    #> [2] /usr/local/lib/R/site-library
    #> [3] /usr/lib/R/site-library
    #> [4] /usr/lib/R/library

**Comment by juliasilge** [comment]
This is going to be a real challenge, because this package is a bit quirky in terms of its interface. I just spent some time looking at how to add this.

For starters, it looks like maxnet _requires_ an outcome that is a vector of 1s and 0s, and will not accept factors or logicals. This is a problem for the parsnip infrastructure for `logistic_reg()`, which built-in error checking for numeric outcomes. You can't get away with forcing the outcome to be a factor, either, because maxnet takes the outcome and predictor inputs and creates a formula with them, which errors if the outcome is a factor. This modeling package is pretty far outside the norms.

These are just some initial thoughts. I don't think this will help much in the long run, but here is a start on how to build a parsnip interface for this kind of model that uses an `x`/`y` user-facing function:

``` r
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.1 ──
#> ✓ broom     0.7.0      ✓ recipes   0.1.13
#> ✓ dials     0.0.8      ✓ rsample   0.0.7 
#> ✓ dplyr     1.0.0      ✓ tibble    3.0.3 
#> ✓ ggplot2   3.3.2      ✓ tidyr     1.1.0 
#> ✓ infer     0.5.3      ✓ tune      0.1.1 
#> ✓ modeldata 0.0.2      ✓ workflows 0.1.2 
#> ✓ parsnip   0.1.2      ✓ yardstick 0.0.7 
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()

# Set model engine
set_model_engine(
  "logistic_reg",
  mode = "classification",
  eng = "maxnet"
)

# Set package dependencies
set_dependency("logistic_reg", eng = "maxnet", pkg = "maxnet")

set_fit(
  model = "logistic_reg",
  eng = "maxnet",
  mode = "classification",
  value = list(
    interface = "matrix",
    data = c(x = "data", y = "p"),
    protect = c("x", "y"),
    func = c(pkg = "maxnet", fun = "maxnet")
  )
)

set_encoding(
  model = "logistic_reg",
  eng = "maxnet",
  mode = "classification",
  options = list(
    predictor_indicators = "traditional",
    compute_intercept = TRUE,
    remove_intercept = TRUE
  )
)

set_model_arg(
  model = "logistic_reg",
  eng = "maxnet",
  parsnip = "penalty",
  original = "regmult",
  func = list(pkg = "dials", fun = "penalty"),
  has_submodel = FALSE
)

show_model_info("logistic_reg")
#> Information for `logistic_reg`
#>  modes: unknown, classification 
#> 
#>  engines: 
#>    classification: glm, glmnet, keras, maxnet, spark, stan
#> 
#>  arguments: 
#>    glmnet: 
#>       penalty --> lambda
#>       mixture --> alpha
#>    spark:  
#>       penalty --> reg_param
#>       mixture --> elastic_net_param
#>    keras:  
#>       penalty --> penalty
#>    maxnet: 
#>       penalty --> regmult
#> 
#>  fit modules:
#>    engine           mode
#>       glm classification
#>    glmnet classification
#>     spark classification
#>     keras classification
#>      stan classification
#>    maxnet classification
#> 
#>  prediction modules:
#>              mode engine                              methods
#>    classification    glm           class, conf_int, prob, raw
#>    classification glmnet                     class, prob, raw
#>    classification  keras                          class, prob
#>    classification  spark                          class, prob
#>    classification   stan class, conf_int, pred_int, prob, raw

## Specify the model
sdm_spec <- logistic_reg(penalty = 1) %>% 
  set_engine("maxnet", classes = "lq")

sdm_spec
#> Logistic Regression Model Specification (classification)
#> 
#> Main Arguments:
#>   penalty = 1
#> 
#> Engine-Specific Arguments:
#>   classes = lq
#> 
#> Computational engine: maxnet
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by derek-corcoran-barrios** [comment]
> )

Thank you @juliasilge , I guess another option would be to go ahead and instead of adding it to a logistic regression I could use a `set_new_model` approach? the only question I have is were would I state that the response variable (p in this case) is numeric?

Thank you for nudging me in the right direction!!!

**Comment by juliasilge** [comment]
I looked at this a little more; I think the key is to create a little wrapper function to handle some of the data conversions back and forth, both for the outcomes and predictors. I believe you _do_ want to keep this a classification model of some kind (and `logistic_reg()` is a good option) because you need that for the metrics.

``` r
library(tidymodels)
#> ── Attaching packages ──────────────────────────────────────────────────── tidymodels 0.1.1 ──
#> ✓ broom     0.7.0          ✓ recipes   0.1.13    
#> ✓ dials     0.0.8          ✓ rsample   0.0.7     
#> ✓ dplyr     1.0.0          ✓ tibble    3.0.3     
#> ✓ ggplot2   3.3.2          ✓ tidyr     1.1.0     
#> ✓ infer     0.5.3          ✓ tune      0.1.1     
#> ✓ modeldata 0.0.2          ✓ workflows 0.1.2     
#> ✓ parsnip   0.1.2.9000     ✓ yardstick 0.0.7     
#> ✓ purrr     0.3.4
#> ── Conflicts ─────────────────────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()

data(bradypus, package = "maxnet")

mod_orig <- maxnet::maxnet(bradypus$presence, bradypus[, -1], regmult = 1, classes = "lq")


set_model_engine("logistic_reg", "classification", eng = "maxnet")
set_dependency("logistic_reg", eng = "maxnet", pkg = "maxnet")

## notice the fit module uses a wrapper function, not the function from maxnet
set_fit(
  model = "logistic_reg",
  eng = "maxnet",
  mode = "classification",
  value = list(
    interface = "matrix",
    protect = c("x", "y"),
    func = c(fun = "maxnet_train"),
    defaults = list(classes = "default")
  )
)

set_encoding(
  model = "logistic_reg",
  eng = "maxnet",
  mode = "classification",
  options = list(
    predictor_indicators = "traditional",
    compute_intercept = TRUE,
    remove_intercept = TRUE
  )
)

set_model_arg(
  model = "logistic_reg",
  eng = "maxnet",
  parsnip = "penalty",
  original = "regmult",
  func = list(pkg = "dials", fun = "penalty"),
  has_submodel = FALSE  ## maybe this is TRUE, actually??
)

show_model_info("logistic_reg")
#> Information for `logistic_reg`
#>  modes: unknown, classification 
#> 
#>  engines: 
#>    classification: glm, glmnet, keras, maxnet, spark, stan
#> 
#>  arguments: 
#>    glmnet: 
#>       penalty --> lambda
#>       mixture --> alpha
#>    spark:  
#>       penalty --> reg_param
#>       mixture --> elastic_net_param
#>    keras:  
#>       penalty --> penalty
#>    maxnet: 
#>       penalty --> regmult
#> 
#>  fit modules:
#>    engine           mode
#>       glm classification
#>    glmnet classification
#>     spark classification
#>     keras classification
#>      stan classification
#>    maxnet classification
#> 
#>  prediction modules:
#>              mode engine                              methods
#>    classification    glm           class, conf_int, prob, raw
#>    classification glmnet                     class, prob, raw
#>    classification  keras                          class, prob
#>    classification  spark                          class, prob
#>    classification   stan class, conf_int, pred_int, prob, raw

## here is a rough go at a wrapper function; hopefully you can do better
maxnet_train <- function(x, y, ...) {
  x <- as.data.frame(x)  
  y <- as.integer(as.character(y))
  max_form <- maxnet::maxnet.formula(y, x)
  maxnet::maxnet(p = y, data = x, f = max_form, ...)
}

## Specify the model
sdm_spec <- logistic_reg(penalty = 1) %>% 
  set_engine("maxnet", classes = "lq")

sdm_spec %>%
  translate()
#> Logistic Regression Model Specification (classification)
#> 
#> Main Arguments:
#>   penalty = 1
#> 
#> Engine-Specific Arguments:
#>   classes = lq
#> 
#> Computational engine: maxnet 
#> 
#> Model fit template:
#> maxnet_train(x = missing_arg(), y = missing_arg(), regmult = 1, 
#>     classes = "lq")

bradypus <- bradypus %>%
  mutate(presence = as.factor(presence))

mod_parsnip <- sdm_spec %>%
  fit(presence ~ ., data = bradypus)

plot(mod_parsnip$fit, "tmp6190_ann")
```

![](https://i.imgur.com/NNqUYFN.png)

``` r

## not quite there, because of levels of ecoreg
identical(mod_orig, mod_parsnip$fit)
#> [1] FALSE
```

<sup>Created on 2020-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

So this successfully fits the model, but it doesn't result in the same exact model as the original specification because the parsnip model treats the levels of the factor as columns in a matrix, I think. I'm hoping this can help you move a bit further on the path! This model definitely is quirky, unfortunately, in how the underlying function handles its data and passes it to glmnet (which, to be frank, is also quirky).

**Comment by topepo** [comment]
I agree about making a wrapper function that smooths things out (like we do for xgboost and a few others).

```r
set_engine("maxnet", classes = "lq")
```

makes me cringe. The wrapper would set `classes`  based on the class of the outcome vector; tidymodels requires factors outcomes for classification. The wrapper could also do the outcome type conversion. 

Here's another version that's incomplete (since I don't know what `classes` should be in some cases). It also you optionally pass in `f` too: 

``` r
maxnet_train <- function(x, y, ...) {
 x <- as.data.frame(x)
 if (is.factor(y)) {
  y <- as.integer(as.character(y))
  # I don't know what 'classes' docs mean: 
  # > continuous feature classes desired, either "default" or any subset 
  # > of "lqpht" (for example, "lh").
  cls <- "something"
 } else {
  cls <- "default"
 }
 
 # You might want to pass in `f` so here's a little rlang magic...
 
 # Intercept the dots. If `f` wasn't passed in, add our default: 
 dots <- rlang::list2(...)
 if (!any(names(dots) == "f")) {
  dots$f <- maxnet::maxnet.formula(y, x)
 }

 # Make a call object...
 cl <-
  rlang::call2(
   "maxnet",
   .ns = "mxnet",
   p = y,
   data = x,
   f = max_form,
   classes = cls,
   !!!dots
  )
 
 # Evaluate it to fit the model
 rlang::eval_tidy(cl) 
}
```

``` r

library(maxnet)
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────────────────────────────────────── tidymodels 0.1.1 ──
#> ✓ broom     0.7.0      ✓ recipes   0.1.13
#> ✓ dials     0.0.8      ✓ rsample   0.0.7 
#> ✓ dplyr     1.0.0      ✓ tibble    3.0.3 
#> ✓ ggplot2   3.3.2      ✓ tidyr     1.1.0 
#> ✓ infer     0.5.2      ✓ tune      0.1.1 
#> ✓ modeldata 0.0.2      ✓ workflows 0.1.2 
#> ✓ parsnip   0.1.2      ✓ yardstick 0.0.7 
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
data(two_class_dat, package = "modeldata")
class_int <- ifelse(two_class_dat$Class == "Class1", 1, 0)

orig_fit <- maxnet(class_int, two_class_dat[, c("A", "B")])
head(rownames(orig_fit$beta))
#> [1] "A"                                          
#> [2] "B"                                          
#> [3] "I(A^2)"                                     
#> [4] "I(B^2)"                                     
#> [5] "hinge(A):0.412213735153241:3.93207168716183"
#> [6] "hinge(A):0.484047570908519:3.93207168716183"

new_f <- maxnet(class_int, two_class_dat[, c("A", "B")], f = ~A + B + I(A^2) + I(B^2) - 1)
rownames(new_f$beta)
#> [1] "A"      "B"      "I(A^2)" "I(B^2)"
```

<sup>Created on 2020-07-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by derek-corcoran-barrios** [comment]
Thank you both @juliasilge  and @topepo if Everything works out, I will try to contribute it to tidymodels, It might be worth it to create a new type of models "SDM" since I could build it for several other Species Distribution models that might follow the same logic, plus there might be some custom metrics to add here, which will be a challenge on its own. 

Thank you so much
