### ISSUE TITLE
How to handle model setting in various extension packages

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/parsnip#367]
When I added a `boost_tree()` specification in [survnip](https://github.com/EmilHvitfeldt/survnip) I had to import {baguette} to make sure that `parsnip::set_new_model("bag_tree")` was run before I can set new model modes.

I feel like this could get out of hand quickly with respect to dependencies. Especially since I don't run any code from {baguette}, I just need `baguette::.onload()` to run.

In my case, the issue could be fixed by calling 

```r
parsnip::set_new_model("bag_tree")
```

in parsnip itself. But I'm wondering if it would be beneficial to set models (at least for some packages) centrally in {parsnip}. Thoughts?

This could also act as an authority to avoid conflicts between packages. Right now it would be possible for two different packages to define `gam_reg()` models independently.

**Comment by EmilHvitfeldt** [comment]
Realized it is not as simple as stated in the text above. We need to do more then just registering. My question still stands.

**Comment by topepo** [comment]
I've been including these packages as depends. You want `parsnip` loaded when your package loads so that the model database is updated. 

For a bagged tree engine, would it be a problem to add that engine to `bageutte` directly?

**Comment by EmilHvitfeldt** [comment]
In theory that could be done. But I like the idea of similar models belonging in the same package.

I don't like the dependency problems we get by having baguette as a dependency either. `survnip` gets 30 (119->149) additional dependencies by having to depend on `bageutte`.

How do you feel about moving the bag_tree.R file to parsnip? It won't add any dependencies in parsnip, require minimal changes to `bageutte`, and would make it easier to packages other than `bageutte` to supply `bag_tree()` engines.

**Comment by EmilHvitfeldt** [comment]
This issues has been closes via https://github.com/tidymodels/parsnip/pull/561
