### ISSUE TITLE
mars(): Add changepoint_range (similar to modeltime::prophet_reg)

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/parsnip#368]
Love using `mars()` for time series. It would be easier to use if we add a `changepoint_range` parameter to prevent changepoints from getting too close to the end of a time series. `earth::earth()` implements `endspan`. I recommend changing the calculation from a number to a percent, which is consistent with `modeltime::prophet_reg(changepoint_range)` ([documentation here](https://business-science.github.io/modeltime/reference/prophet_reg.html)), and does not require the user to know how many data points are in the series (just a percentage). 

## Problem

One of the issues with time series models is when trend changepoints get too close to the edge causing instability. This has a negative effect on the `mars()` modeling package. You can see it here:

![image](https://user-images.githubusercontent.com/13734662/91621926-fc77d500-e962-11ea-8f58-7c6fd86055b6.png)

This happens because the changepoints (mars knots) are allowed to go very close to the ends by default. 

![image](https://user-images.githubusercontent.com/13734662/91621980-32b55480-e963-11ea-8d26-40618d9afbbb.png)

## Solution

We can correct this by using the `endspan` argument in the `earth::earth()` model. However, it's a bit challenging because you need to know how much data and how many points. But when I specify no closer than 200 datapoint, the trend becomes spot on. 

```
model_spec_mars <- mars(
    mode = "regression", 
    num_terms = 10
) %>%
    set_engine("earth", endspan = 200)
```

![image](https://user-images.githubusercontent.com/13734662/91622119-a6eff800-e963-11ea-8573-aa3b0c6f7a64.png)

## Recommendation

Prophet does a very similar technique, and I use `prophet_reg(changepoint_range)`, which allows me to specify the range ([0.8 means I can go no farther than 80% of the data are where the changepoints can be located](https://business-science.github.io/modeltime/reference/prophet_reg.html)). 

I recommend implementing this `changepoint_range` in the `mars()` model because the user doesn't need to know how many data points. Just a percentage of data to include in the available changepoint range. 

You can see the effect here, when I forecast against test data. When I get the endspan right, my forecasts are spot on. 

![image](https://user-images.githubusercontent.com/13734662/91622273-59c05600-e964-11ea-8d61-c36f6adff01e.png)

**Comment by mdancho84** [comment]
As a workaround, we can use `set_engine("earth", endspan = tune("endspan"))`, which is pretty sweet.

**Comment by simonpcouch** [comment]
Thanks for the thorough description! As this hasn't come to the top of our to-do list in the last few years, I'm going to go and close this. As you say, folks can still set/tune this parameter via the engine argument!
