### ISSUE TITLE
linear_regression with glmnet engine on resamples

### ISSUE THREAD

**Issue by Bijaelo** [tidymodels/parsnip#374]
After answering a recent question [on stackoverflow](https://stackoverflow.com/q/64187532/10782538) that concerned the package I noticed a (possible) bug that I hadn't noticed while going through chapter 10. While trying to fit resampled linear regressions using `glmnet` as the engine, it starts complaining about lack of penalization.

I'll be using a very similar example as the one used in chapter 7, 8, 9 and 10 `ames`  (only difference in `Sale_Price` is transformed in the recipe)
```R
library(tidymodels)
data('ames', package = 'modeldata')
set.seed(123)
ames_split <- initial_split(ames, prob = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

ames_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
           Latitude + Longitude, data = ames_train) %>%
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_log(Sale_Price, base = 10, skip = TRUE) %>%
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal()) %>% 
  step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) %>% 
  step_ns(Latitude, Longitude, deg_free = 20)

# Create workflow
lmr <- linear_reg() %>%
  set_engine('glmnet') %>%
  set_mode('regression') 
lmw <- workflow() %>% 
  add_recipe(ames_rec) %>%
  add_model(lmr)

#Fit the model
fit(lmw, data = ames_train) # works
folds <- vfold_cv(ames_train, 10)
fit_resamples(lmw, folds) # errors
```
Now the first example works fine using `fit` but `fit_resamples` fails on all iterations with the following error

> x Fold10: model (predictions): Error: `penalty` should be a single numeric value. `multi_predict()` can be u...

Now this was highly unexpected, so I tried doing a bit of digging, first fitting with the juiced data and only a formula spec
```R
ames_train_juices <- juice(prep(ames_rec))
juiced_folds <- vfold_cv(ames_train, 10)
fit_resamples(workflow() %>%
                add_formula(Sale_Price ~ .) %>% 
                add_model(lmr),
              juiced_folds)
```
> x Fold10: model (predictions): Error: `penalty` should be a single numeric value. `multi_predict()` can be u...

But to no avail.  
Something interesting did come from my digging however. In the case where the recipe is reduced (removing dummy creation and so on) a new error occured
```R
fit_resamples(workflow() %>%
                add_recipe(recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
                                    Latitude + Longitude, data = ames_train) %>%
                             step_log(Gr_Liv_Area, base = 10) %>% 
                             step_log(Sale_Price, base = 10, skip = TRUE)) %>% 
                add_model(lmr),
              folds) 
```
which was further unexpected, as the book itself states that `parsnip` will try to translate the input into the proper format, that it knows is necessary for the model input.

**Comment by topepo** [comment]
The rationale for how this works is described in #195

I don't consider this to be a bug. It just behaves differently than `glmnet` does (which, itself works differently than most modeling functions). 

> Is there a way to pick the "best" penalty value from the vector here and automatically use that?

Yes, `tune::tune_grid()`, `tune::tune_bayes()`, ...
