### ISSUE TITLE
Installation Error: set_encodings() allow_sparse_x error

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/parsnip#376]
Hi Max & company, 

Great R package. A few of my students are having issues installing parsnip-adjacent packages like `modeltime` and `treesnip`. [Here's a stackoverflow.](https://stackoverflow.com/questions/64249604/error-package-or-namespace-load-failed-for-treesnip) 

The error looks like:

```
Error: package or namespace load failed for 'treesnip':
 .onLoad failed in loadNamespace() for 'treesnip', details:
  call: NULL
  error: The values passed to `set_encoding()` are missing arguments: 'allow_sparse_x'
error: loading failed
```

**Comment by topepo** [comment]
I'm in the process of making PRs for all of the `parsnip` packages for this. The change is [pretty simple](https://github.com/tidymodels/baguette/commit/9f6dbd43e628320f2c40b0bb9e8b9845b1f023be#diff-953335553e997c9ccb80040bd660398a). 

@Athospd

**Comment by mdancho84** [comment]
You da man. 🔥
