### ISSUE TITLE
summary text for model specification/fit

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#38]
related to topepo/recipes#181...

Use a generic to create a textual summary of a model (e.g. "a random forest classifier with mtry = 4 and the number of trees = 1000")

**Comment by juliasilge** [comment]
Models do have print methods ✅

``` r
library(parsnip)
rand_forest(mode = "classification", mtry = 4, trees = 2000)
#> Random Forest Model Specification (classification)
#> 
#> Main Arguments:
#>   mtry = 4
#>   trees = 2000
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
