### ISSUE TITLE
Set the number of cores/threads to use when predicting

### ISSUE THREAD

**Issue by ndiquattro** [tidymodels/parsnip#386]
## Feature

In situations when you need to scale up prediction with increasing data volume, it would be nice to have the ability to change the number of cores used for prediction. Perhaps something like `predict(workflow_obj, new_data, nthreads = 45)`.

### Example

We're training a xgboost model with `nthread = 25` on a dev machine, but using a 48 core machine in production. It seems to be the nature of XGBoost to use the same number of cores used to train for predicting (we see this behavior). However, we'd like to use the full 48 cores when predicting (smaller machine is used during training). 

### Workaround attempts

Tried following the advice in https://github.com/dmlc/xgboost/issues/1345#issuecomment-231898237 , but setting the environment variable doesn't seem to have an impact and I get an invalid boost object error when trying to call the `xgb.parameters(bst) <-` function on the output of `pull_workflow_fit()`. 

Thanks much! I'm really enjoying tidymodels.

**Comment by simonpcouch** [comment]
Thanks for the issue!🦜 Coming back to this after a good while:

You can indeed use the `xgb.parameters<-` inset to set `nthreads` for prediction, as with xgboost's interface. 

``` r
library(tidymodels)
library(xgboost)
#> 
#> Attaching package: 'xgboost'
#> The following object is masked from 'package:dplyr':
#> 
#>     slice
  
mtcars$cyl <- as.factor(mtcars$cyl)  
  
res <- 
  boost_tree("classification") %>%
  fit(cyl ~ ., data = mtcars)

# use the `xgb.parameters` inset to set threads
xgb.parameters(res$fit) <- list(nthread = 1)

# query xgboost's c++ backend to confirm
xgb.config(res$fit) %>% substr(1, 100)
#> [1] "{\"learner\":{\"generic_param\":{\"fail_on_invalid_gpu_id\":\"0\",\"gpu_id\"
#>      :\"-1\",\"n_jobs\":\"1\",\"nthread\":\"1\",\""
 
predict(res, mtcars)
#> # A tibble: 32 × 1
#>    .pred_class
#>    <fct>      
#>  1 6          
#>  2 6          
#>  3 4          
#>  4 6          
#>  5 8          
#>  6 6          
#>  7 8          
#>  8 4          
#>  9 4          
#> 10 6          
#> # … with 22 more rows

# use the `xgb.parameters<-` inset to set threads
xgb.parameters(res$fit) <- list(nthread = 8)

# query xgboost's c++ backend to confirm
xgb.config(res$fit) %>% substr(1, 100)
#> [1] "{\"learner\":{\"generic_param\":{\"fail_on_invalid_gpu_id\":\"0\",\"gpu_id\"
#>       :\"-1\",\"n_jobs\":\"8\",\"nthread\":\"8\",\""

predict(res, mtcars)
#> # A tibble: 32 × 1
#>    .pred_class
#>    <fct>      
#>  1 6          
#>  2 6          
#>  3 4          
#>  4 6          
#>  5 8          
#>  6 6          
#>  7 8          
#>  8 4          
#>  9 4          
#> 10 6          
#> # … with 22 more rows
```

<sup>Created on 2023-03-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Since that package does not provide an interface via a `predict()` argument to do so (some recent discussion [here](https://github.com/dmlc/xgboost/issues/8869)), I think we'll hold off on that as well.
