### ISSUE TITLE
Update rstanarm function for prediction

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/parsnip#389]
In this line, the rstanarm function needs to change to `rstanarm::posterior_epred()`

https://github.com/tidymodels/parsnip/blob/53722dbcebca037a4ce4cb1f4e7a537e21b5c31a/R/linear_reg_data.R#L261

The warning that is being generated and shown to users at prediction time is:

> Instead of posterior_linpred(..., transform=TRUE) please call posterior_epred(), which provides equivalent functionality.

This also needs to change for `logistic_reg()`.

Related to tidymodels/tidymodels.org#200 and tidymodels/TMwR#43

**Comment by topepo** [comment]
closed by #390
