### ISSUE TITLE
Setting objective in set_engine not respected for xgboost

### ISSUE THREAD

**Issue by lorenzwalthert** [tidymodels/parsnip#403]
I wanted to use one of the many objectives in xgboost described [here](https://xgboost.readthedocs.io/en/latest/parameter.html#learning-task-parameters).
So I went on and wrote this code to set the `objective` in `set_engine()`, as `...` are passed to the engine as described in the docs for `...` in `help(set_engine, package = 'parsnip')`:

>  Any optional arguments associated with the chosen computational engine. [...]

However, I think the [objective is not respected](
https://github.com/tidymodels/parsnip/blob/8af904b7b419ccc713d69f8c99faf1a54cf68a00/R/boost_tree.R#L381), as it is always derived from `mode`, which can only be regression or classification.

```r
library(parsnip)
library(magrittr)
# boost_tree
model <- parsnip::boost_tree(mtry = NULL, trees = 5, mode = 'regression', learn_rate = .1)
model <- parsnip::set_engine(model, "xgboost", objective = "reg:squaredlogerror")
set.seed(4)
data <- matrix(rnorm(1000), ncol = 4) %>%
  tibble::as_tibble() %>%
  dplyr::mutate(y = sample(1000/4))
fit <- model %>%
  parsnip::fit(y ~., data = data)

predict(fit, data)
```

This problem actually did come up in https://github.com/curso-r/treesnip/issues/24, where I wanted to use the quantile objective for `{lightgbm}` and could not and the answer was: "We just copied that code from parsnip". In the interest of a consistent solution to this problem, I am creating an issue here. As described in https://github.com/curso-r/treesnip/issues/24, the maintainers of `{treesnip}` are happy to let the user override the objective, but I thought maybe this topic merits a discussion here, as the same problem applies to `{xgboost}` and other engines too.

I think it should be possible to override the objective if it is consistent with the `mode` argument, because I it can in some instances be orthogonal to the mode (e.g. in my example, i want to use the squared log error) or specify the mode more precisely, e.g. `survival:cox` is a Cox regression, which is consistent with `mode = 'regression'` conceptually I think.

**Comment by topepo** [comment]
Fixed in #411 

``` r
library(parsnip)
library(magrittr)
# boost_tree
model <- parsnip::boost_tree(mtry = NULL, trees = 5, mode = 'regression', learn_rate = .1)
model <- parsnip::set_engine(model, "xgboost", objective = "reg:squaredlogerror")
set.seed(4)
data <- matrix(rnorm(1000), ncol = 4) %>%
  as.data.frame() %>%
  dplyr::mutate(y = sample(1000/4))
fit <- model %>%
  parsnip::fit(y ~., data = data)

predict(fit, data)
#> # A tibble: 250 x 1
#>    .pred
#>    <dbl>
#>  1  1.20
#>  2  1.20
#>  3  1.20
#>  4  1.20
#>  5  1.20
#>  6  1.20
#>  7  1.20
#>  8  1.20
#>  9  1.20
#> 10  1.20
#> # … with 240 more rows
fit$fit$params$objective
#> [1] "reg:squaredlogerror"
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lorenzwalthert** [comment]
Thanks Max.

**Comment by lorenzwalthert** [comment]
If you want to do it, I'd surely prefer that :smile:. There is already an issue for it as mentioned above just to make sure: curso-r/treesnip#24. Thanks a lot.

**Comment by Athospd** [comment]
I went ahead and replicate the logic for catboost and lightgbm to spare @topepo’s time. 
https://github.com/curso-r/treesnip/commit/62fe946522f2fad6203c86c4f77e953aad10a45f and https://github.com/curso-r/treesnip/commit/c15533a7cfd61894bd938127ab529ed48560d3fe
