### ISSUE TITLE
Separate backend for tidy prediction

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/parsnip#41]
I've been reworking the `augment()` methods and it's rapidly becoming clear that dealing with idiosyncratic `predict()` methods is going to slow down progress immensely.

In the end `broom` and `parsnip` are both going to want to wrap a bajillion predict methods, and we should report predictions in the same way for consistencies sake. I think we should move this functionality to a separate package. Potentially we could use the [`prediction`](https://github.com/leeper/prediction) package by Thomas Leeper, but we should decide on the behavior we want first.

If we define a new generic / series of generics, we can then test these behaviors in `modeltests` and allow other modelling package developers to guarantee that their `predict()` methods are sane and consistent.

**What I want from a predict method**:

- Returns a tidy tibble
- Never drops missing data (i.e. matches the behavior of `predict.lm(..., na.action = na.pass)`)
- Consistent naming of fitted values
- Uncertainty in predictions

I want all of these to be guaranteed, and for methods that cannot meet these guarantees, I want an informative error rather than a partially correct output.

**Comment by topepo** [comment]
> Returns a tidy tibble

That would be the most tidy thing to do but my first thought is that it should return a vector unless the prediction contains multiple columns (e.g. class probs, multivariate _Y_). Let me ponder this a bit.

> Never drops missing data

I agree on this. It is something that can happen after prediction if people really don't want those data. 

As a corollary, we should always return the same length/nrow as the input even when the prediction produces multiple columns. That may not be automatically 100% tidy, but I think that it is good practice. 

> Consistent naming of fitted values

👍

We should think about the names though. Let's say that we choose `pred` as the name (just for argument). For numeric outputs, what about quantile regression, risk/probability estimates, and others that have a different context than a simple numeric prediction? Do we have different names and document them or should we keep a single label?


> Uncertainty in predictions

Yes, but not be default (if that's what you mean) since 1) most models don't implement them and 2) they might be computationally taxing and, if you don't want them, why would you take the time to generate them. We should have a formal syntax for getting them though; I just disagree with the defaultedness (sp?)

**Comment by topepo** [comment]
Yes, absolutely.

**Comment by alexpghayes** [comment]
Other thoughts:

- Arguments should always default to `NULL` and missing arguments should error
- The default behavior should be to produce a prediction of the same type as the original response data

This should also all end up in `principles` eventually.

**Comment by alexpghayes** [comment]
Another decision (related to #37): should uncertainty just be reported as a `se.fit` column, or should it be reported as intervals.

**Comment by leeper** [comment]
Also, just to throw out edge cases:

 - predictions from bayesian models typically aren't single values
 - sometimes features relevant to predictions are appended as attributes or other elements in the response lists from `predict()` methods

I'd say a data frame-like structure is the way to go as it's trivial to add columns. A difficult decision in prediction was whether to always include class probabilities and predicted class, or just one or the other. For my purposes, I decided to always do both but in practice it means callling most `predict()` methods twice.

**Comment by topepo** [comment]
> A difficult decision in prediction was whether to always include class probabilities and predicted class, or just one or the other.

Some models don't generate class probabilities. I keep them separate as a default but provide an api to get both at once (with a single call to get the probabilities).

**Comment by leeper** [comment]
I should also add that I'd be really happy to see broom and prediction integrated into one package if we can find a way to make an integrated version serve both our purposes. The key functionality for me is actually for the margins package, which requires the following:

- `prediction::build_datalist()` to get predictions over specified out-of-sample cases
- Some of the convenience functions for getting specific predictions, like `seq_range()`, `mean_or_mode()`, etc. that are currently in prediction but could easily live somewhere else
- A consistent data frame (or tibble) response from `prediction()` (or its equivalent)

I imagine it would be beneficial to the community to have one really good package doing this rather than various packages serving slightly different purposes.

**Comment by leeper** [comment]
If you think it will work for you with modifications, let me know what's missing and I'll try to get it all implemented.

**Comment by topepo** [comment]
How does this should for a prediction standard (pinging @hadley, @artichaud1, and @DavisVaughan for more input) :

Any code to produce predictions should follow these conventions:

 * The return value is a tibble with the same number of rows as the data being predicted. This implies that `na.action` should not affect the shape of the outcome object. 
 * The return tibble can contain extra attributes for values relevant to the prediction (e.g. alpha for intervals) but care should be taken to make sure that these attributes are not destroyed when standard operations are applied to the tibble (e.g. `arrange`, `filter`, etc.). 
 * For univariate, numeric point estimates, the column should be named `pred`. For multivariate numeric predictions (excluding probabilities), the columns should be named `{outcome name}_pred`.  
 * For class probability predictions, the columns should be named the same as the factor levels (with back-ticks when they are not valid column names). 
 * If interval estimates are produced (e.g. prediction/confidence/credible), the column names should be `lower` and `upper`. If a standard error is produced, it should be named `std_error`. 
 * For predictions that are not simple scalars, such as distributions or non-rectangular structures, the `pred` column should be a list-column. Examples:
     * If a posterior distribution is returned for each sample, each element of the list column can be a tibble with as many rows as samples in the distribution. 
     * When a `predict` method produces values over multiple tuning parameter values (e.g. `glmnet`), the list column elements have rows for every tuning parameter value combination that is being changed (e.g. `lambda` in `glmnet`). 
     * In time to event models, where survivor probabilities are produced for values of `time`, the return tibble has a column for `times`. 
* Class predictions should be factors with the same levels as the original outcome. 
* By default, `newdata` should not be returned by the prediction function. 
* The function to produce predictions should be a class-specific `predict` method with argument names `object`, `newdata`, and `type`. Other arguments, such as `alpha`, should be standardized and not named without discussion on [RStudio Community](https://community.rstudio.com/).
* The main predict method can defer to separate, unexported functions (`predict_class`, etc). 
* `type` should also come from a set of pre-defined values such as "response" (numeric values), "class", "prob", and "raw". Other values should be assigned with consensus. 
* If `newdata` is not supplied, an error should be thrown. 
* If there is a strong need for producing output during the prediction phase, there should be a `verbose` option that defaults to no output.

**Comment by leeper** [comment]
> Class predictions should be factors with the same levels as the original outcome.

Named?

> type should also come from a set of pre-defined values such as "response" (numeric values), "class", "prob", and "raw". Other values should be assigned with consensus.

What about "link"?

> If newdata is not supplied, an error should be thrown.

Very good!

> If there is a strong need for producing output during the prediction phase, there should be a verbose option that defaults to no output.

How about `getOption("verbose", FALSE)`?

**Comment by DavisVaughan** [comment]
> The return tibble can contain extra attributes for values relevant to the prediction (e.g. alpha for intervals) but care should be taken to make sure that these attributes are not destroyed when standard operations are applied to the tibble (e.g. arrange, filter, etc.).

Depending on the state of `sloop::reconstruct()` integration with `dplyr`, this could be really simple or a manual (but not difficult) process.

> For class probability predictions, the columns should be named the same as the factor levels (with back-ticks when they are not valid column names).

Any reason to want to format like `{factor_label}_prob` instead? Just thinking about preemptively preventing any name clashes if you somehow joined the prob predictions to something that had the factor labels in a wide format already. Might also be a consistent companion to `pred`.

> If interval estimates are produced (e.g. prediction/confidence/credible), the column names should be lower and upper. If a standard error is produced, it should be named std_error.

Should this include the confidence level? `lower_95` or something similar. See the `forecast` pkg for examples:

```r
library(forecast)
fit <- auto.arima(WWWusage)
forecast(fit, h=20, level=95)
    Point Forecast    Lo 95    Hi 95
101       218.8805 212.6840 225.0770
102       218.1524 203.3133 232.9915
103       217.6789 194.1786 241.1792
104       217.3709 185.6508 249.0910
...
```

**Comment by topepo** [comment]
> Named?

Not sure what you mean. 

> How about `getOption("verbose", FALSE)`?

Maybe... there might be a lot of verbose globals that get made so it would have to be something like `my_model_verbose`. There are good arguments to make that verbosity should be able to be set at different levels (e.g. model fit, feature selection, etc).

**Comment by topepo** [comment]
@DavisVaughan 

> Any reason to want to format like `{factor_label}_prob` instead? Just thinking about preemptively preventing any name clashes if you somehow joined the prob predictions to something that had the factor labels in a wide format already. Might also be a consistent companion to `pred`.

That's good for standardization but bad for consuming those values. So if I go to make a `ggplot`, then a lot of `rename_at` will be going on. 

Let me think about that. 

> Should this include the confidence level? 

No. Then you've encoding data into the name and you can't predict what the name will be easily. I'd rather set an attribute for the level (so that it is there) but not add it to the same or the value.

**Comment by topepo** [comment]
@leeper 

> Named?

~~~Not sure what you mean. ~~~

Sorry, I get it now.

My inclination is to also call it `pred` but I'm torn between that and `class_pred`. I plan on making a new data structure with S3 class `class_pred` so maybe `pred_class`? 

That could get out of hand easily though. Do we end up with `pred_time`, `pred_post_mode` and so on.

**Comment by leeper** [comment]
Agree it's messy but I think it's sensible to keep class predictions as a separate thing. For example, for **margins**, I use predictions for numerical derivatives and want to always be able to count on those being numeric.

**Comment by alexpghayes** [comment]
Naming: I'm not a huge fan of `pred`. See also some [conventions](http://mjskay.github.io/tidybayes/reference/tidybayes-deprecated.html#deprecated-arguments-and-column-names) the Stan crew just went with. I think full singular nouns is the way to go.

>  The return tibble can contain extra attributes for values relevant to the prediction (e.g. alpha for intervals) but care should be taken to make sure that these attributes are not destroyed when standard operations are applied to the tibble (e.g. arrange, filter, etc.).

I think that ideally as much information as possible should be contained in the tibble itself. Users are much more familiar working with tibbles than attributes. For example, for intervals, I'd strongly prefer a column `width` to an attribute. This would make working with multiple intervals at once nicer as well (for plotting, say).

>    For class probability predictions, the columns should be named the same as the factor levels (with back-ticks when they are not valid column names).

No indication that the columns are probabilities in the name?

> If interval estimates are produced (e.g. prediction/confidence/credible), the column names should be lower and upper. If a standard error is produced, it should be named std_error.

Yes.

>  If a posterior distribution is returned for each sample, each element of the list column can be a tibble with as many rows as samples in the distribution.

Not sold on this. For a high level interface, we should not force users to interact with posterior samples. We should provide a default summary of those samples and only optionally return them.

> When a predict method produces values over multiple tuning parameter values (e.g. glmnet), the list column elements have rows for every tuning parameter value combination that is being changed (e.g. lambda in glmnet).

I think we need to think very carefully if we want to do this. My take is that so far this entire thread has been defining a `predict()` method for a single fitted model object. When you have multiple hyperparameter combinations, you are fundamentally working with multiple fitted model objects. I'm not convinced it even makes sense to define `predict()` in this case. If we are going to define fit at all, I think one sensibly option is:

```r
predict.many_fits <- function(...) {
   best_fit <- extract_best_fit(many_fits)
   predict(best_fit)
}
```

to get predictions for different hyperparameter values I'd much prefer a workflow like:

```r
map(many_fits, predict) # many_fits basically a list of fitted objects
```

But I think we should be really careful here.


> If newdata is not supplied, an error should be thrown.

Strongly second this, and came here to recommend it. This is an issue because models often drop rows with missing data silently, which leads to all sorts of nasty surprises and after the fact attempts to determine precisely which rows got dropped.

**Comment by topepo** [comment]
> Naming: I'm not a huge fan of pred. See also some conventions the Stan crew just went with. I think full singular nouns is the way to go.

How about `.pred`, `.pred_class`, `.pred_{class levels}`? `.predicted` or `.prediction` is too long, especially when combined with class levels. 

> I think that ideally as much information as possible should be contained in the tibble itself.

I don't want to do that. It's replicating data that has a single value into a column that is potentially large. 

> Not sold on this. For a high level interface, we should not force users to interact with posterior samples. We should provide a default summary of those samples and only optionally return them.

That's one example of many where the prediction isn't a scalar. Even so, I've had applications where I've needed the full posterior distribution for each sample.  

> I think we need to think very carefully if we want to do this. My take is that so far this entire thread has been defining a `predict()` method for a single fitted model object. When you have multiple hyperparameter combinations, you are fundamentally working with multiple fitted model objects. I'm not convinced it even makes sense to define `predict()` in this case.

I'm only talking about doing it in the cases where the `predict` method make _simultaneous_ predictions across many parameters from a single fitted model object. That's the whole "submodel trick" that `caret` uses for efficiency and it would be lost by repeated calling of `predict` for each parameter value _using the same model object_ (when the underlying predict code gives them all to you at once).

**Comment by artichaud1** [comment]
> I think this is better for other developers extending existing work, since they are less likely to make assumptions about which rows are present than which columns are present.

Not sure if this is still up for debate, and although I favored wide format in the past, more often than not I ended up going to long format for analysis, because it allowed me to standardize my workflow:: filter, group_by, summarise -> send to ggplot.

> But I think we should be really careful here.

That's another reason why I'm playing devil's advocate for long format. I feel that it removes some of the weight in the decision making, i.e. it makes it easier to change ideas whenever, with a lower probability of breaking stuff.

**Comment by kevinykuo** [comment]
This one pops up on my dashboard every day, so I'll join the party ;)

Regarding class probabilities, since we're using tibble anyway, why not just have the probabilities in a listcol? I think it's good to avoid wide tables by default. This would also allow `.prediction` as a column name, which is clearer than `pred/.pred`. Also, we might not always have names of factor levels.

**Comment by topepo** [comment]
> Also, we might not always have names of factor levels.

_spark_ may not, but that will be illegal in the modeling new world order 😃

**Comment by kevinykuo** [comment]
> In classification, people probably want the class prediction as well as the probabilities, so that's already > 1 column even if we make the probabilities a list.

These are definitely subjective points but imo
- 4-5 columns is one thing, but 1000 class probability columns doesn't *feel* as tidy, and
- It's easier to specify the contract/expectations of what you get if you have long rather than wide data.

**Comment by topepo** [comment]
> 4-5 columns is one thing, but 1000 class probability columns doesn't feel as tidy, and

True but I don't want extreme cases to drive the bus

> It's easier to specify the contract/expectations of what you get if you have long rather than wide data.

Unless you are going to merge these results with the original data (which is pretty common).  Plus, you already have wide data anyway with classes and probabilities. If you stack the probabilities then you have a class column that is replicated. Why duplicate data?

**Comment by kevinykuo** [comment]
Oh I didn't mean we should stack probabilities (although upon re-reading it does sound like it!). I'm thinking about appending `.prediction`, `.predicted_class`, and `.class_probabilities` to the dataset for classification. Having to write `paste0("pred_", lvl)` to get the right column feels brittle, although practically it likely won't matter. I guess going down this line of reasoning, we'd also have `.prediction_interval` and friends (and `.prediction` if we have multiple outputs) as list columns, and this may deviate too much from what folks are used to. So yeah, if we're going to do `lower` and `upper`, it would be consistent to have `pred_setosa` and `pred_versicolor`. 😄

**Comment by topepo** [comment]
I think that `parsnip` will have _functions_ to make predictions across submodels (maybe `predict_submodel`?). I think that I'm leaning towards restricting `predict` to produce a single model prediction per object. 

Similarly, add `predict_interval` that will produce `.pred_lower` and `.pred_upper` and also add `predict(object, newdata, type = "interval")` that references it. I'll prototype it with `lm`, `stan`, and `mars`.

**Comment by topepo** [comment]
> So for `predict_boost_tree()` would it have a `type` argument as well so you can specify `class` vs `prob`? And then it would just have a default `type` based off `mode` if no `type` is specified, like the current `predict.model_fit()` has?

Close. There is not `predict_boost_tree`, just `predict.model_spec`. I'm about to merge in a devel branch that shows how [`predict` will pass off to different functions](https://github.com/topepo/parsnip/blob/1f1e3fc385c5ad655255f1e786a15e2335154e5f/R/predict.R#L47). I should just merge that it. 

> And you could call `predict(boost_fit, newdata, type = "whatever")` which would just call `predict_boost_tree()`?

It will call `predict.model_spec` use use `type` to redirect.

**Comment by juliasilge** [comment]
Prediction norms have been fairly standardized for us now. Thanks to all for your thoughts! 🙌
