### ISSUE TITLE
kknn engine fails with factors without calling library(kknn)

### ISSUE THREAD

**Issue by jjcurtin** [tidymodels/parsnip#410]
There appears to be a problem when using nearest_neighbor() and the kknn engine with factors that have not been converted to dummy features using a recipe.  By default, train.kknn() will convert factors to dummy coded features (see its contrasts argument).  However, it uses its own contrast function to do this - contr.dummy().   This function is not available when using nearest_neighbor() unless the user explicitly also loads the kknn package.

The code below reproduces this error. If you add library(kknn) at the top of the code, the error is resolved.   It seems that contr.dummy() needs to be available when using tidymodels with kknn engine.  Thanks for looking into this

library(tidymodels)
# library(kknn) # uncomment this line to resolve the error below

# simulate data
set.seed(1969)
train <- tibble(x = factor(c(rep(0, 20), rep(1, 20), rep(2, 20))),
                y = rnorm(60, 0, 50))

algo <-
  nearest_neighbor() %>%   
  set_engine("kknn") %>%   
  set_mode("regression")   

rec <- 
  recipe(y ~ x, data = train)

fit <- 
  workflow() %>% 
  add_model(algo) %>% 
  add_recipe(rec) %>% 
  fit(data = train)

# Error in get(ctr, mode = "function", envir = parent.frame()) : 
#   object 'contr.dummy' of mode 'function' was not found

**Comment by juliasilge** [comment]
This is the same as #264. Do you mind adding any new info you have to that issue, instead of opening a new one? And/or adding a ➕ or 👍 ?

**Comment by topepo** [comment]
This is a problem with that specific package. See KlausVigo/kknn#16. I have a few issues and PRs there (some from 2018) but no action to date.

**Comment by jjcurtin** [comment]
My apologies for not finding the previous issue report.   That is exactly the issue I reported and it seems well described with an example.  I have nothing to add other than a 👍, which I did

Thanks for a great modeling environment.  I am updating my grad machine learning course this spring to switch from caret to tidy models.  I loved caret but I really love tidy models so far.

much appreciated

John

John J. Curtin, Ph.D.
Professor and
Director of Clinical Training
Department of Psychology
University of Wisconsin-Madison
1202 West Johnson St
Madison, WI 53706

608-262-0387
https://arc.psych.wisc.edu<https://arc.psych.wisc.edu/>
https://uwmadison.zoom.us/j/6082176221

pronouns:  he/him/his
________________________________
