### ISSUE TITLE
re-organize model/engine documentation

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#422]
I feel like there are two issues that make the current documentation less effective: 

 1. Model help packages become very long since we document all of the engines there. Since it throws a lot of information at the user, it is more difficult to find information and they might not read it at all. 
 2. We need a way to reference documentation of engines that are provided by other packages. For example, `multilevelmod` has engines for `linear_reg()` and other models. The user might not be able to find those engine-specific notes. 

The [`clock` documentation](https://davisvaughan.github.io/clock/) is nicely organized by having a main page for a generic and sub-pages for the specific methods. For example, the [getter functions](https://davisvaughan.github.io/clock/reference/clock-getters.html) show the generic methods and there are clear links at the top of the page that show the information for different types of calendars. 

To solve the first problem listed above, we could make rd files for model/engine combinations and link those at the top of the model page. 

For the issue with `parsnip`-adjacent packages, the `parsnip` model pages could also use dynamic documentation to make that list of links at the top (depending on what is available/attached at the moment).  This would be similar to how [`generics` shows a list of methods dynamically](https://github.com/r-lib/generics/blob/017e465bb3382c9913dc4aa8a7bb1f426c14147e/R/glance.R#L13).

**Comment by EmilHvitfeldt** [comment]
Suggestion: Can we add some technical/theoretical information on what the model is in the documentation. For example [linear_reg()](https://parsnip.tidymodels.org/reference/linear_reg.html) says it is a specification for a "Linear Regression Model" but there isn't much detail. It would be helpful with a sentence/paragraph explaining what model the specification is doing + some links to more technical literature.

Secondly, it would be nice if the function/package used to implement the engine can be hyperlinked in the documentation itself.

**Comment by hfrick** [comment]
related: #74

**Comment by topepo** [comment]
Closed by #456
