### ISSUE TITLE
Removing `update.*()` from Github Pages 

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/parsnip#423]
Right now the `update.*()` functions are listed alongside their respective model specification function on the [reference page](https://parsnip.tidymodels.org/reference/index.html) on Github Pages. I feel that they add more visual noise than the utility. Don't know if this change is desirable or doable.

# Current version
<img width="818" alt="Screen Shot 2021-02-01 at 1 39 43 PM" src="https://user-images.githubusercontent.com/14034784/106525778-5c862080-6499-11eb-9329-0230991c6731.png">

# Suggested version
<img width="820" alt="Screen Shot 2021-02-01 at 1 40 30 PM" src="https://user-images.githubusercontent.com/14034784/106525785-5db74d80-6499-11eb-86f4-59c1741192e7.png">

**Comment by juliasilge** [comment]
Maybe in our planned re-organization discussed in #422 we could consider making a separate `.Rd` file for the `update()` methods.

**Comment by EmilHvitfeldt** [comment]
Sounds good!
