### ISSUE TITLE
Early stopping and stop_iter not working properly.

### ISSUE THREAD

**Issue by mlane3** [tidymodels/parsnip#437]
##  Early stopping and stop_iter do not behave as expected because they are unable to be adjusted
Issue number #237 requested that early_stop and stop_iter be adjustable for XGBoost models.  When I was trying to assess the quality of my data and adjusted this parameter I received the following error.
`! Fold01: preprocessor 1/1, model 1/30: The following arguments cannot be manually modified and were removed: early_stop.`

### Reproducible example
The full example can be found here:  [https://gist.github.com/mlane3/b62408aa86a00f0591e5d16a6f4c6ab6](https://gist.github.com/mlane3/b62408aa86a00f0591e5d16a6f4c6ab6 )
The specific lines of code that I receive the error is on the set engine line
```
xgb_spec <- boost_tree(
  trees = 14, 
  tree_depth = tune(), min_n = tune(), 
  loss_reduction = tune(),                     ## first three: model complexity
  sample_size = tune(), mtry = tune(),         ## randomness
  learn_rate = tune(),                         ## step size
) %>% 
  set_engine("xgboost",early_stop=1000,verbose=1) %>% 
  set_mode("classification")
```

### Second Attempt using stop_iter
I also tried to change those lines to this:

```
xgb_spec <- boost_tree(
  trees = 15, 
  tree_depth = tune(), min_n = tune(), 
  loss_reduction = tune(),                     ## first three: model complexity
  sample_size = tune(), mtry = tune(),         ## randomness
  learn_rate = tune(),                         ## step size
) %>% 
  set_engine("xgboost",early_stop=1000,verbose=1) %>% 
  set_mode("classification")
```
There is then this error which while expected is also not a good warning to a user using tidymodels.
`Fold01: preprocessor 1/1, model 14/100, `early_stop` was reduced to 14.`

### Statistical Reasoning behind why this bug is concerning
So I decide to track down the line of code that throws the error and the statistical reasoning doesn't make sense either: https://rdrr.io/cran/parsnip/src/R/arguments.R
This function seems to be trying to avoid changing ""explicitly constant"" parameters.
The assumption made for when to reduce early stopping is statistical approximation and not a law.  For example, Pang Wei Koh paper on overfitting (https://arxiv.org/pdf/1703.04730.pdf) is an old but open challenge to the conventional wisdom on XGBoost.   
From a code design standpoint you really should make the user unable to change even the smallest parameter.  It would be better to throw warnings instead.  In fact,  a warning that only certain variables can be changed one at a time in the case of the second example.

**Comment by topepo** [comment]
I think that there are two issue here: 

 * You should be specifying the early stopping iterations using the main argument (`stop_iter`) not the engine argument (`early_stop`). Sorry if that is confusing. 
 * If you are inly using 14 or 15 iterations of boosting, the early stopping value should be less than that. That is why it was reduced instead of failing. For example, if I use `stop_iter = 3`, there are no errors or warnings. 

You can change any parameter but make sure that they are not in the main parameter list. If it helps, there is a translation guide at the engine of the engine details section: 

![image](https://user-images.githubusercontent.com/5731043/110031358-ceee5880-7d04-11eb-8b84-6eec119cedc9.png)

**Comment by jrosell** [comment]
I don't see stop_iter() function on dials package. Is it not tunneable?

**Comment by topepo** [comment]
We'll add it but you can create a grid manually to tune it for now. I'll close this since there is another issue.
