### ISSUE TITLE
Add RANSAC algorithm

### ISSUE THREAD

**Issue by paulponcet** [tidymodels/parsnip#441]
RANSAC or Random Sample Consensus is a popular iterative algorithm for regression in presence of outliers, as described e.g. here https://en.wikipedia.org/wiki/Random_sample_consensus. 

It would be a great feature if the `parsnip` package would include such an algorithm, able to use any regression spec as input.

**Comment by topepo** [comment]
I don't think that we'll implement this right now. You are welcome to make a `parsnip`-adjacent package to do it though.
