### ISSUE TITLE
Addition of Approximate Nearest Neighbors to nearest_neighbor engines.

### ISSUE THREAD

**Issue by UnclAlDeveloper** [tidymodels/parsnip#457]
Would it be possible to add RANN or an Approximate Nearest Neighbors algorithm as an engine option to nearest_neighbor?

KNN is not a very good predictor on its own, but as part of a stack of algorithms it is a useful addition as it tends to have low correlation to other more powerful models, and thus improves the predictiveness of a stack model.  The only problem is that it is o(n^2) which means it cannot be used on larger data sets.  ANN is o(n.log(n)) so would be a useful addition.

**Comment by topepo** [comment]
Sure. I don't know that we will get to this soon so you are welcome to make a PR with that engine.

**Comment by topepo** [comment]
I'll close this but reference it if you make a PR
