### ISSUE TITLE
Re-licensing parsnip 🚀

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/parsnip#462]
We are systematically re-licensing tidymodels packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all non-RStudio [contributors](https://github.com/tidymodels/parsnip/graphs/contributors). 

@EmilHvitfeldt, @patr1ckm, @simonpcouch, @stevenpawley, would you permit us to re-license parsnip with the MIT license? If so, please comment "I agree" below.

* [x] [@EmilHvitfeldt](https://github.com/tidymodels/parsnip/commits?author=EmilHvitfeldt)  
* [x] [@patr1ckm](https://github.com/tidymodels/parsnip/commits?author=patr1ckm)  
* [x] [@simonpcouch](https://github.com/tidymodels/parsnip/commits?author=simonpcouch)  
* [x] [@stevenpawley](https://github.com/tidymodels/parsnip/commits?author=stevenpawley)

**Comment by simonpcouch** [comment]
I agree. :-)

**Comment by patr1ckm** [comment]
I agree

**Comment by EmilHvitfeldt** [comment]
I agree 🚀

**Comment by stevenpawley** [comment]
I agree, thanks!

**Comment by juliasilge** [comment]
Thanks so much, all! 🙏
