### ISSUE TITLE
rlang: Use `vctrs::vec_cast()` instead of `lgl()`/`as_logical()` (deprecated)

### ISSUE THREAD

**Issue by hsbadr** [tidymodels/parsnip#496]
```r
> lgl(1)
Error: (converted from warning) `as_logical()` is deprecated as of rlang 0.4.0
Please use `vctrs::vec_cast()` instead.
Backtrace:
     ▆
  1. └─rlang::lgl(1)
  2.   └─`/rlang.so`::ffi_squash()
  3.     └─`/rlang.so`::r_squash_if()
  4.       └─`/rlang.so`::atom_squash()
  5.         └─`/rlang.so`::r_vec_poke_coerce_n()
  6.           └─(function (x) ...
  7.             └─rlang:::signal_deprecated_cast("as_logical")
  8.               └─rlang:::signal_soft_deprecated(...)
  9.                 └─rlang:::warn_deprecated(msg, id)
 10.                   └─base:::.Signal(msg = msg)
```
https://github.com/tidymodels/parsnip/blob/6d6b0a7b01eeedca0420f0acbb57cd628c6c4312/R/misc.R#L57

**Comment by DavisVaughan** [comment]
We should just use `logical(1)` here.

@hsbadr how did you manage to force this warning to appear in parsnip itself?

**Comment by hsbadr** [comment]
> how did you manage to force this warning to appear in parsnip itself?

With the dev version of `rlang`:

```r
> parsnip::linear_reg()
Linear Regression Model Specification (regression)

Warning message:
`as_logical()` is deprecated as of rlang 0.4.0
Please use `vctrs::vec_cast()` instead.
```

Also, I use [`winch`](https://github.com/r-prof/winch), and the following options:

```r
options(
  error = rlang::entrace,
  lifecycle_disable_warnings = FALSE,
  lifecycle_repeat_warnings = TRUE,
  lifecycle_verbose_soft_deprecation = TRUE,
  lifecycle_verbosity = "warning",
  rlang_backtrace_on_error = "full",
  rlang_trace_use_winch = TRUE
)
```

**Comment by hsbadr** [comment]
> We should just use `logical(1)` here.

`rlang::lgl(1)  == TRUE` while `logical(1) == FALSE`; maybe, just use `TRUE` or  `vctrs::vec_cast(1, logical())`, for the general case.

**Comment by DavisVaughan** [comment]
It's probably this one that forces the warning to be thrown

```r
rlang::with_options(rlang::lgl(1), lifecycle_verbose_soft_deprecation = TRUE)
#> Warning: `as_logical()` is deprecated as of rlang 0.4.0
#> Please use `vctrs::vec_cast()` instead.
#> This warning is displayed once per session.
#> [1] TRUE
```

I don't think this is technically our fault, as the warning is about `as_logical()` being deprecated, but we are using `lgl()` (which is questioning at the moment, but not deprecated yet). So to me this looks like a corner case rlang bug. I've mentioned it to the maintainer.

**Comment by hsbadr** [comment]
Thanks @DavisVaughan! I see. It's probably better to replace the use of questioning functions, especially if it requires a very simple change. I agree that this is a very minor `rlang` bug though.

**Comment by lionel-** [comment]
Fixed in https://github.com/r-lib/rlang/commit/56d2e389.

**Comment by juliasilge** [comment]
Thanks so much, all! 🙌
