### ISSUE TITLE
Request support for `lightgbm` engine

### ISSUE THREAD

**Issue by joeycouse** [tidymodels/parsnip#502]
Related to #370. Has there been any consensus among the `tidymodels` team on whether `lightgbm` will be added to `parsnip`? `lightgbm` has been on CRAN for a while now and has a very similar syntax to `xgboost`. The Microsoft team seems willing to adapt `lightgbm` to better integrate with `tidymodels` https://github.com/tidymodels/parsnip/issues/370#issuecomment-735519252

**Comment by topepo** [comment]
See the [`treesnip`](https://github.com/curso-r/treesnip) package.

**Comment by juliasilge** [comment]
Thanks so much for your thoughts @joeycouse! 🙌 Let us know if you have further questions.
