### ISSUE TITLE
 Error: Model `area_level` already exists

### ISSUE THREAD

**Issue by graysonwhite** [tidymodels/parsnip#516]
Hey there! I am just starting to write a package that builds some parsnip models for small area estimation ([`subpop`](https://github.com/graysonwhite/subpop)). I have been using an `.onLoad` call to register the model every time the package is loaded:
```
.onLoad <- function(libname, pkgname) {
  make_area_level()
}
```
where `make_area_level` registers the model. 

It seems that when I include this `.onLoad` function I get an error when running `devtools::load_all` more than once:
```
 Error: Model `area_level` already exists
```
This can be fixed by restarting the R session, as mentioned in #307, but I was wondering if there is a nice workflow to avoid having to restart the R session every time I would like to run `devtools::load_all`.

**Comment by topepo** [comment]
No, it is usually safest to do a full restart when using `parsnip` 😞

**Comment by graysonwhite** [comment]
Gotcha, thanks for the quick response! Glad that I am not just missing something 🙂
