### ISSUE TITLE
Use rlang::check_installed() on checking the dependencies

### ISSUE THREAD

**Issue by yutannihilation** [tidymodels/parsnip#526]
Currently `parsnip:::check_installs()` just aborts when the dependency package is not installed yet. I think it would be helpful to use `rlang::check_install()` to let users install the packages interactively.

```
> rlang::check_installed(c("foo", "bar"))
ℹ The `foo` and `bar` packages are required.
x Would you like to install them?

1: Yes
2: No

Selection:
```

**Comment by topepo** [comment]
I think that it is better to leave as-is. If someone is using parallel processing during and interactive session, we don't want the worker processes trying to prompt the user for input. 

If you want, you could create a `check_package_dependency()` function that will do the interactive bits outside of the tuning or resampling processes.

**Comment by yutannihilation** [comment]
Ah, I didn't consider parallelism, sorry...

**Comment by topepo** [comment]
No worries. It is was a good idea.

**Comment by juliasilge** [comment]
We could consider adding an additional "precheck" check before fitting happens (possibly in workers) to see if packages are installed in the main R process. This "precheck" (using `rlang::check_installed()` would probably be helpful and involve less friction for the majority of R users.

**Comment by simonpcouch** [comment]
In light of the above discussion, and for consistency with `tune:::check_installs()`, we'll continue to fail here. As long as we continue to fail early, I think this is indeed the right way to go.
