### ISSUE TITLE
Vignette update request

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/parsnip#53]
Just took a look over the [making a parsnip model object from scratch](https://topepo.github.io/parsnip/articles/articles/Scratch.html) vignette. There was a lot going on and I had a bit of difficulty putting the pieces together from my short glance through. I think the vignette might benefit from being broken into two separate pieces:

- Creating new model specifications
- Adding a new estimator for an existing model specification
    - Aside: it would be easy to confuse an engine with an estimator, so we should probably document the difference somewhere.

I finally have `parsnip` running on my laptop and I'm going to try to use it exclusively for a regression course this semester and see where I run into problems. Some things I imagine I'll be building fairly early on:

- Mixed models. I should just be able to pass formulas to `lme4` with the usual random effects syntax, right?
- Robust covariance estimators. The easy way to do this is probably via a new `lm_robust` engine.

**Comment by sctyner** [comment]
Commenting for a +1 on mixed models!

**Comment by juliasilge** [comment]
We are in the process of moving the developer article ("how to build a parsnip model") to the soon-to-launch tidymodels.org site (with edits).

Mixed/hierarchical models (using stan) are a priority in the near term as well. 👍
