### ISSUE TITLE
Error: For the glmnet engine, `penalty` must be a single number (or a value of `tune()`)

### ISSUE THREAD

**Issue by stephenhillphd** [tidymodels/parsnip#549]
When building a ridge regression model (using "glmnet") I am encountering the error:

"Error: For the glmnet engine, `penalty` must be a single number (or a value of `tune()`). * There are 0 values for `penalty`. * To try multiple values for total regularization, use the tune package. * To predict multiple penalties, use `multi_predict()`"

A MWE is provided below. The error occurs for both ridge and lasso (mixture = 1). 

The error appears when using parsnip 0.1.7, but does not appear in parsnip 0.1.3. glmnet version is 4.1-2 on both machines. 

Any ideas? Thank you.

```r
library(tidyverse) #tidyverse set of packages and functions
library(tidymodels)
library(glmnet) #for Lasso, ridge, and elastic net models 

mwe_recipe = recipe(mpg ~., mtcars) %>% #add all variables via ~.
  step_center(all_predictors()) %>% #centers the predictors
  step_scale(all_predictors()) #scales the predictors
  
ridge_model = #give the model type a name 
  linear_reg(mixture = 0) %>% #mixture = 0 sets up Ridge Regression
  set_engine("glmnet") #specify the specify type of linear tool we want to use 

ridge_wflow = 
  workflow() %>% 
  add_model(ridge_model) %>% 
  add_recipe(mwe_recipe)

ridge_fit = fit(ridge_wflow, mtcars)
```

**Comment by juliasilge** [comment]
This change occurred in [parsnip 0.1.6](https://github.com/tidymodels/parsnip/blob/master/NEWS.md#parsnip-016):

> For models with `glmnet` engines: 
>
>  - A single value is required for `penalty` (either a single numeric value or a value of `tune()`) (#481).
>  - A special argument called `path_values` can be used to set the `lambda` path as a specific set of numbers (independent of the value of `penalty`). A pure ridge regression models (i.e., `mixture = 1`) will generate incorrect values if the path does not include zero. See issue #431 for discussion (#486).

We consider the old behavior misleading/problematic because you as the modeling practitioner are getting _something_ for the penalty but probably aren't entirely sure what it is. With this change, you can either set it (a single number like `penalty = 0.1`) or tune it to find the best value (with `penalty = tune()`).

**Comment by juliasilge** [comment]
Let us know if you have further questions or problems! 🙌
