### ISSUE TITLE
(Documentation formatting only) In documentation, there should be multiple first-level bullets

### ISSUE THREAD

**Issue by daaronr** [tidymodels/parsnip#554]
![image](https://user-images.githubusercontent.com/8229168/134049013-8244c300-c41f-4bff-8be9-c0c68f50b704.png)

The second-level bulleting makes me think these are 'sublists' within the `args` element of the `model_spec` object. 

I think these should be first-level bullets

**Comment by juliasilge** [comment]
Thanks so much for the report @daaronr! 🙌 

You can see the fix [implemented in the dev pkgdown site here](https://parsnip.tidymodels.org/dev/reference/model_spec.html).
