### ISSUE TITLE
Templating of description of models

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/parsnip#566]
The following lines appear in all the model specifications, should they be templated?

https://github.com/tidymodels/parsnip/blob/af46f571c4e7ea07d7a707bc1a12e3567ff93e5e/R/boost_tree.R#L11-L12

https://github.com/tidymodels/parsnip/blob/af46f571c4e7ea07d7a707bc1a12e3567ff93e5e/R/boost_tree.R#L16-L17

**Comment by simonpcouch** [comment]
Implemented in #631. :)
