### ISSUE TITLE
option to turn off `fit time` printing of fitted parsnip objects

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/parsnip#578]
When rerunning uncached code, it can be a little annoying to get git diffs because of a different fit time. Would it be possible to have a global option to turn it off? 

https://github.com/tidymodels/parsnip/blob/a97e938d4a967e3f777639efbd6398b62153ac09/R/fit.R#L421-L423

**Comment by juliasilge** [comment]
Closed in #614
