### ISSUE TITLE
Model help page breaks with only non-default engines

### ISSUE THREAD

**Issue by hfrick** [tidymodels/parsnip#586]
When I was testing out the new documentation for censored, I noticed that I have in order to see the engine pages for `bag_tree()` I have to load baguette. censored also contains an engine but it won't show if baguette isn't loaded. First wild guess is that maybe that's related to baguette containing the default engine.

```
pak::pak("tidymodels/parsnip@doc-survival")
pak::pak("tidymodels/baguette")
pak::pak("tidymodels/censored@doc-new-parsnip-style")
```

This works as expected:
```
library(parsnip)
?bag_tree # no engines
library(baguette)
?bag_tree # engines from baguette
library(censored)
?bag_tree # engines from baguette and censored
```
This does not (remember to restart the session):
```
library(censored)
?survival_reg # works and shows doc from parsnip without any engines
?bag_tree # gives internal server error
library(baguette)
?bag_tree # now works and shows engines from baguette and censored
```

**Comment by juliasilge** [comment]
This was addressed in #631 also, right @hfrick?
