### ISSUE TITLE
Dynamically include different modes in engine-specific documentation

### ISSUE THREAD

**Issue by hfrick** [tidymodels/parsnip#587]
Currently the documentation is designed to dynamically show which engines are available based on the loaded packages. However, the modes covered by these engines are not dealt with dynamically.

Example:
For `decision_tree()`, parsnip contains the `rpart` engine for modes `classification` and `regression`. censored includes an `rpart` engine for the `censored regression` mode but can't include documentation for it easily.

**Comment by juliasilge** [comment]
This was addressed in #631, right, @hfrick?

**Comment by hfrick** [comment]
yes, it was 👍
