### ISSUE TITLE
Sparse group lasso (SGL) as a new engine for linear_reg, logistic_reg, and proportional_hazards

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/parsnip#595]
## Feature

Is there any interest in adding `{SGL}` as an engine for `linear_reg()`, `logistic_reg()`, and `proportional_hazards()` models in `parsnip`? The function mostly works like `glmnet`, but the two implementation challenges I see might be:
- It uses a `data` interface which accepts a list of `x` and `y`, rather than a formula or separate x/y arguments
- There needs to be some way to indicate a variable corresponding to group membership, but this may need to play nicely with `recipes` and `tune`. Not sure if the `tune()` sentinel function would work in this situation. This would take some thought about how to implement.

If there is interest I could work on submitting a PR for this implementation.

Relevant: https://cran.r-project.org/web/packages/SGL/SGL.pdf

**Comment by topepo** [comment]
The function's interface is not great and may be an issue if there is any disconnect between the predictors given to `parsnip` or `workflows` and the ones given to `SGL`. To define the groups: 

> `index`: A p-vector indicating group membership of each covariate

which is a fairly oblique way of saying "For each predictor, in their order in `x`, provide an integer for which group they reside."

If users need to generate dummy variables for a predictor, they would have to spell out the resulting column names ahead of time. Also, if there are any preprocessing methods used they may not know the names ahead of time. Also also, if they are resampled there could be gaps in the `index` results. 

It might be possible to make a wrapper for this function that uses `dplyr` selectors or something that could construct the `index` vector based on what is generated. 

Despite what I've written above, I would suggest that you take a shot at making a wrapper if the model is important to you. I don't think that we will do it but we would help you if you want to own it.

**Comment by mattwarkentin** [comment]
Does `recipes` internally store the mapping from old variable names to new variable names? Like if a factor is dummied, is there an internal which original variable led to the creation of the indicators? Other than manually parsing the new variable names.

**Comment by topepo** [comment]
The `tidy()` method has that data. 

In general, it's pretty much impossible to track the original column to the final feature given all the things that could happen to it.
