### ISSUE TITLE
provide a way to unregister models after model registration

### ISSUE THREAD

**Issue by yitao-li** [tidymodels/parsnip#597]
Typically packages providing `parsnip` interfaces run `parsnip::set_model_engine()` within the `.onLoad()` callback. It looks like in some scenarios (e.g., development flows using `devtools`) they also need a way to unregister models within the `onUnload()` callback. Otherwise the next time the `.onLoad()` callback is run, there will be an error saying models are being registered twice.

**Comment by juliasilge** [comment]
Can you give an example of where you are experiencing this @yitao-li? We use the development flows of devtools for parsnip and our parsnip extension packages like [baguette](https://github.com/tidymodels/baguette), [plsmod](https://github.com/tidymodels/plsmod), etc and do not experience this. Perhaps we can offer some advice on how to avoid it.

**Comment by yitao-li** [comment]
@juliasilge It can be re-pro'd with (for example) the following:

```
git clone https://github.com/mlverse/cuda.ml.git
cd cuda.ml

# launch the R interpreter, and then run
devtools::load_all()
devtools::test()
```

The error message was

"
Error: The combination of 'cuml' and mode 'classification' already has a fit component for model 'rand_forest'.
Run `rlang::last_error()` to see where the error occurred.
"

There is, of course, also the usual pkg workflow that essentially run the 2 `devtools` functions above in RStudio in that order, which people are used to, and it would be nice to make it work (e.g., see Tomasz's comment in https://github.com/mlverse/cuda.ml/pull/112#pullrequestreview-758905914).

**Comment by juliasilge** [comment]
Hmmmm, I am not able to get that package to build at all; looks like the [CUDA library you are wrapping requires Linux](https://rapids.ai/start.html). 

Do you have a more minimal example of the problem?

**Comment by hfrick** [comment]
I think `censored` is an example for that. I can run `devtools::load_all()` once just fine, if I run is a second time it fails:

```
> devtools::load_all(".")
ℹ Loading censored
Loading required package: parsnip

> devtools::load_all(".")
ℹ Loading censored
Error: The combination of 'survival' and mode 'censored regression' already has a fit component for model 'proportional_hazards'.
Backtrace:
 1. devtools::load_all(".")
 2. pkgload::load_all(...)
 3. pkgload:::run_pkg_hook(package, "load")
 4. nsenv[[f_name]](dirname(ns_path), package)
 5. censored:::make_proportional_hazards_survival() R/0_imports.R:29:2
 6. parsnip::set_fit(...) R/proportional_hazards_data.R:18:2
```

**Comment by topepo** [comment]
This is one reason why I don't use `load_all()`. Besides this error it is difficult to know when the parsnip database has been rebuilt and registered.

**Comment by hfrick** [comment]
@yitao-li We spoke some more about this at our team meeting today. `load_all()` [does not call `.onUnload()`](https://github.com/r-lib/pkgload/blob/e43073ca71fd9e2c3a759f472568518e8801353d/R/load.r#L65) and that's [intentional](https://github.com/r-lib/pkgload/issues/148). So basically even if parsnip had tools to unregister models and an extension package called them in `.onUnload()` the usual devtools workflow would not work :cry: So parsnip might gain such tools at some point if there are other use cases for them but we don't plan on adding them now.

**Comment by yitao-li** [comment]
@hfrick Good to know. Thanks for looking into it! :+1:
