### ISSUE TITLE
Add nfold argument to mars() so prune_method = 'cv' can be used

### ISSUE THREAD

**Issue by NickCH-K** [tidymodels/parsnip#607]
## Add nfold argument to mars()

I'm working on a [Stata API](https://github.com/NickCH-K/MLRtime) for **parsnip** (among other packages) and have an RA trying a bunch of different model specifications to make sure they work. One they stumbled upon is that there doesn't seem to be possible to use `prune_method = 'cv'` in the `mars()` function. Doing so requires that the `nfold` option be set, but there is no option in `mars()` to set the `nfold` option.

Example:

```r
mars(mode = "regression", prune_method = 'cv') %>% fit(mpg ~ hp + am, data = mtcars)
# Error: the nfold argument must be specified when pmethod="cv"
# Timing stopped at: 0 0 0
mars(mode = "regression", prune_method = 'cv', nfold = 10) %>% fit(mpg ~ hp + am, data = mtcars)
#Error in mars(mode = "regression", prune_method = "cv", nfold = 10) : 
#  unused argument (nfold = 10)
```

Seems like a useful thing to add! Thank you.

**Comment by hfrick** [comment]
Any additional arguments for the underlying engine/fitting function can be set in `set_engine()`:

``` r
library(parsnip)

mars(mode = "regression", prune_method = 'cv') %>% 
  set_engine("earth", nfold = 10) %>% 
  fit(mpg ~ hp + am, data = mtcars)
#> parsnip model object
#> 
#> Fit time:  924ms 
#> Selected 5 of 6 terms, and 2 of 2 predictors (pmethod="cv")
#> Termination condition: RSq changed by less than 0.001 at 6 terms
#> Importance: hp, am
#> Number of terms at each degree of interaction: 1 4 (additive model)
#> GRSq 0.703758  RSq 0.8369282  mean.oof.RSq -0.07107984 (sd 2.29)
#> 
#> pmethod="backward" would have selected:
#>     4 terms 2 preds,  GRSq 0.7372506  RSq 0.8291172  mean.oof.RSq -3.589344
```

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by NickCH-K** [comment]
Ah, that makes sense. Thank you!
