### ISSUE TITLE
deprecate 'fit_control()' in favor of 'control_parsnip()'

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/parsnip#609]
https://github.com/tidymodels/parsnip/blob/dd36a954d58c73b67a118e0b79f79f770e9ce703/R/control_parsnip.R#L17-L28

should be

```
#' @return An S3 object with class "control_parsnip" that is a named list with the 
```

**Comment by topepo** [comment]
While you are at it, go ahead and use our deprecation process for `fit_control()` 😄
