### ISSUE TITLE
Adding links to logistic regression

### ISSUE THREAD

**Issue by gmcmacran** [tidymodels/parsnip#619]
## Feature

Is there interest in adding a few new links to logistic regression? The package extendedFamily (https://CRAN.R-project.org/package=extendedFamily) implements new family objects.  I imagine most of the work would be documentation. If there is interest, I would take the lead on this and issue a pull request. 

library(GlmSimulatoR)
library(extendedFamily)
library(tidymodels)

set.seed(1)
dat <- simulate_binomial(N = 1000, link = "loglog",weights = c(0.1, 0.2)) %>% 
  mutate(Y = factor(Y, levels = c("1", "0")))

loglog_fit <- logistic_reg() %>% 
  set_engine("glm", family = binomialEF("loglog")) %>% 
  fit(Y ~ ., data = dat)
tidy(loglog_fit)

loglog_fit_2 <- glm(formula = Y ~ X1 + X2, data = dat, family = binomialEF("loglog"))
summary(loglog_fit_2) # confirm weights match

**Comment by juliasilge** [comment]
It looks to me like this works as is:

``` r
library(GlmSimulatoR)
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
set.seed(1)
dat <- simulate_binomial(N = 1000, link = "loglog",weights = c(0.1, 0.2)) %>%
  mutate(Y = factor(Y, levels = c("1", "0")))


parsnip_fit <-
  logistic_reg() %>%
  set_engine("glm", family = extendedFamily::binomialEF("loglog")) %>%
  fit(Y ~ ., data = dat)

parsnip_fit
#> parsnip model object
#> 
#> 
#> Call:  stats::glm(formula = Y ~ ., family = ~extendedFamily::binomialEF("loglog"), 
#>     data = data)
#> 
#> Coefficients:
#> (Intercept)           X1           X2  
#>     0.65511     -0.04115     -0.36678  
#> 
#> Degrees of Freedom: 999 Total (i.e. Null);  997 Residual
#> Null Deviance:       1333 
#> Residual Deviance: 1326  AIC: 1332
tidy(parsnip_fit)
#> # A tibble: 3 × 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)   0.655      0.312     2.10  0.0359 
#> 2 X1           -0.0411     0.146    -0.283 0.777  
#> 3 X2           -0.367      0.142    -2.59  0.00967


glm_fit <- glm(formula = Y ~ X1 + X2, data = dat, 
               family = extendedFamily::binomialEF("loglog"))
summary(glm_fit)
#> 
#> Call:
#> glm(formula = Y ~ X1 + X2, family = extendedFamily::binomialEF("loglog"), 
#>     data = dat)
#> 
#> Deviance Residuals: 
#>     Min       1Q   Median       3Q      Max  
#> -1.1029  -1.0022  -0.9105   1.3343   1.5243  
#> 
#> Coefficients:
#>             Estimate Std. Error z value Pr(>|z|)   
#> (Intercept)  0.65511    0.31229   2.098  0.03593 * 
#> X1          -0.04115    0.14559  -0.283  0.77745   
#> X2          -0.36678    0.14176  -2.587  0.00967 **
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> (Dispersion parameter for binomial family taken to be 1)
#> 
#>     Null deviance: 1332.9  on 999  degrees of freedom
#> Residual deviance: 1326.2  on 997  degrees of freedom
#> AIC: 1332.2
#> 
#> Number of Fisher Scoring iterations: 4
```

<sup>Created on 2021-12-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I don't believe any changes are needed to parsnip here, and folks can already make use of other link functions. Maybe we could add a note to [this page](https://parsnip.tidymodels.org/reference/details_logistic_reg_glm.html) about `family` being an engine argument?

**Comment by gmcmacran** [comment]
I looked over the above changes. I think that will cover it. Thanks.
