### ISSUE TITLE
Regression models should error when outcome is character

### ISSUE THREAD

**Issue by kcarnold** [tidymodels/parsnip#621]
The following should fail:

``` r
class(dplyr::storms$status)
#> [1] "character"
parsnip::fit(
  parsnip::decision_tree(mode = "regression"),
  status ~ wind,
  data = dplyr::storms)
#> parsnip model object
#> 
#> Fit time:  17ms 
#> n= 10010 
#> 
#> node), split, n, loss, yval, (yprob)
#>       * denotes terminal node
#> 
#> 1) root 10010 5636 tropical storm (0.3087912088 0.2542457542 0.4369630370)  
#>   2) wind>=62.5 3092    1 hurricane (0.9996765847 0.0000000000 0.0003234153) *
#>   3) wind< 62.5 6918 2545 tropical storm (0.0000000000 0.3678808904 0.6321191096)  
#>     6) wind< 32.5 2545    0 tropical depression (0.0000000000 1.0000000000 0.0000000000) *
#>     7) wind>=32.5 4373    0 tropical storm (0.0000000000 0.0000000000 1.0000000000) *
```

<sup>Created on 2021-12-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This then causes downstream problems because the model is set to regression mode. Note that when `mode = "classification"` we correctly get a data type error.

``` r
class(dplyr::storms$status)
#> [1] "character"
parsnip::fit(
  parsnip::decision_tree(mode = "classification"),
  status ~ wind,
  data = dplyr::storms)
#> Error: For a classification model, the outcome should be a factor.
```

<sup>Created on 2021-12-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think the condition on https://github.com/tidymodels/parsnip/blob/7cf4115c689f7578365731513e0fd0b0ca7069d7/R/fit_helpers.R#L16 is too strict: lacking a `levels` doesn't mean we've got a number.

**Comment by juliasilge** [comment]
We could make a little helper function like `levels_from_formula()` that does something like `all(map_lgl(eval_tidy(env$formula[[2]], env$data), is.numeric))`. 

This problem applies to `form_form()` and `form_xy()`; the other two are using [`check_outcome()`](https://github.com/tidymodels/parsnip/blob/dd36a954d58c73b67a118e0b79f79f770e9ce703/R/misc.R#L200) which does explicitly check the type.

**Comment by juliasilge** [comment]
Thanks for this report @kcarnold! 🙌
