### ISSUE TITLE
Add Cubist_rules Sparse Matrix Support Please!

### ISSUE THREAD

**Issue by tsengj** [tidymodels/parsnip#622]
Hi,

I'm a big fan of tidymodels, and found that cubist rules outperforms all my other models. but because it lacks the sparse matrix support, it is unable to cope with sparse data. Please add cubist rules into your sparse matrix support please?

```r
> library(parsnip)
> library(rules)
Loading required package: modeldata
> get_encoding("cubist_rules")
# A tibble: 1 x 7
  model        engine mode       predictor_indicators compute_intercept remove_intercept allow_sparse_x
  <chr>        <chr>  <chr>      <chr>                <lgl>             <lgl>            <lgl>         
1 cubist_rules Cubist regression none                 FALSE             FALSE            FALSE         
```

**Comment by topepo** [comment]
The only thing that we could do is to convert the sparse matrix to a dense data frame. The Cubist C code doesn't allow it so there's not much that can be done.

**Comment by juliasilge** [comment]
Can you explain a bit more about the process you were wanting to use? Are you wanting to come to `rules::cubist_rules()` with a sparse matrix that you made yourself? Or were you hoping for a [process like that demonstrated here, using a sparse "blueprint"](https://www.tidyverse.org/blog/2020/11/tidymodels-sparse-support/)? 

The second option there is not really possible because of what Max explained. If you have your own sparse matrix that you created, you could convert it yourself before fitting.

**Comment by tsengj** [comment]
Was hoping for the second option. If the second option is not an option, how do I convert a sparse matrix to a dense data frame?

I previously attempted the function below, and fed that into cubist train function, but that didn't work.
```r
sparse.model.matrix(~. , data = df_train)
```
To give you some context, i'm running a regression model to predict home prices. Zipcode as factor (hot encoded). 
It performs really well on a couple of zipcode, and outperforms xgb and glmnet. but when the area becomes larger, memory constraints and performance becomes an issues to cubist (not to xgb and glmnet).

Thanks in advanced.

**Comment by tsengj** [comment]
Was hoping for the second option.
I would like to clarify if i wasn't clear initially. 
My dateset is originally a dataframe. Due to the high number of dimensions (sparse columns: lots of 1 and 0s), i wanted to take advantage of the sparse blueprint to reduce the computation cost and memory constraints. Hence would like to feed the dataframe as sparse Matrix of class "dgCMatrix" into cubist.

I'm not clear on your suggested solution, were you suggesting that i simply turn it back to matrix and allow cubist to read (without the computation / memory benefits?). Because i tried inputing into the caret (as opposed to tidymodels) directly as sparse matrix dgCMatrix, and it produces an error. It only works if i remove the line "%>% Matrix(data = ., sparse=TRUE)"

FYI, i'm building a regression model and zipcode comes in as factor (hot encoding). When i work on a couple of zipcodes, cubist produces excellent results (beating glmnet and xgboost). But when i increase the number of records with different zipcodes, it quickly gets out of hand. Looking to work around memory and computation constraints. Was also looking to introduce text as features, but tackling this hurdle first.

Thanks

```r
> library(Matrix)
> train_sp <- baked_train %>% select(-price) %>% as.matrix() %>% Matrix(data = ., sparse=TRUE)
> train_y <- baked_train %>% pull(price)
> val_sp <- baked_test %>% select(-price) %>% as.matrix() %>% Matrix(data = ., sparse=TRUE)
> val_y <- baked_test %>% pull(price)
> #cubist model
> library('Cubist')
Loading required package: lattice
> library('caret')

Attaching package: ‘caret’

The following objects are masked from ‘package:yardstick’:

    precision, recall, sensitivity, specificity

The following object is masked from ‘package:purrr’:

    lift

> library(rules)

Attaching package: ‘rules’

The following object is masked from ‘package:dials’:

    max_rules

> cubist_grid <-
+   grid_max_entropy(
+     committees(range =c(1,100)),
+     neighbors(range = c(0,9)),
+     size = 25) %>% 
+   as.data.frame
> set.seed(25)
> system.time(
+   cubist_tuned <- train(
+     x = train_sp,
+     y = train_y,
+     method = "cubist",
+     tuneGrid = cubist_grid,
+     trControl = trainControl(method = "cv")
+   )
+ )
Something is wrong; all the RMSE metric values are missing:
      RMSE        Rsquared        MAE     
 Min.   : NA   Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA   Max.   : NA  
 NA's   :25    NA's   :25    NA's   :25   
Error: Stopping
In addition: Warning message:
In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
  There were missing values in resampled performance measures.
Timing stopped at: 1.19 0.24 9.88
```

**Comment by juliasilge** [comment]
Thank you for the added context. Yes, a dataframe is "dense" meaning that it doesn't use any special tricks to store sparse data like a sparse matrix does. I think the main thing to understand is that the algorithm used by `rules::cubist_rules()` does not handle sparse data with any additional boost or improvement, and in fact we are required to pass data in a dense format to the algorithm. 

Using a sparse blueprint is only helpful when the model algorithm you plan to use can handle sparse data; check out the ["current limits"](https://www.tidyverse.org/blog/2020/11/tidymodels-sparse-support/#current-limits) section of that blog post. (I believe the `LiblineaR` engine also can be used with a sparse blueprint.)

**Comment by topepo** [comment]
The Cubist and C50 R packages are wrappers around Quinlan's fairly old C code that is meant to be run at the command line. The approach that we took to porting is to emulate the file structure that Quinlan requires (which is basically a cvs file) and pass that in as a string to the C code. 

As an example, here is what it looks like for the first five rows of `mtcars`: 

```
> Cubist::makeDataFile(mtcars[1:5, 2:8], mtcars$mpg[1:5]) %>% cat()
21,6,160,110,3.90,2.620,16.46,0
21,6,160,110,3.90,2.875,17.02,0
22\.8,4,108,93,3.85,2.320,18.61,1
21\.4,6,258,110,3.08,3.215,19.44,1
18\.7,8,360,175,3.15,3.440,17.02,0
```

I could make `makeDataFile()` generic and add a sparse matrix method. The issue is that the data ends up taking as much memory (or more) than it would if it were in a data frame. 

The original C code can't leverage the sparse structure so that is really the bottleneck.
