### ISSUE TITLE
Improve documentation for engine arguments

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/parsnip#641]
Let's improve documentation for how to use engine arguments.

- We can expand [the `set_engine()` documentation](https://parsnip.tidymodels.org/dev/reference/set_engine.html) with another example as well as better text explanation of engine arguments (`@details`).
- We can create a little template about engine arguments to add to the main model pages so when folks are looking for specific arguments they see a nudge to understand engine arguments.

**Comment by topepo** [comment]
This should wait until #631 is merged
