### ISSUE TITLE
In xgboost, `ntreelimit` has been deprecated in favour of `iteration_range`

### ISSUE THREAD

**Issue by tiagomaie** [tidymodels/parsnip#655]
https://github.com/tidymodels/parsnip/blob/0af9c8617b7961dbf74b5a29578374e97ffa143a/R/boost_tree.R#L484-L486

L485 should instead be:
`pred <- xgb_pred(object$fit, newdata = new_data,  iterationrange = c(1, tree + 1), ntreelimit = NULL)`

`ntreelimit` has been deprecated.
It is `tree + 1` as in the xgboost [docs](https://cran.r-project.org/web/packages/xgboost/xgboost.pdf#Rfn.predict.xgb.Booster.1) they mention that `iteration_range` should be a half-open set.
This should fix the warnings given when running `tune::tune_grid` for example, see below.

``` r
library(parsnip)
library(dplyr)

# using iris dataset

# defining train/test split
train_ids <- 1:(nrow(iris) - 50)
test_ids <- (nrow(iris) - 49):nrow(iris)

# defining recipe
d_recipe <- recipes::recipe(
  Species ~ .,
  data = iris[train_ids, ] %>% dplyr::mutate(Species = factor(Species))
)

# defining model
g_model <-
  parsnip::boost_tree(trees = tune::tune()) %>%
  parsnip::set_engine("xgboost", objective = "binary:logistic") %>%
  parsnip::set_mode("classification")


# defining workflow
wf <- workflows::workflow() %>%
  workflows::add_recipe(d_recipe) %>%
  workflows::add_model(g_model)

# tuning params
res <- wf %>% tune::tune_grid(
    resamples=rsample::vfold_cv(
      recipes::bake(d_recipe %>% recipes::prep(), new_data = NULL)
    )
  )
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
#> [18:38:53] WARNING: amalgamation/../src/c_api/c_api.cc:718: `ntree_limit` is deprecated, use `iteration_range` instead.
#> [18:38:53] WARNING: amalgamation/../src/c_api/c_api.cc:718: `ntree_limit` is deprecated, use `iteration_range` instead.
#> [18:38:53] WARNING: amalgamation/../src/c_api/c_api.cc:718: `ntree_limit` is deprecated, use `iteration_range` instead.
...
#> [18:38:59] WARNING: amalgamation/../src/c_api/c_api.cc:718: `ntree_limit` is deprecated, use `iteration_range` instead.
#> [18:38:59] WARNING: amalgamation/../src/c_api/c_api.cc:718: `ntree_limit` is deprecated, use `iteration_range` instead.
#> [18:38:59] WARNING: amalgamation/../src/c_api/c_api.cc:718: `ntree_limit` is deprecated, use `iteration_range` instead.
```

<sup>Created on 2022-02-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I should note that this potential fix doesn't account for functionality that you can have with `iterationrange` but that it is currently not possible anyway with `ntreelimit`.

**Comment by juliasilge** [comment]
It looks like this was [part of v1.5.0](https://github.com/dmlc/xgboost/blob/master/NEWS.md#v150-2021-oct-11):

> In 1.4 we have a new prediction function in the C API which is used by the Python package. This release revises the R package to use the new prediction function as well. A new parameter iteration_range for the predict function is available, which can be used for specifying the range of trees for running prediction. (#6819, #7126)

And I believe this was released on CRAN in November 2021.
