### ISSUE TITLE
Integration with `sparklyr` is failing, starting with `parsnip` 2.0

### ISSUE THREAD

**Issue by edgararuiz** [tidymodels/parsnip#671]
Recent `sparklyr` GHA R checks are failing on `parsnip` tests.  These tests are new, and dev-version package testing is not yet working in GHA for `sparklyr`, so we didn't catch it until now.

reprex:
```r
library(sparklyr)
library(parsnip)

sc <- spark_connect("local")
iris_tbl <- sdf_copy_to(sc, iris)

decision_tree(engine = "spark") %>%
  set_mode("classification") %>%
  fit(Species ~ Sepal_Length + Petal_Length, iris_tbl)
#> Error in eval_tidy(env$formula[[2]], env$data): object 'Species' not found

spark_disconnect(sc)
```

It looks like this is the check in which it happens: https://github.com/tidymodels/parsnip/blob/b6db6763c82e4307978bdb54ed15d77607461a1f/R/fit_helpers.R#L9

Also confirmed here: https://github.com/sparklyr/sparklyr/runs/5483357141?check_suite_focus=true#step:19:1469

**Comment by topepo** [comment]
I think that this would be fixed if we wrapped it in a 

```r
if (!inherits(env$data, "tbl_spark")) {
  check_outcome(eval_tidy(env$formula[[2]], env$data), object) 
}
```
