### ISSUE TITLE
upkeep activities for parsnip and extensions

### ISSUE THREAD

**Issue by topepo** [tidymodels/parsnip#679]
testthat 3e etc.

**Comment by juliasilge** [comment]
I did poissonreg in tidymodels/poissonreg#32

**Comment by juliasilge** [comment]
I did discrim in tidymodels/discrim#50

**Comment by juliasilge** [comment]
I did rules in tidymodels/rules#47

**Comment by simonpcouch** [comment]
Related to #657

**Comment by juliasilge** [comment]
I did baguette in tidymodels/baguette#60

I believe that is all the extension packages done, so once we finish upkeep for parsnip this can be closed 🙏

**Comment by simonpcouch** [comment]
Closing, as it looks like other parsnip spring cleaning tests were taken care of pre-#699!
