### ISSUE TITLE
parsnip extension model definitions do not support tuning engine-specific args

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/parsnip#691]
In #351 we changed the `update()` functions to support tuning engine-specific args (not throwing them away) by using `update_engine_parameters()`. At least the rules model definitions still have the old handling of the dots:

https://github.com/tidymodels/parsnip/blob/9ce41c872d10690c28051ecd9ec24855ea817f2a/R/c5_rules.R#L103

This means that [folks cannot tune the engine-specific arguments of rules models](https://stackoverflow.com/questions/71510155/getting-more-information-about-c5-model-in-tidymodels).

``` r
library(tidymodels)
library(rules)
#> 
#> Attaching package: 'rules'
#> The following object is masked from 'package:dials':
#> 
#>     max_rules

C5_rules(trees = tune()) %>% 
    set_engine("C5.0", fuzzyThreshold = tune()) %>%
    extract_parameter_set_dials()
#> Collection of 1 parameters for tuning
#> 
#>  identifier  type    object
#>       trees trees nparam[+]

rand_forest(min_n = tune()) %>%
    set_mode("regression") %>%
    set_engine("ranger", 
               regularization.factor = tune(), 
               regularization.usedepth = tune()) %>%
    extract_parameter_set_dials()
#> Collection of 3 parameters for tuning
#> 
#>               identifier                    type    object
#>                    min_n                   min_n nparam[+]
#>    regularization.factor   regularization.factor nparam[+]
#>  regularization.usedepth regularization.usedepth dparam[+]
```

<sup>Created on 2022-03-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by simonpcouch** [comment]
Looks like a PR a la #351 that addresses this will need to be composed of a few different PRs as the tests for some of these update methods (and `tunable` machinery) live in extension packages.

The process:

* [ ] transition `update_dot_check` -> `update_engine_parameters` in parsnip
* [ ] add update tests for model specs tested in parsnip (mars)
* [ ] add tests to `update`-testing extension packages (refreshing `tunable` machinery if needed)
     * [ ] baguette: `bag_mars`, `bag_tree`
     * [ ] discrim: `discrim_flexible`, `discrim_linear`, `discrim_quad`, `discrim_regularized`, `naive_Bayes`
     * [ ] rules: `c5_rules`, `cubist_rules`, `rule_fit`
     * [ ] plsmod: `pls`
     * [ ] poissonreg or multilevelmod: `poisson_reg` 

A PR for the first two bullet points coming in a moment!

**Comment by hfrick** [comment]
Does this also apply to censored and `proportional_hazards()`?

**Comment by simonpcouch** [comment]
@hfrick #704 does indeed transition the internals of `update.proportional_hazards`, but it doesn't look like it will need to be accompanied by a PR to censored as `update.proportional_hazards` has been tested in parsnip. (Should this not be the case?) From a quick glance, it seems like censored's `tunable` internals work as they ought to, as well! So no need for a PR a la tidymodels/rules#51🦔

``` r
library(parsnip)
library(tune)

proportional_hazards() %>% 
  set_engine("survival", init = tune()) %>% 
  tunable()
#> # A tibble: 1 × 5
#>   name  call_info source     component            component_id
#>   <chr> <list>    <chr>      <chr>                <chr>       
#> 1 init  <NULL>    model_spec proportional_hazards engine
```

<sup>Created on 2022-04-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hfrick** [comment]
awesome, thank you!

**Comment by simonpcouch** [comment]
Ran some quick checks to make sure other extension's `tunable` methods are up to date and we're all good:

``` r
library(parsnip)
library(tune)
```

``` r
library(baguette)

bag_tree() %>% 
  set_engine("C5.0", trials = tune()) %>% 
  extract_parameter_set_dials()
#> Collection of 1 parameters for tuning
#> 
#>  identifier   type  object
#>      trials trials missing
#> The parameter `trials` needs a `param` object. 
#> See `vignette('dials')` to learn more.
```

``` r
library(discrim)

discrim_linear() %>% 
  set_engine("sda", lambda = tune()) %>% 
  extract_parameter_set_dials()
#> Collection of 1 parameters for tuning
#> 
#>  identifier   type  object
#>      lambda lambda missing
#> The parameter `lambda` needs a `param` object. 
#> See `vignette('dials')` to learn more.
```

``` r
library(rules)

C5_rules() %>% 
  set_engine("C5.0", trials = tune()) %>% 
  extract_parameter_set_dials()
#> Collection of 1 parameters for tuning
#> 
#>  identifier   type  object
#>      trials trials missing
#> The parameter `trials` needs a `param` object. 
#> See `vignette('dials')` to learn more.
```

``` r
library(plsmod)

pls() %>% 
  set_engine("mixOmics", tol = tune()) %>% 
  extract_parameter_set_dials()
#> Collection of 1 parameters for tuning
#> 
#>  identifier type  object
#>         tol  tol missing
#> The parameter `tol` needs a `param` object. 
#> See `vignette('dials')` to learn more.
```

``` r
library(poissonreg)

poisson_reg() %>% 
  set_engine("hurdle", dist = tune()) %>% 
  extract_parameter_set_dials()
#> Collection of 1 parameters for tuning
#> 
#>  identifier type  object
#>        dist dist missing
#> The parameter `dist` needs a `param` object. 
#> See `vignette('dials')` to learn more.
```

``` r
library(multilevelmod)

poisson_reg() %>% 
  set_engine("glmer", nAGQ = tune()) %>% 
  extract_parameter_set_dials()
#> Collection of 1 parameters for tuning
#> 
#>  identifier type  object
#>        nAGQ nAGQ missing
#> The parameter `nAGQ` needs a `param` object. 
#> See `vignette('dials')` to learn more.
```

<sup>Created on 2022-04-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

A think a good few of these just rely on `parsnip:::tunable_model_spec`.

#704 covers the rest of our bases in terms of testing, so closing in favor of that PR.🦑
