### ISSUE TITLE
Error fitting bagged tree: "No engines were loaded for 'bag_tree'"

### ISSUE THREAD

**Issue by shosaco** [tidymodels/parsnip#716]
Dear all,

When I try to create a bagged tree classification model using the latest CRAN parsnip version, the following error occurs:

```
Error in `fit()`:
! No engines were loaded for `bag_tree`. Please load a parsnip extension package that provides one. See https://www.tidymodels.org/find/parsnip/ 
```

This occurs independent of the R version or OS. Minimal example:

```
library(parsnip)
bag_tree() %>%
    set_mode("classification") %>%
    set_engine("rpart") %>% 
    fit(formula = cyl ~ ., data = mtcars)
```

The same with regression instead of classification.

Anything that I am missing?

Thanks in advance!
sandro

**Comment by EmilHvitfeldt** [comment]
Hello @shosaco 👋 

To use `bag_tree()` with {rpart} as an engine you need to load {baguette} as well. This is also noted in [`?details_bag_tree_rpart`](https://parsnip.tidymodels.org/reference/details_bag_tree_rpart.html#translation-from-parsnip-to-the-original-package-classification-).

``` r
library(parsnip)
library(baguette)

bag_tree() %>%
  set_mode("classification") %>%
  set_engine("rpart") %>% 
  fit(formula = Species ~ ., data = iris)
#> parsnip model object
#> 
#> Bagged CART (classification with 11 members)
#> 
#> Variable importance scores include:
#> 
#> # A tibble: 4 × 4
#>   term         value std.error  used
#>   <chr>        <dbl>     <dbl> <int>
#> 1 Petal.Width   90.5     0.877    11
#> 2 Petal.Length  89.6     1.26     11
#> 3 Sepal.Length  59.8     1.47     11
#> 4 Sepal.Width   36.4     1.90     11
```

<sup>Created on 2022-05-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by shosaco** [comment]
Hi Emil,

thanks so much! This was bugging me for a while, I only had working models where `bag_tree()` was contained in the `baguette` package. Everything clear now.

Thanks again,
sandro
