### ISSUE TITLE
Why null_model() performs better than any other regression methods in parsnip?

### ISSUE THREAD

**Issue by gundalav** [tidymodels/parsnip#726]
I am testing several regression models using [Tidyverse's parsnip][1].
Initially the best performing one is [rand_forest()][2], but after 
I add [null_model()][3], it is the latter one that is best in terms of RMSE.

All are done after parameter tuning and cross-validated resampling.

Here is the result of `null_model()`:

    > show_best(null_grid_results, metric = "rmse")
    # A tibble: 1 × 6
      .metric .estimator  mean     n std_err .config             
      <chr>   <chr>      <dbl> <int>   <dbl> <chr>               
    1 rmse    standard   0.421    10  0.0701 Preprocessor1_Model1
    > collect_metrics(null_grid_results) %>%
    +   filter(.metric == "rmse") %>%
    +   pull(mean) %>% mean()
    [1] 0.4209793

And the random forest:

```
> show_best(random_forest_grid_results, metric = "rmse")
# A tibble: 5 × 9
   mtry trees min_n .metric .estimator  mean     n std_err .config          
  <int> <int> <int> <chr>   <chr>      <dbl> <int>   <dbl> <chr>            
1  1224  1752    24 rmse    standard   0.420    10  0.0700 Preprocessor1_Mo…
2  1536  1533    22 rmse    standard   0.420    10  0.0702 Preprocessor1_Mo…
3   899  1979    40 rmse    standard   0.421    10  0.0702 Preprocessor1_Mo…
4  1771   646    33 rmse    standard   0.421    10  0.0701 Preprocessor1_Mo…
5  2127   100    22 rmse    standard   0.421    10  0.0700 Preprocessor1_Mo…

> collect_metrics(random_forest_grid_results) %>%
+   filter(.metric == "rmse") %>%
+   pull(mean) %>% mean()
[1] 0.4369724
```

This is my complete code. 
The RDS file that contains predictors and outcome can be downloaded [**here**](https://bit.ly/3yMuPjF).

```
library(tidyverse)
library(tidymodels)
library(rules)
library(baguette)
tidymodels_prefer()
library(doParallel)

prolif_feat_outcome_dat <- readRDS("prolif_feat_outcome_dat.rds")
# RDS file can be downloaded here: https://bit.ly/3yMuPjF

# 1. Splitting the data for resampling/validation ----------------------------

set.seed(1501)
prolif_feat_outcome_dat_split <- initial_split(prolif_feat_outcome_dat, strata = NULL)
prolif_feat_outcome_dat_train <- training(prolif_feat_outcome_dat_split)
prolif_feat_outcome_dat_test  <- testing(prolif_feat_outcome_dat_split)

set.seed(1502)
prolif_feat_outcome_dat_folds <- vfold_cv(prolif_feat_outcome_dat_train, strata = NULL, repeats = 1)

# 2. Tuning single model (random_forest) -------------------------------------------
random_forest_spec <-   rand_forest(mtry = tune(), min_n = tune(), trees = tune()) %>% 
  set_engine("ranger") %>%
  set_mode("regression") %>% 
  translate()

random_forest_feature_preproc_rec <- recipe(prolif_outcome ~ ., data = prolif_feat_outcome_dat_train) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_numeric_predictors()) 

random_forest_wflow <- workflow() %>%
  add_model(random_forest_spec) %>%
  add_recipe(random_forest_feature_preproc_rec )

random_forest_set <- extract_parameter_set_dials(random_forest_wflow) 

grid_ctrl <- control_grid(
  verbose = TRUE,
  save_pred = TRUE,
  parallel_over = "everything",
  save_workflow = TRUE
)
nof_grid <- 25
ptm <- proc.time()
cls <- makePSOCKcluster(parallel::detectCores(logical = FALSE))
registerDoParallel(cls)

set.seed(999)
random_forest_grid_results <- random_forest_wflow %>%
  tune_grid(
    param_info = random_forest_set,
    resamples = prolif_feat_outcome_dat_folds,
    grid = nof_grid,
    control = grid_ctrl
  )


stopCluster(cls)
proc.time() - ptm


show_best(random_forest_grid_results, metric = "rmse")
collect_metrics(random_forest_grid_results) %>%
  filter(.metric == "rmse") %>%
  pull(mean) %>% mean()

# 3. Tuning single model (null_model) -------------------------------------------

null_model_spec <-    null_model() %>% 
  set_engine("parsnip") %>% 
  set_mode("regression") %>%  
  translate()

null_model_feature_preproc_rec <- recipe(prolif_outcome ~ ., data = prolif_feat_outcome_dat_train) %>% 
  step_zv(all_predictors()) 

null_model_wflow <- workflow() %>%
  add_model(null_model_spec) %>%
  add_recipe(null_model_feature_preproc_rec )

null_model_set <- extract_parameter_set_dials(null_model_wflow) 

grid_ctrl <- control_grid(
  verbose = TRUE,
  save_pred = TRUE,
  parallel_over = "everything",
  save_workflow = TRUE
)
nof_grid <- 25
ptm <- proc.time()
cls <- makePSOCKcluster(parallel::detectCores(logical = FALSE))
registerDoParallel(cls)

set.seed(999)
null_model_grid_results <- null_model_wflow %>%
  tune_grid(
    param_info = null_model_set,
    resamples = prolif_feat_outcome_dat_folds,
    grid = nof_grid,
    control = grid_ctrl
  )


stopCluster(cls)
proc.time() - ptm

show_best(null_model_grid_results, metric = "rmse")
collect_metrics(null_model_grid_results) %>%
  filter(.metric == "rmse") %>%
  pull(mean) %>% mean()



```

I expected `null_model()` to perform way worse than `rand_forest()`?
My question is why `null_model()` perform best?
Is my approach correct? If not what is the correct way to implement it?

  [1]: https://www.tidymodels.org/find/parsnip/
  [2]: https://parsnip.tidymodels.org/reference/rand_forest.html
  [3]: https://parsnip.tidymodels.org/reference/null_model.html

**Comment by simonpcouch** [comment]
Thanks for the issue!

Can you please provide a minimal [reprex](https://github.com/tidyverse/reprex#what-is-a-reprex) (reproducible example)? I don't have access to your `prolif_feat_outcome_dat_folds` and other data objects. A reprex will help us troubleshoot your issue more quickly.🙂

**Comment by EmilHvitfeldt** [comment]
Cross-posted from https://stackoverflow.com/questions/72312575/why-null-model-perform-better-than-any-other-regression-methods-in-r-tidymodel

From the code you have posted, it appears that you have used the packages correctly. It is hard to say anything else without seeing the data. A `null_model()` predicts the mean of `prolif_outcome` regardless of what the predictors do. This null model can give better performance then other more complicated models, especially if there isn't much signal in the predictors.

**Comment by gundalav** [comment]
> Thanks for the issue!
> 
> Can you please provide a minimal [reprex](https://github.com/tidyverse/reprex#what-is-a-reprex) (reproducible example)? I don't have access to your `prolif_feat_outcome_dat_folds` and other data objects. A reprex will help us troubleshoot your issue more quickly.🙂

Thanks. I updated my OP with full running code right from the data splitting.
The RDS file that contains predictors and outcome can be downloaded [**here**](https://bit.ly/3yMuPjF).

Truly hope to hear from you again.

G.V.

**Comment by gundalav** [comment]
> Cross-posted from https://stackoverflow.com/questions/72312575/why-null-model-perform-better-than-any-other-regression-methods-in-r-tidymodel
> 
> From the code you have posted, it appears that you have used the packages correctly. It is hard to say anything else without seeing the data. A `null_model()` predicts the mean of `prolif_outcome` regardless of what the predictors do. This null model can give better performance then other more complicated models, especially if there isn't much signal in the predictors.

Thanks. I updated my OP with full running code right from the data splitting.
The RDS file that contains predictors and outcome can be downloaded [**here**](https://bit.ly/3yMuPjF).

Truly hope to hear from you again.

G.V.

**Comment by EmilHvitfeldt** [comment]
Okay, I'm able to reproduce the results that you are seeing as well. Is this your whole data set? There are a lot more columns than rows, which can be hard to handle for many of these models.

**Comment by gundalav** [comment]
> Okay, I'm able to reproduce the results that you are seeing as well. Is this your whole data set? There are a lot more columns than rows, which can be hard to handle for many of these models. So in this case it makes perfect sense why you are seeing these results. There doesn't appear to be a lot of information in the 22 observations of the training set that the model can pick up on.

@EmilHvitfeldt Yes this is the whole dataset. 
Is there anything we can do about it, e.g. what kind of feature preprocessing?
Or add more data is the only way to reasonably evaluate the model performance?

**Comment by juliasilge** [comment]
I just took a look at the data you shared and I notice that there are ~30 rows but ~10,000 columns. This is not a situation where modeling can be successful in general, and feature engineering doesn't change those basic concerns. You might check out these explanations:

- https://stats.stackexchange.com/questions/282663/why-is-n-p-a-problem-for-ols-regression
- https://stats.stackexchange.com/questions/139593/why-does-multiple-linear-regression-fail-when-the-number-of-variables-are-larger

Also, you might check out the book [_An Introduction to Statistical Learning_](https://www.statlearning.com/).
