### ISSUE TITLE
Why can't we include all predictors for tune_grid() with GAM model?

### ISSUE THREAD

**Issue by gundalav** [tidymodels/parsnip#730]
I was trying to `tune_grid()` with **[GAM model](https://parsnip.tidymodels.org/reference/gen_additive_mod.html)**, following @topepo post [here](https://community.rstudio.com/t/tune-grid-and-gam-model-incl-gam-formula/127206/2).

```
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
#> Warning: package 'broom' was built under R version 4.1.2
tidymodels_prefer()

gam_spec <- gen_additive_mod(select_features = tune()) %>% set_mode("regression")

gam_wflow <- 
  workflow() %>% 
  # smoothing must be specified here:
  add_model(gam_spec, formula = mpg ~ s(disp) + wt + gear) %>% 
  add_variables(predictors = c(everything()), outcomes = mpg)

set.seed(1)
car_folds <- bootstraps(mtcars, times = 5)

gam_res <- 
  gam_wflow %>% tune_grid(resamples = car_folds)

show_best(gam_res, metric = "rmse")
#> # A tibble: 2 × 7
#>   select_features .metric .estimator  mean     n std_err .config             
#>   <lgl>           <chr>   <chr>      <dbl> <int>   <dbl> <chr>               
#> 1 FALSE           rmse    standard    3.48     5   0.848 Preprocessor1_Model2
#> 2 TRUE            rmse    standard    3.48     5   0.848 Preprocessor1_Model1
```

It works fine.

But note that he only used 3 predictors.

`  add_model(gam_spec, formula = mpg ~ s(disp) + wt + gear) %>% 
`

When I tried to use all predictors with the following syntax

`  add_model(gam_spec, formula = mpg ~ .) %>% 
`

It failed by giving these errors:

```

> gam_res <- gam_wflow %>% 
+   tune_grid(resamples = car_folds)
x Bootstrap1: preprocessor 1/1, model 1/2: Error in terms.formula(gf, specials = c...
x Bootstrap1: preprocessor 1/1, model 2/2: Error in terms.formula(gf, specials = c...
x Bootstrap2: preprocessor 1/1, model 1/2: Error in terms.formula(gf, specials = c...
x Bootstrap2: preprocessor 1/1, model 2/2: Error in terms.formula(gf, specials = c...
x Bootstrap3: preprocessor 1/1, model 1/2: Error in terms.formula(gf, specials = c...
x Bootstrap3: preprocessor 1/1, model 2/2: Error in terms.formula(gf, specials = c...
x Bootstrap4: preprocessor 1/1, model 1/2: Error in terms.formula(gf, specials = c...
x Bootstrap4: preprocessor 1/1, model 2/2: Error in terms.formula(gf, specials = c...
x Bootstrap5: preprocessor 1/1, model 1/2: Error in terms.formula(gf, specials = c...
x Bootstrap5: preprocessor 1/1, model 2/2: Error in terms.formula(gf, specials = c...
Warning message:
All models failed. See the `.notes` column. 
> 
> show_best(gam_res, metric = "rmse")
Error in `estimate_tune_results()`:
! All of the models failed. See the .notes column.

```

What's the correct way to go about using all predictors for GAM?

GV

**Comment by juliasilge** [comment]
This is because of how the underlying GAM model uses the formula:

``` r
mgcv::gam(mpg ~ ., data = mtcars)
#> Error in terms.formula(gf, specials = c("s", "te", "ti", "t2", extra.special)): '.' in formula and no 'data' argument
```

<sup>Created on 2022-05-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In this model, you need to provide a [valid GAM formula](https://stat.ethz.ch/R-manual/R-devel/library/mgcv/html/formula.gam.html).

**Comment by gundalav** [comment]
> This is because of how the underlying GAM model uses the formula:
> 
> ```r
> mgcv::gam(mpg ~ ., data = mtcars)
> #> Error in terms.formula(gf, specials = c("s", "te", "ti", "t2", extra.special)): '.' in formula and no 'data' argument
> ```
> 
> Created on 2022-05-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)
> 
> In this model, you need to provide a [valid GAM formula](https://stat.ethz.ch/R-manual/R-devel/library/mgcv/html/formula.gam.html).

@juliasilge Does that mean we have to explicitly declare all the predictor column names?

G.V.

**Comment by juliasilge** [comment]
That is still a formula that does not work in the underlying GAM model unfortunately:

``` r
form <- as.formula(paste0("mpg ~", paste0("s(", colnames(mtcars[2:length(mtcars)]), ")", collapse = "+")))
form
#> mpg ~ s(cyl) + s(disp) + s(hp) + s(drat) + s(wt) + s(qsec) + 
#>     s(vs) + s(am) + s(gear) + s(carb)
mgcv::gam(form, data = mtcars)
#> Error in smooth.construct.tp.smooth.spec(object, dk$data, dk$knots): A term has fewer unique covariate combinations than specified maximum degrees of freedom
```

<sup>Created on 2022-05-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


You need to use a formula that works for that underlying implementation:

``` r
mgcv::gam(mpg ~ s(disp) + wt + gear, data = mtcars)
#> 
#> Family: gaussian 
#> Link function: identity 
#> 
#> Formula:
#> mpg ~ s(disp) + wt + gear
#> 
#> Estimated degrees of freedom:
#> 6.19  total = 9.19 
#> 
#> GCV score: 5.496548
```

<sup>Created on 2022-05-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
