### ISSUE TITLE
Multi-output regression problem using parsnip

### ISSUE THREAD

**Issue by bappa10085** [tidymodels/parsnip#764]
I want to perform multi-output regression where dependent variable is more than 1. I think `parsnip` allows only one output. In Python, `sklearn` supports [multi-output regression](https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html). In R, I could find only one package [MultivariateRandomForest](https://cran.r-project.org/web/packages/MultivariateRandomForest/index.html) for multi-output regression. Are you having any plan to make `parsnip` package capable of handeling multi-output regression in future?

**Comment by simonpcouch** [comment]
This is indeed possible with some engines, though we haven't documented this functionality well. Will go ahead and close in favor of #798, and provide further updates on that issue. :)
