### ISSUE TITLE
An explicit function for creating a resusable XGBoost model

### ISSUE THREAD

**Issue by CarmenCiardiello** [tidymodels/parsnip#779]
## Saving XGBoost `worklfow`

I have a couple of `xgboost` models in production that are saved as `workflow` objects in a RDS file. There seems to be some compatibility issues with the the updated version of `xgboost`. Not sure what/if there is a remedy to this, but having a function to explicitly save the workflow object as something this is reusable and compatible with `xgboost`.

**Comment by simonpcouch** [comment]
Thanks for the issue, @CarmenCiardiello!

For now, xgboost models fitted with parsnip (and possible wrappers like workflows, workflowsets, stacks) will be susceptible to the kind of instability across versions noted in the [xgboost documentation on saving and memory snapshots](https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html#a-note-on-backward-compatibility-of-models-and-memory-snapshots).

We're actively working on better infrastructure for supporting native serialization like xgboost's `xgb.save()`. That work currently lives at https://github.com/simonpcouch/bundle if you'd like to follow our development, but we will be integrating this functionality under the hood in objects outputted by tidymodels packages soon.

**Comment by CarmenCiardiello** [comment]
Thanks for pointing me in this direction!

**Comment by simonpcouch** [comment]
Closing in favor of #781. Thanks for the issue!
