### ISSUE TITLE
Add arithmetic operations for new weights classes

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidymodels/parsnip#783]
This is a bit of a contrived example but demonstrates what I am talking about:

``` r
library(recipes)

mtcars$cyl <- importance_weights(mtcars$cyl)
mtcars$cyl * 2
#> Error in `vec_arith()`:
#> ! <importance_weights> * <double> is not permitted
```
I find myself having to coerce back using `as.numeric` in plotting code.

**Comment by EmilHvitfeldt** [comment]
Hello @TylerGrantSmith 👋 

This is a deliberate choice on our side. This is a layer of defense against accidental modification of the case weights. Using `as.numeric()` or `as.double()` as you have done is the recommended path.
