### ISSUE TITLE
Adaboost

### ISSUE THREAD

**Issue by zhaoliang0302** [tidymodels/parsnip#825]
Hi, does parsnip support adaboost?

**Comment by simonpcouch** [comment]
Thanks for the issue! Glad that we can document this decision publicly.

We don't plan on supporting adaptive boosting in parsnip or any extension packages that we maintain, for now. We do support [gradient boosted trees via C5.0](https://parsnip.tidymodels.org/reference/details_boost_tree_C5.0.html), which loosely follow up on the ideas underlying Adaboost implementations, and are generally more versatile and tunable models.

Adaptive boosting is supported in caret via the ["ada"](https://cran.r-project.org/web/packages/ada/index.html) engine, and that package includes three of the classic Adaboost implementations via the `type` argument to `ada()`. That package's interface is quite principled, so if you'd like to make use of that modeling engine with parsnip, you could [build your own parsnip model](https://www.tidymodels.org/learn/develop/models/) with that engine without too many complications!
