### ISSUE TITLE
Stepwise linear regression engines (olsrr)

### ISSUE THREAD

**Issue by Marwolaeth** [tidymodels/parsnip#847]
## Missing olsrr

It seems like there is no `parsnip` support for stepwise regression algorithms, of which my favourite is [`olsrr`](https://olsrr.rsquaredacademy.com/). It performs variable selection for linear regression models by adding or removing predictor variables one at a time based on some criteria (p-value or AIC) in order to create a parsimonious model. Does anybody agree it's a good idea to include it?

I guess the implementation is not straightforward due to idiosyncratic nature of the algorithm (though somewhat similar to tuning). You may consider it unnecessary since ols_step_\*_\* are model selecting algorithms themselves.

Are stepwise algorithms reasonable candidates for `parsnip`?

P.S. This is my first feature request, XME

**Comment by topepo** [comment]
We won't implement this. Your mileage may vary, but classical stepwise methods have been shown to be problematic in terms of their statistical validity. 

I know they are still used a lot, so I suggest adding it as an engine in a separate package. Documentation to do that is [here](https://www.tidymodels.org/learn/develop/models/) and you can post new issues in this repo if you have any problems. We are happy to help you with that.

**Comment by Marwolaeth** [comment]
Ok, I got it

As an excuse, this interest is influenced by my first-ever statistical textbook: OpenIntro Statistics, section 9.2, particularly 9.2.2
