### ISSUE TITLE
Mode is either unnecessary or insufficiently expressive?

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/parsnip#85]
Thinking about long term maintainability here.

### Can `mode` be inferred from the data?

If `mode` is only needed to set some `fit`-time parameters to engines based on whether the problem is a regression or a classification problem, then `fit()` should infer the problem type and set parameters as necessary.

I think we discussed this in a video call at some point but I didn't quite understand why this doesn't work.

### Alternatively

Another way to think about `mode` is as a key for a convenience function that allows access to many models at once.

For example, consider `stats::glm()`. Gaussian linear regression is fundamentally different from gamma regression is fundamentally different from logistic regression, etc. But it's nice to have them all in the same place so `glm()` wraps them. `glm()` then needs some way to determine which model to fit, and uses the `family` argument to do so.

Now suppose you want to predict from a `glm` object. You have to do something like

```{r}
safe_predict.glm <- function(
  object,
  new_data,
  type = c(
    "link",
    "conf_int",
    "response",
    "class",
    "prob"
  ),
  ...) {

  fam <- family(object)$family

  type_by_family <- tibble::tribble(
    ~ param, ~ type,
    "binomial", c("class", "prob"),
    "gaussian", "response",
    "Gamma", "response",
    "inverse.gaussian", "response",
    "poisson", "response",
    "quasi", "response",
    "quasibinomial", c("class", "prob"),
    "quasipoisson", "response"
  )

  check_type_by_param(type_by_family, type, fam, all = c("link", "conf_int"))

  if (std_error && type != "link")
    stop(
      "Standard errors cannot be calculated unless `type = link`.",
      call. = FALSE
    )

  if (type == "link")
    predict_glm_link(object, new_data, std_error)
  else if (type == "conf_int")
    predict_glm_confint(object, new_data, level, std_error)
  else if (type == "response")
    predict_glm_response(object, new_data)
  else if (type %in% c("class", "prob") && fam == "binomial")
    predict_glm_binomial(object, new_data, type, threshold)
  else
    could_not_dispatch_error()
}
```

This is painful and has a high maintenance burden. Suppose someone wants to add a `gen_linear_model()` model to `parsnip`. Then some methods they implement will need to do this checking.

My understanding is that `mode` is supposed to help with this by narrowing down the set of reasonable actions for an object and allowing a sort of dispatching on mode. For example, you can't `predict(..., type = "class")` on a fit with `mode = "regression"`.

I'm not sure if `mode` is currently expressive enough, however. Consider:

```{r}
library(parsnip)

fit <- rand_forest() %>% 
  fit(hp ~ ., data = mtcars, engine = "ranger")

predict(fit$fit, mtcars, type = "quantiles", quantiles = c(0.1, 0.9))$predictions
#> Error in predict.ranger(fit$fit, mtcars, type = "quantiles", quantiles = c(0.1, : Error: Set quantreg=TRUE in ranger(...) for quantile prediction.
```

If we want to give a better error about setting `others = list(quantreg = TRUE)`, we still have to do the same sort of digging around as in the `glm` example.

So it maybe it makes sense to add an option `mode = "quantiles"`. But then when does this stop? There'll be some problem that "regression", "classification", and "quantile" isn't expressive enough for. Maybe these are enough for prediction, but they won't be enough if we start adding more inference related methods.

One (labor-intensive) solution would be to create different objects based on a `family`-like argument, manually filling in classes that we wish existed. For example, something like:

```{r}
log_reg <- general_linear_model(family = "logistic") %>% 
  fit(...)

gamma <- general_linear_model(family = "gamma") %>% 
  fit(...)

class(log_reg)
#> [1] "logistic_glim"   "model_fit"

class(gamma)
#> [1] "gamma_glim"   "model_fit"
```

Then we could dispatch on `logistic_glim` and `gamma_glim` without all the digging around instead a `glm` object, and have guarantees about the contents of the objects based on their construction.

**Comment by topepo** [comment]
I think that the mode is related to intent and is usually concordant with the type of data and/or outcome. 

I originally considered that survival models that are making predictions on _risk_ should be a different mode since they aren't interested in predicting the actual outcome. I'm 50/50 on doing this still but that would be a good example of what I mean. 

Also think about graph models. I don't think that we could infer that modeling task from the data.
