### ISSUE TITLE
FR: generalised synthetic control method

### ISSUE THREAD

**Issue by exsell-jc** [tidymodels/parsnip#862]
`gsynth` package: https://cran.r-project.org/web/packages/gsynth/gsynth.pdf

Paper: https://www.cambridge.org/core/journals/political-analysis/article/generalized-synthetic-control-method-causal-inference-with-interactive-fixed-effects-models/B63A8BD7C239DD4141C67DA10CD0E4F3

The main function of interest is `gsynth()`.

I think...
* the arguments `CV`, `cl`, `lambda`, `nlambda,`, `criterion`, `k` should be handled by `rsample` for cross validation.
* the arguments `formula`, `Y`, `D`, `X` should be handled by `recipes` for model specification.
* the argument `cov.ar` should probably be handled by `recipes` also, for up/down sampling
* the argument `normalize` should be handled by `recipes` also
* the argument `criterion` should probably be handled by `yardstick` for performance metrics.

Unsure about `min.T0` argument

```
library(gsynth)
data(gsynth)
out <- gsynth(Y ~ D + X1 + X2,
  data = simdata,
  parallel = FALSE,
  index = c("id","time"),
  force = "two-way",
  CV = TRUE,
  r = c(0, 5),
  se = FALSE)
print(out)
```

**Comment by simonpcouch** [comment]
Thanks for the issue! While we won't be including this functionality in this package, this sounds like a great idea for a parsnip extension package. We have some documentation on how to so [on the tidymodels website](https://www.tidymodels.org/learn/develop/models/).

**Comment by exsell-jc** [comment]
> Thanks for the issue! While we won't be including this functionality in this package, this sounds like a great idea for a parsnip extension package. We have some documentation on how to so [on the tidymodels website](https://www.tidymodels.org/learn/develop/models/).

Thanks @simonpcouch -- just quick question. Maybe I'm jumping the gun on hopes here, but when you say 'parsnip extension' package, does this mean that I should create a GitHub issue under `parsnip` to integrate `gsynth` or does parsnip extension allow for foreign packages to be used within the `tidymodels` framework, including `yardstick` or `workflows`?

**Comment by simonpcouch** [comment]
The second—parsnip's infrastructures allows for anyone to create their own package that integrates with parsnip (and thus the rest of the tidymodels ecosystem)! That link to the tidymodels website gives instructions on how to do so. [modeltime](https://github.com/business-science/modeltime) is one such package. :)
