### ISSUE TITLE
feature request: add way to remove intercept in linear_reg() lm

### ISSUE THREAD

**Issue by jospueyo** [tidymodels/parsnip#975]
## Feature: step_rm_intercept()

In situations when a linear model without intercept is needed, recipes does not provide a straightforward method. If you try the conventional way:

``` r
library(tidymodels)

rec <- recipe(mpg ~ cyl -1, data = mtcars)
#> Error in `recipe()`:
#> ! `-` is not allowed in a recipe formula. Use `step_rm()` instead.
#> Backtrace:
#>     ▆
#>  1. ├─recipes::recipe(mpg ~ cyl - 1, data = mtcars)
#>  2. └─recipes:::recipe.formula(mpg ~ cyl - 1, data = mtcars)
#>  3.   └─rlang::abort("`-` is not allowed in a recipe formula. Use `step_rm()` instead.")
```
I found a workaround in [stackoverflow](https://stackoverflow.com/questions/69004818/how-to-fit-a-model-without-an-intercept-using-r-tidymodels-workflow), where, by the way, @juliasilge already suggested to include this feature.

However, I do not know how to integrate this workaround when multiple models are set using `workflow_set` because the `add_model` step, suggested in the above answer, is not used:

``` r
library(tidymodels)

rec1 <- recipe(mpg ~ cyl + hp, data = mtcars)
rec2 <- rec1 |>
  step_rm(hp)

workflow_set(list(rec1, rec2), list(lm = linear_reg()))
#> # A workflow set/tibble: 2 × 4
#>   wflow_id    info             option    result    
#>   <chr>       <list>           <list>    <list>    
#> 1 recipe_1_lm <tibble [1 × 4]> <opts[0]> <list [0]>
#> 2 recipe_2_lm <tibble [1 × 4]> <opts[0]> <list [0]>
```

<sup>Created on 2023-05-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thanks for the package!

**Comment by simonpcouch** [comment]
Thanks for the issue, @jospueyo! The solution here is to use workflows' [model formula](https://workflows.tidymodels.org/reference/add_model.html). From workflows' docs:

> formula: An optional formula override to specify the terms of the model. Typically, the terms are extracted from the formula or recipe preprocessing methods. However, some models (like survival and bayesian models) use the formula not to preprocess, but to specify the structure of the model. In those cases, a formula specifying the model structure must be passed unchanged into the model call itself. This argument is used for those purposes.

So, `mpg ~ cyl + hp` specifies the terms, `mpg ~ cyl + hp - 1` specifies the model structure which `lm()` knows how to interpret.

For example:

``` r
library(parsnip)
library(workflows)

# via base:
lm(mpg ~ cyl + hp - 1, mtcars)
#> 
#> Call:
#> lm(formula = mpg ~ cyl + hp - 1, data = mtcars)
#> 
#> Coefficients:
#>     cyl       hp  
#>  5.4036  -0.1075

# via parsnip
linear_reg() %>% fit(mpg ~ cyl + hp - 1, mtcars)
#> parsnip model object
#> 
#> 
#> Call:
#> stats::lm(formula = mpg ~ cyl + hp - 1, data = data)
#> 
#> Coefficients:
#>     cyl       hp  
#>  5.4036  -0.1075

# via workflows
workflow() %>%
  add_formula(mpg ~ cyl) %>%
  add_model(linear_reg(), formula = mpg ~ cyl + hp - 1) %>%
  fit(mtcars)
#> Error in eval(predvars, data, env): object 'hp' not found
```

<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
