### ISSUE TITLE
Returning preductions along with original data (especially when using spark)

### ISSUE THREAD

**Issue by scottporter** [tidymodels/parsnip#984]
## Feature

This might already exist, and I just haven't figured it out.

I'm using spark ml in the background and I would like to get a prediction from a model that includes the original data.  Getting a column with just the predictions is not what I'd like in spark.

Like I said, I'm using spark ml in the background to fit an lm model.  If I were to use `sparklyr` directly, I could do a call to:

`sparklyr::ml_linear_regression` to fit the model and then do a call to  `sparklyr::ml_predict` to get the prediction.

This gives me a spark table with the original data plus the prediction, which is what I want.

However, if I use `parsnip::fit`, I can't get to that same output.  

The default `post` actions have a `select` call to get rid of the original columns:

```
linreg_reg_spec <-
  parsnip::linear_reg() %>%
  parsnip::set_engine("spark") %>%
  parsnip::translate()

print(linreg_reg_spec$method$pred$numeric$post)
# prints the following:
# function (results, object) 
# {
#     results <- dplyr::rename(results, pred = prediction)
#     results <- dplyr::select(results, pred)
#     results
# }
# <bytecode: 0x5584f0c517d8>
#  <environment: namespace:parsnip>
```

I can force it to not delete the extra columns created in the `sparklyr::ml_predict` call by doing something like 

```
my_fitted_model$spec$method$pred$numeric$post <- function(results, object) {
  results <- dplyr::rename(results, pred = prediction)
  results
  }
```
But I haven't found an easy way to specify this behavior using `parsnip` functions as intended.

I don't want to have to merge these results in with the original data.  That would require me to use spark specific code, and if I'm going to do that, I should probably just stick with `sparklyr::ml_linear_regression` .

Is there already a way to request that `predict` pass on the original columns?  If not, it would be very useful, at least in the case of spark.

**Comment by simonpcouch** [comment]
Thanks for the issue! Does the [`augment()` function](https://parsnip.tidymodels.org/reference/augment.html) address this? When supplied a model and a dataset, the function will return the dataset with the model's predictions appended to it.

**Comment by scottporter** [comment]
I tried that.  It throws errors with spark data frames.

**Comment by simonpcouch** [comment]
Judging by the error message, I might try and supply `mtcars` rather than `spark_mtcars` to `augment()`. If that doesn't do the trick, can you please provide a minimal [reprex](https://github.com/tidyverse/reprex#what-is-a-reprex) (reproducible example)? A reprex will help me troubleshoot and fix your issue more quickly.🙂

**Comment by scottporter** [comment]
We absolutely want to keep the data in spark the whole time.  With the real data we use, it won't fit in memory.

**Comment by scottporter** [comment]
``` r
getwd()
#> [1] "/tmp/RtmpdD6GjU/reprex-d0ed8a8c29-stuck-crane"
library(magrittr)
system("wget https://archive.apache.org/dist/spark/spark-3.1.3/spark-3.1.3-bin-hadoop2.7.tgz")
system("tar xvzf spark-3.1.3-bin-hadoop2.7.tgz")
Sys.setenv("SPARK_HOME" = "spark-3.1.3-bin-hadoop2.7")
SparkR::sparkR.session()
#> Spark package found in SPARK_HOME: spark-3.1.3-bin-hadoop2.7
#> Java ref type org.apache.spark.sql.SparkSession id 4
conf <- sparklyr::spark_config() 
conf$`sparklyr.cores.local` <- 2
conf$`sparklyr.shell.driver-memory` <- "1G"
conf$spark.memory.fraction <- 0.2
sc <- sparklyr::spark_connect(master = "local", config = conf)

data("mtcars")

spark_mtcars <- dplyr::copy_to(sc, mtcars)

mtcars_model <- parsnip::linear_reg() %>%
  parsnip::set_engine("spark") %>%
  parsnip::fit(mpg ~ ., data = spark_mtcars)

# current behavior
mtcars_predictions_default <- predict(
  mtcars_model,
  spark_mtcars
)

colnames(mtcars_predictions_default)
#> [1] "pred"

# error if try to use augment
mtcars_predictions_augment <- parsnip::augment(
  mtcars_model,
  spark_mtcars
)
#> Error: Input must be a vector, not a <tbl_spark/tbl_sql/tbl_lazy/tbl> object.

# desired behavior
mtcars_model_hack <- mtcars_model
mtcars_model_hack$spec$method$pred$numeric$post <- function(results, object) {
  results <- dplyr::rename(results, pred = prediction)
  results
}
mtcars_predictions_desired <- predict(
  mtcars_model_hack,
  spark_mtcars
)

colnames(mtcars_predictions_desired)
#>  [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
#> [11] "carb" "pred"
```

<sup>Created on 2023-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by scottporter** [comment]
I apologize for the long post... but hopefully this gives useful background on why someone would want to get back the predictions with the original data.   In spark, it's really easy to get two datasets that start in the same order out of order.

I was digging through the `sparklyr` git issues, and the reason why the `sparklyr` ml predict functions return all the original columns in addition to the predict column is that the  spark documentation doesn't make any guarantee of preserving row order for most functions.  

See the comments here: https://github.com/sparklyr/sparklyr/blob/4794dd7120f7bee437007d898319424a11e59e8d/R/ml_utils.R#L97-L126 and here: https://github.com/sparklyr/sparklyr/issues/650  

Release notes show this was re-written in `sparklyr` version 0.5 https://github.com/sparklyr/sparklyr/blob/main/NEWS.md

I understand that there was a conscious decision to leave out the original variables in `parsnip` in order to make the output the same as we get from base `predict` function.  But this does seem a bit riskier when you are working with spark dataets than it is when you are working with R dataframes (where there are more guarantees are made about functions not re-ordering the data).  I think this is why it is really important to provide an interface like `parsnip::augment`.  And in my mind, ideally `parsnip::augment` would just return the same dataset that `sparklyr` does.  They've already gone through all the effort to keep an id all the way through and then re-order the dataset identically as when the process started.  So though spark the API isn't making a guarantee, `sparklyr` is, and it seems useful to rely on that.

Since the spark documentation doesn't provide a guarantee for which functions change order and which don't, it adds some risk. So if a function that wouldn't have changed the order of your data in an R dataframe does change the order in a spark dataset, your predict column and your data could get out of sync and it would be unexpected for someone who is more familiar with R than they are with spark.

For example, what if you augment your dataset by adding in a new variable to your dataset using a left join?  In an R dataframe you'd expect that you can still bind in the predict results.  But not in spark.  Since the behavior is different that what they have come to expect in R, it will be easy to get the predictions out of line.

Perhaps what I am saying is obvious and doesn't need a reprex to illustrate, but since I already had yesterday's reprex, I've gone ahead and done so.  I've done a `left_join` in the example below.  You could extend this by playing around with which spark functions change order and which don't, but since it isn't guaranteed in the spark API documentation, it's all just relying on current implementation in spark.  Relying on current implementation seems more risky than what the `sparklyr` team did (defensively programming and assuming that no guarantees exist for row order after any function in spark).

``` r
# spark setup
getwd()
#> [1] "/tmp/RtmpnQ5Mj4/reprex-d10524562cf-choky-barb"
system("wget https://archive.apache.org/dist/spark/spark-3.1.3/spark-3.1.3-bin-hadoop2.7.tgz")
system("tar xvzf spark-3.1.3-bin-hadoop2.7.tgz")
Sys.setenv("SPARK_HOME" = "spark-3.1.3-bin-hadoop2.7")
SparkR::sparkR.session()
#> Spark package found in SPARK_HOME: spark-3.1.3-bin-hadoop2.7
#> Java ref type org.apache.spark.sql.SparkSession id 1
conf <- sparklyr::spark_config() 
conf$`sparklyr.cores.local` <- 2
conf$`sparklyr.shell.driver-memory` <- "1G"
conf$spark.memory.fraction <- 0.2
sc <- sparklyr::spark_connect(master = "local", config = conf)

library(magrittr)

# creating a dataset where we multiply by 2 to make a really predictable regression
my_numbers <- tibble::tibble(
  counting = 1:1000000
) %>%
  dplyr::mutate(counting_x_2 = counting * 2)

spark_numbers <- dplyr::copy_to(sc, my_numbers, repartition = 9)

numbers_model <- parsnip::linear_reg() %>%
  parsnip::set_engine("spark") %>%
  parsnip::fit(counting_x_2 ~ counting, data = spark_numbers)

# current behavior
parsnip_prediction_default <- predict(
  numbers_model,
  spark_numbers
)

colnames(parsnip_prediction_default)
#> [1] "pred"

# even though I can't find a guarantee in the spark documentation, if you just stick  
#  with bind_cols, and do the matching immediately, it is likely to work
spark_numbers_immediate_with_prediction_default <- sparklyr::sdf_bind_cols(
  spark_numbers,
  parsnip_prediction_default
)

# Now let's collect into memory and check it
local_numbers_immediate_with_prediction_default <- dplyr::collect(
  spark_numbers_immediate_with_prediction_default
)

print(head(local_numbers_immediate_with_prediction_default))
#> # A tibble: 6 x 3
#>   counting counting_x_2  pred
#>      <int>        <dbl> <dbl>
#> 1        1            2     2
#> 2        2            4     4
#> 3        3            6     6
#> 4        4            8     8
#> 5        5           10    10
#> 6        6           12    12

# pred should always exactly equal counting_x_2
testthat::expect_equal(
  local_numbers_immediate_with_prediction_default$counting_x_2,
  local_numbers_immediate_with_prediction_default$pred
)

# However, let's merge in another variable into our spark dataset before we 
#  merge in the predictions

number_odd_even<- tibble::tibble(
  counting = 1:2000000
) %>%
  dplyr::mutate(odd_even = 
    dplyr::case_when(
      counting %% 2 == 0 ~ "even",
      TRUE ~ "odd"
      )
  )

spark_odd_even <- dplyr::copy_to(sc, number_odd_even, repartition = 13)

# This wouldn't change the order in an R dataframe, so people might expect that 
#   same behavior with spark

spark_numbers_augmented_default <- dplyr::left_join(
  spark_numbers, 
  spark_odd_even, 
  by = "counting"
)

# let's now match in our predictions

spark_numbers_augmented_with_prediction_default <- sparklyr::sdf_bind_cols(
  spark_numbers_augmented_default,
  parsnip_prediction_default
)

# Now let's collect into memory and check it

local_numbers_augmented_with_prediction_default <- dplyr::collect(
  spark_numbers_augmented_with_prediction_default
)

print(head(local_numbers_augmented_with_prediction_default))
#> # A tibble: 6 x 4
#>   counting counting_x_2 odd_even  pred
#>      <int>        <dbl> <chr>    <dbl>
#> 1       12           24 even         2
#> 2       13           26 odd          4
#> 3       14           28 even         6
#> 4       18           36 even         8
#> 5       38           76 even        10
#> 6       46           92 even        12

# pred should always exactly equal counting_x_2
#   but likely doesn't because order in spark  isn't guaranteed
testthat::expect_equal(
  local_numbers_augmented_with_prediction_default$counting_x_2,
  local_numbers_augmented_with_prediction_default$pred
)
#> Error: local_numbers_augmented_with_prediction_default$counting_x_2 not equal to local_numbers_augmented_with_prediction_default$pred.
#> 1000000/1000000 mismatches (average diff: 625103)
#> [1]  24 -  2 ==  22
#> [2]  26 -  4 ==  22
#> [3]  28 -  6 ==  22
#> [4]  36 -  8 ==  28
#> [5]  76 - 10 ==  66
#> [6]  92 - 12 ==  80
#> [7] 134 - 14 == 120
#> [8] 140 - 16 == 124
#> [9] 186 - 18 == 168
#> ...

# the desired behavior (at least for the `parsnip::augment` function)
#   the hack below proxies this behavior by not deleting the original variables
#   that `sparklyr` goes through the trouble of returning to us
numbers_model_hack <- numbers_model
numbers_model_hack$spec$method$pred$numeric$post <- function(results, object) {
  results <- dplyr::rename(results, pred = prediction)
  results
}
parsnip_predictions_desired <- predict(
  numbers_model_hack,
  spark_numbers
)

colnames(parsnip_predictions_desired)
#> [1] "counting"     "counting_x_2" "pred"

# Now if we augment the data, it doesn't matter, since original data is in same
#  spark dataset as predictions

spark_numbers_with_prediction_desired <- dplyr::left_join(
  parsnip_predictions_desired,
  spark_odd_even,
  by="counting"
)

local_numbers_with_prediction_desired <- dplyr::collect(
  spark_numbers_with_prediction_desired
)

print(head(local_numbers_with_prediction_desired))
#> # A tibble: 6 x 4
#>   counting counting_x_2  pred odd_even
#>      <int>        <dbl> <dbl> <chr>   
#> 1       12           24    24 even    
#> 2       13           26    26 odd     
#> 3       14           28    28 even    
#> 4       18           36    36 even    
#> 5       38           76    76 even    
#> 6       46           92    92 even

testthat::expect_equal(
  local_numbers_with_prediction_desired$counting_x_2,
  local_numbers_with_prediction_desired$pred
)
```

<sup>Created on 2023-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by scottporter** [comment]
I neglected to include an example using a local R dataframe to demonstrate why someone might not be expecting the spark behavior.

I've standardized my own coding around `dplyr` because in general, the same exact code can run on a local dataframe and a spark dataset and a jdbc database source, but there are a few gotchas like this that I've learned to be careful of.

But anyway, if you are used to working with R dataframes, you might get used to things like the below working.

``` r
library(magrittr)

# creating a dataset where we multiply by 2 to make a really predictable regression
my_numbers <- tibble::tibble(
  counting = 1:1000000
) %>%
  dplyr::mutate(counting_x_2 = counting * 2)

numbers_model <- parsnip::linear_reg() %>%
  parsnip::set_engine("lm") %>%
  parsnip::fit(counting_x_2 ~ counting, data = my_numbers)

# current behavior
parsnip_prediction_default <- predict(
  numbers_model,
  my_numbers
)

colnames(parsnip_prediction_default)
#> [1] ".pred"

# let's match in the prediction immediately
numbers_immediate_with_prediction_default <- dplyr::bind_cols(
  my_numbers,
  parsnip_prediction_default
)

print(head(numbers_immediate_with_prediction_default))
#> # A tibble: 6 x 3
#>   counting counting_x_2 .pred
#>      <int>        <dbl> <dbl>
#> 1        1            2  2.00
#> 2        2            4  4.00
#> 3        3            6  6.00
#> 4        4            8  8.00
#> 5        5           10 10.0 
#> 6        6           12 12.0

# pred should always exactly equal counting_x_2
testthat::expect_equal(
  numbers_immediate_with_prediction_default$counting_x_2,
  numbers_immediate_with_prediction_default$.pred
)

# However, let's merge in another variable before we 
#  merge in the predictions

number_odd_even<- tibble::tibble(
  counting = 1:2000000
) %>%
  dplyr::mutate(odd_even = 
    dplyr::case_when(
      counting %% 2 == 0 ~ "even",
      TRUE ~ "odd"
      )
  )

# This won't change the order in an R dataframe

numbers_augmented_default <- dplyr::left_join(
  my_numbers, 
  number_odd_even, 
  by = "counting"
)

# let's now match in our predictions

numbers_augmented_with_prediction_default <- dplyr::bind_cols(
  numbers_augmented_default,
  parsnip_prediction_default
)

print(head(numbers_augmented_with_prediction_default))
#> # A tibble: 6 x 4
#>   counting counting_x_2 odd_even .pred
#>      <int>        <dbl> <chr>    <dbl>
#> 1        1            2 odd       2.00
#> 2        2            4 even      4.00
#> 3        3            6 odd       6.00
#> 4        4            8 even      8.00
#> 5        5           10 odd      10.0 
#> 6        6           12 even     12.0

# pred still always exactly equal counting_x_2
#  since order was preserved by the `left_join` above
testthat::expect_equal(
  numbers_augmented_with_prediction_default$counting_x_2,
  numbers_augmented_with_prediction_default$.pred
)
```

<sup>Created on 2023-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by scottporter** [comment]
I just noticed that the `sparklyr` release notes for version 1.7.6 include this note:

```
Fixes augment() when the model was fitted via parsnip (https://github.com/sparklyr/sparklyr/issues/3233)
```

I'll update and see if this helps at all.

**Comment by scottporter** [comment]
I tried my first reprex in rstudio.cloud where it was easy to quickly install the latest version of `parsnip` and `sparklyr`.

`parsnip::augment` now works with spark datasets, and it seems to be running the sparklyr model under the hood.  So it looks like someone beat me to the suggestion.  :)

Sorry for the false alarm.  I should have run the reprex with the latest versions originally.

**Comment by scottporter** [comment]
I tried my first reprex in rstudio.cloud where it was easy to quickly install the latest version of `parsnip` and `sparklyr`.

`parsnip::augment` now works with spark datasets, and it seems to be running the sparklyr model under the hood.  So it looks like someone beat me to the suggestion.  :)

Sorry for the false alarm.  I should have run the reprex with the latest versions originally.

**Comment by simonpcouch** [comment]
Awesome, glad you found a fix and thanks for posting it here!
